/*
Moolabs API

Testing BudgetsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package moolabs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/moolabs/moolabs-go"
)

func Test_moolabs_BudgetsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BudgetsAPIService AcknowledgeAlert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var budgetId string
		var alertId string

		resp, httpRes, err := apiClient.BudgetsAPI.AcknowledgeAlert(context.Background(), budgetId, alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService CreateBudget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BudgetsAPI.CreateBudget(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService GetBudget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var budgetId string

		resp, httpRes, err := apiClient.BudgetsAPI.GetBudget(context.Background(), budgetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService GetBudgetAlerts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var budgetId string

		resp, httpRes, err := apiClient.BudgetsAPI.GetBudgetAlerts(context.Background(), budgetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService GetBudgetStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BudgetsAPI.GetBudgetStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService ListBudgets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BudgetsAPI.ListBudgets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BudgetsAPIService UpdateBudget", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var budgetId string

		resp, httpRes, err := apiClient.BudgetsAPI.UpdateBudget(context.Background(), budgetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
