/*
Moolabs API

Testing BillingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package moolabs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/moolabs/moolabs-go"
)

func Test_moolabs_BillingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BillingAPIService RetryRemediationEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var usageEventId string

		resp, httpRes, err := apiClient.BillingAPI.RetryRemediationEvent(context.Background(), usageEventId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
