/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.2.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// FxRatesAPIService FxRatesAPI service
type FxRatesAPIService service

type ApiCreateFxRateEndpointV1Request struct {
	ctx context.Context
	ApiService *FxRatesAPIService
	createFxRateRequest *CreateFxRateRequest
}

func (r ApiCreateFxRateEndpointV1Request) CreateFxRateRequest(createFxRateRequest CreateFxRateRequest) ApiCreateFxRateEndpointV1Request {
	r.createFxRateRequest = &createFxRateRequest
	return r
}

func (r ApiCreateFxRateEndpointV1Request) Execute() (*FxRateResponse, *http.Response, error) {
	return r.ApiService.CreateFxRateEndpointV1Execute(r)
}

/*
CreateFxRateEndpointV1 Create Fx Rate Endpoint

Create a new FX rate version.

This endpoint creates a versioned FX rate for converting credits to USD.
FX rates are effective at a specific timestamp and can be locked to grants.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateFxRateEndpointV1Request
*/
func (a *FxRatesAPIService) CreateFxRateEndpointV1(ctx context.Context) ApiCreateFxRateEndpointV1Request {
	return ApiCreateFxRateEndpointV1Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return FxRateResponse
func (a *FxRatesAPIService) CreateFxRateEndpointV1Execute(r ApiCreateFxRateEndpointV1Request) (*FxRateResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *FxRateResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FxRatesAPIService.CreateFxRateEndpointV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/fx-rates/rates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createFxRateRequest == nil {
		return localVarReturnValue, nil, reportError("createFxRateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createFxRateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateValueRecognitionEntryEndpointV1FxRequest struct {
	ctx context.Context
	ApiService *FxRatesAPIService
	createValueRecognitionRequest *CreateValueRecognitionRequest
}

func (r ApiCreateValueRecognitionEntryEndpointV1FxRequest) CreateValueRecognitionRequest(createValueRecognitionRequest CreateValueRecognitionRequest) ApiCreateValueRecognitionEntryEndpointV1FxRequest {
	r.createValueRecognitionRequest = &createValueRecognitionRequest
	return r
}

func (r ApiCreateValueRecognitionEntryEndpointV1FxRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.CreateValueRecognitionEntryEndpointV1FxExecute(r)
}

/*
CreateValueRecognitionEntryEndpointV1Fx Create Value Recognition Entry Endpoint

Create a VALUE_RECOGNITION journal entry.

This endpoint creates a journal entry for revenue recognition in USD.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateValueRecognitionEntryEndpointV1FxRequest
*/
func (a *FxRatesAPIService) CreateValueRecognitionEntryEndpointV1Fx(ctx context.Context) ApiCreateValueRecognitionEntryEndpointV1FxRequest {
	return ApiCreateValueRecognitionEntryEndpointV1FxRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FxRatesAPIService) CreateValueRecognitionEntryEndpointV1FxExecute(r ApiCreateValueRecognitionEntryEndpointV1FxRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FxRatesAPIService.CreateValueRecognitionEntryEndpointV1Fx")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/fx-rates/value-recognition/entry"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createValueRecognitionRequest == nil {
		return localVarReturnValue, nil, reportError("createValueRecognitionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createValueRecognitionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetFxRateAtEndpointV1Request struct {
	ctx context.Context
	ApiService *FxRatesAPIService
	getFxRateRequest *GetFxRateRequest
}

func (r ApiGetFxRateAtEndpointV1Request) GetFxRateRequest(getFxRateRequest GetFxRateRequest) ApiGetFxRateAtEndpointV1Request {
	r.getFxRateRequest = &getFxRateRequest
	return r
}

func (r ApiGetFxRateAtEndpointV1Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetFxRateAtEndpointV1Execute(r)
}

/*
GetFxRateAtEndpointV1 Get Fx Rate At Endpoint

Get FX rate effective at a specific timestamp.

Returns the FX rate that was effective at the given timestamp.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetFxRateAtEndpointV1Request
*/
func (a *FxRatesAPIService) GetFxRateAtEndpointV1(ctx context.Context) ApiGetFxRateAtEndpointV1Request {
	return ApiGetFxRateAtEndpointV1Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FxRatesAPIService) GetFxRateAtEndpointV1Execute(r ApiGetFxRateAtEndpointV1Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FxRatesAPIService.GetFxRateAtEndpointV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/fx-rates/rates/at"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.getFxRateRequest == nil {
		return localVarReturnValue, nil, reportError("getFxRateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.getFxRateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProcessValueRecognitionV1FxRequest struct {
	ctx context.Context
	ApiService *FxRatesAPIService
	processValueRecognitionRequest *ProcessValueRecognitionRequest
}

func (r ApiProcessValueRecognitionV1FxRequest) ProcessValueRecognitionRequest(processValueRecognitionRequest ProcessValueRecognitionRequest) ApiProcessValueRecognitionV1FxRequest {
	r.processValueRecognitionRequest = &processValueRecognitionRequest
	return r
}

func (r ApiProcessValueRecognitionV1FxRequest) Execute() (*ValueRecognitionResponse, *http.Response, error) {
	return r.ApiService.ProcessValueRecognitionV1FxExecute(r)
}

/*
ProcessValueRecognitionV1Fx Process Value Recognition

Process burn allocations for a journal entry and create VALUE_RECOGNITION postings.

This endpoint:
- Gets all burn allocations for a journal entry
- Computes USD value for each allocation (using locked FX rates or effective_at rate)
- Creates VALUE_RECOGNITION postings in USD

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiProcessValueRecognitionV1FxRequest
*/
func (a *FxRatesAPIService) ProcessValueRecognitionV1Fx(ctx context.Context) ApiProcessValueRecognitionV1FxRequest {
	return ApiProcessValueRecognitionV1FxRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ValueRecognitionResponse
func (a *FxRatesAPIService) ProcessValueRecognitionV1FxExecute(r ApiProcessValueRecognitionV1FxRequest) (*ValueRecognitionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ValueRecognitionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FxRatesAPIService.ProcessValueRecognitionV1Fx")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/fx-rates/value-recognition/process"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.processValueRecognitionRequest == nil {
		return localVarReturnValue, nil, reportError("processValueRecognitionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.processValueRecognitionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
