/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.3.0-rc4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"os"
)


// QuoteContractsAPIService QuoteContractsAPI service
type QuoteContractsAPIService service

type ApiAddQuoteContractParticipantV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	addContractParticipantRequest *AddContractParticipantRequest
}

func (r ApiAddQuoteContractParticipantV1Request) AddContractParticipantRequest(addContractParticipantRequest AddContractParticipantRequest) ApiAddQuoteContractParticipantV1Request {
	r.addContractParticipantRequest = &addContractParticipantRequest
	return r
}

func (r ApiAddQuoteContractParticipantV1Request) Execute() (*ContractParticipantResponse, *http.Response, error) {
	return r.ApiService.AddQuoteContractParticipantV1Execute(r)
}

/*
AddQuoteContractParticipantV1 Add Quote Contract Participant

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiAddQuoteContractParticipantV1Request
*/
func (a *QuoteContractsAPIService) AddQuoteContractParticipantV1(ctx context.Context, quoteId string) ApiAddQuoteContractParticipantV1Request {
	return ApiAddQuoteContractParticipantV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return ContractParticipantResponse
func (a *QuoteContractsAPIService) AddQuoteContractParticipantV1Execute(r ApiAddQuoteContractParticipantV1Request) (*ContractParticipantResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ContractParticipantResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.AddQuoteContractParticipantV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/participants"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.addContractParticipantRequest == nil {
		return localVarReturnValue, nil, reportError("addContractParticipantRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.addContractParticipantRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateQuoteContractThreadV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	createContractThreadRequest *CreateContractThreadRequest
}

func (r ApiCreateQuoteContractThreadV1Request) CreateContractThreadRequest(createContractThreadRequest CreateContractThreadRequest) ApiCreateQuoteContractThreadV1Request {
	r.createContractThreadRequest = &createContractThreadRequest
	return r
}

func (r ApiCreateQuoteContractThreadV1Request) Execute() (*ContractThreadSnapshotResponse, *http.Response, error) {
	return r.ApiService.CreateQuoteContractThreadV1Execute(r)
}

/*
CreateQuoteContractThreadV1 Create Quote Contract Thread

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiCreateQuoteContractThreadV1Request
*/
func (a *QuoteContractsAPIService) CreateQuoteContractThreadV1(ctx context.Context, quoteId string) ApiCreateQuoteContractThreadV1Request {
	return ApiCreateQuoteContractThreadV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return ContractThreadSnapshotResponse
func (a *QuoteContractsAPIService) CreateQuoteContractThreadV1Execute(r ApiCreateQuoteContractThreadV1Request) (*ContractThreadSnapshotResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ContractThreadSnapshotResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.CreateQuoteContractThreadV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createContractThreadRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetQuoteContractThreadV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
}

func (r ApiGetQuoteContractThreadV1Request) Execute() (*ContractThreadSnapshotResponse, *http.Response, error) {
	return r.ApiService.GetQuoteContractThreadV1Execute(r)
}

/*
GetQuoteContractThreadV1 Get Quote Contract Thread

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiGetQuoteContractThreadV1Request
*/
func (a *QuoteContractsAPIService) GetQuoteContractThreadV1(ctx context.Context, quoteId string) ApiGetQuoteContractThreadV1Request {
	return ApiGetQuoteContractThreadV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return ContractThreadSnapshotResponse
func (a *QuoteContractsAPIService) GetQuoteContractThreadV1Execute(r ApiGetQuoteContractThreadV1Request) (*ContractThreadSnapshotResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ContractThreadSnapshotResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.GetQuoteContractThreadV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListQuoteContractQuarantineV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
}

func (r ApiListQuoteContractQuarantineV1Request) Execute() ([]ContractInboundMessageResponse, *http.Response, error) {
	return r.ApiService.ListQuoteContractQuarantineV1Execute(r)
}

/*
ListQuoteContractQuarantineV1 List Quote Contract Quarantine

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiListQuoteContractQuarantineV1Request
*/
func (a *QuoteContractsAPIService) ListQuoteContractQuarantineV1(ctx context.Context, quoteId string) ApiListQuoteContractQuarantineV1Request {
	return ApiListQuoteContractQuarantineV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return []ContractInboundMessageResponse
func (a *QuoteContractsAPIService) ListQuoteContractQuarantineV1Execute(r ApiListQuoteContractQuarantineV1Request) ([]ContractInboundMessageResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ContractInboundMessageResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.ListQuoteContractQuarantineV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/quarantine"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListQuoteContractVersionsV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
}

func (r ApiListQuoteContractVersionsV1Request) Execute() ([]ContractVersionResponse, *http.Response, error) {
	return r.ApiService.ListQuoteContractVersionsV1Execute(r)
}

/*
ListQuoteContractVersionsV1 List Quote Contract Versions

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiListQuoteContractVersionsV1Request
*/
func (a *QuoteContractsAPIService) ListQuoteContractVersionsV1(ctx context.Context, quoteId string) ApiListQuoteContractVersionsV1Request {
	return ApiListQuoteContractVersionsV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return []ContractVersionResponse
func (a *QuoteContractsAPIService) ListQuoteContractVersionsV1Execute(r ApiListQuoteContractVersionsV1Request) ([]ContractVersionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ContractVersionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.ListQuoteContractVersionsV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPromoteQuoteContractQuarantineSenderV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	messageId string
	addContractParticipantRequest *AddContractParticipantRequest
}

func (r ApiPromoteQuoteContractQuarantineSenderV1Request) AddContractParticipantRequest(addContractParticipantRequest AddContractParticipantRequest) ApiPromoteQuoteContractQuarantineSenderV1Request {
	r.addContractParticipantRequest = &addContractParticipantRequest
	return r
}

func (r ApiPromoteQuoteContractQuarantineSenderV1Request) Execute() (*ContractParticipantResponse, *http.Response, error) {
	return r.ApiService.PromoteQuoteContractQuarantineSenderV1Execute(r)
}

/*
PromoteQuoteContractQuarantineSenderV1 Promote Quote Contract Quarantine Sender

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @param messageId
 @return ApiPromoteQuoteContractQuarantineSenderV1Request
*/
func (a *QuoteContractsAPIService) PromoteQuoteContractQuarantineSenderV1(ctx context.Context, quoteId string, messageId string) ApiPromoteQuoteContractQuarantineSenderV1Request {
	return ApiPromoteQuoteContractQuarantineSenderV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
		messageId: messageId,
	}
}

// Execute executes the request
//  @return ContractParticipantResponse
func (a *QuoteContractsAPIService) PromoteQuoteContractQuarantineSenderV1Execute(r ApiPromoteQuoteContractQuarantineSenderV1Request) (*ContractParticipantResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ContractParticipantResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.PromoteQuoteContractQuarantineSenderV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/quarantine/{message_id}/promote"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"message_id"+"}", url.PathEscape(parameterValueToString(r.messageId, "messageId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.addContractParticipantRequest == nil {
		return localVarReturnValue, nil, reportError("addContractParticipantRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.addContractParticipantRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRemoveQuoteContractParticipantV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	participantId string
}

func (r ApiRemoveQuoteContractParticipantV1Request) Execute() (*RemoveContractParticipantResponse, *http.Response, error) {
	return r.ApiService.RemoveQuoteContractParticipantV1Execute(r)
}

/*
RemoveQuoteContractParticipantV1 Remove Quote Contract Participant

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @param participantId
 @return ApiRemoveQuoteContractParticipantV1Request
*/
func (a *QuoteContractsAPIService) RemoveQuoteContractParticipantV1(ctx context.Context, quoteId string, participantId string) ApiRemoveQuoteContractParticipantV1Request {
	return ApiRemoveQuoteContractParticipantV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
		participantId: participantId,
	}
}

// Execute executes the request
//  @return RemoveContractParticipantResponse
func (a *QuoteContractsAPIService) RemoveQuoteContractParticipantV1Execute(r ApiRemoveQuoteContractParticipantV1Request) (*RemoveContractParticipantResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RemoveContractParticipantResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.RemoveQuoteContractParticipantV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/participants/{participant_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"participant_id"+"}", url.PathEscape(parameterValueToString(r.participantId, "participantId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiReprocessQuoteContractQuarantineMessageV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	messageId string
}

func (r ApiReprocessQuoteContractQuarantineMessageV1Request) Execute() (*InboundEmailProcessResponse, *http.Response, error) {
	return r.ApiService.ReprocessQuoteContractQuarantineMessageV1Execute(r)
}

/*
ReprocessQuoteContractQuarantineMessageV1 Reprocess Quote Contract Quarantine Message

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @param messageId
 @return ApiReprocessQuoteContractQuarantineMessageV1Request
*/
func (a *QuoteContractsAPIService) ReprocessQuoteContractQuarantineMessageV1(ctx context.Context, quoteId string, messageId string) ApiReprocessQuoteContractQuarantineMessageV1Request {
	return ApiReprocessQuoteContractQuarantineMessageV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
		messageId: messageId,
	}
}

// Execute executes the request
//  @return InboundEmailProcessResponse
func (a *QuoteContractsAPIService) ReprocessQuoteContractQuarantineMessageV1Execute(r ApiReprocessQuoteContractQuarantineMessageV1Request) (*InboundEmailProcessResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *InboundEmailProcessResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.ReprocessQuoteContractQuarantineMessageV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/quarantine/{message_id}/reprocess"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"message_id"+"}", url.PathEscape(parameterValueToString(r.messageId, "messageId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUploadQuoteContractVersionV1Request struct {
	ctx context.Context
	ApiService *QuoteContractsAPIService
	quoteId string
	file *os.File
}

func (r ApiUploadQuoteContractVersionV1Request) File(file *os.File) ApiUploadQuoteContractVersionV1Request {
	r.file = file
	return r
}

func (r ApiUploadQuoteContractVersionV1Request) Execute() (*ContractVersionResponse, *http.Response, error) {
	return r.ApiService.UploadQuoteContractVersionV1Execute(r)
}

/*
UploadQuoteContractVersionV1 Upload Quote Contract Version

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param quoteId
 @return ApiUploadQuoteContractVersionV1Request
*/
func (a *QuoteContractsAPIService) UploadQuoteContractVersionV1(ctx context.Context, quoteId string) ApiUploadQuoteContractVersionV1Request {
	return ApiUploadQuoteContractVersionV1Request{
		ApiService: a,
		ctx: ctx,
		quoteId: quoteId,
	}
}

// Execute executes the request
//  @return ContractVersionResponse
func (a *QuoteContractsAPIService) UploadQuoteContractVersionV1Execute(r ApiUploadQuoteContractVersionV1Request) (*ContractVersionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ContractVersionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QuoteContractsAPIService.UploadQuoteContractVersionV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/quotes/{quote_id}/contract-thread/versions"
	localVarPath = strings.Replace(localVarPath, "{"+"quote_id"+"}", url.PathEscape(parameterValueToString(r.quoteId, "quoteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
