/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the SyncInvoicesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncInvoicesRequest{}

// SyncInvoicesRequest struct for SyncInvoicesRequest
type SyncInvoicesRequest struct {
	AccountId *string `json:"account_id,omitempty"`
}

// NewSyncInvoicesRequest instantiates a new SyncInvoicesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncInvoicesRequest() *SyncInvoicesRequest {
	this := SyncInvoicesRequest{}
	return &this
}

// NewSyncInvoicesRequestWithDefaults instantiates a new SyncInvoicesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncInvoicesRequestWithDefaults() *SyncInvoicesRequest {
	this := SyncInvoicesRequest{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *SyncInvoicesRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncInvoicesRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *SyncInvoicesRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *SyncInvoicesRequest) SetAccountId(v string) {
	o.AccountId = &v
}

func (o SyncInvoicesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncInvoicesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	return toSerialize, nil
}

type NullableSyncInvoicesRequest struct {
	value *SyncInvoicesRequest
	isSet bool
}

func (v NullableSyncInvoicesRequest) Get() *SyncInvoicesRequest {
	return v.value
}

func (v *NullableSyncInvoicesRequest) Set(val *SyncInvoicesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncInvoicesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncInvoicesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncInvoicesRequest(val *SyncInvoicesRequest) *NullableSyncInvoicesRequest {
	return &NullableSyncInvoicesRequest{value: val, isSet: true}
}

func (v NullableSyncInvoicesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncInvoicesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


