/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.3.0-rc4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoogleChatQuoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleChatQuoteResponse{}

// GoogleChatQuoteResponse struct for GoogleChatQuoteResponse
type GoogleChatQuoteResponse struct {
	Text string `json:"text"`
	CardsV2 []map[string]interface{} `json:"cardsV2,omitempty"`
}

type _GoogleChatQuoteResponse GoogleChatQuoteResponse

// NewGoogleChatQuoteResponse instantiates a new GoogleChatQuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleChatQuoteResponse(text string) *GoogleChatQuoteResponse {
	this := GoogleChatQuoteResponse{}
	this.Text = text
	return &this
}

// NewGoogleChatQuoteResponseWithDefaults instantiates a new GoogleChatQuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleChatQuoteResponseWithDefaults() *GoogleChatQuoteResponse {
	this := GoogleChatQuoteResponse{}
	return &this
}

// GetText returns the Text field value
func (o *GoogleChatQuoteResponse) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *GoogleChatQuoteResponse) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *GoogleChatQuoteResponse) SetText(v string) {
	o.Text = v
}

// GetCardsV2 returns the CardsV2 field value if set, zero value otherwise.
func (o *GoogleChatQuoteResponse) GetCardsV2() []map[string]interface{} {
	if o == nil || IsNil(o.CardsV2) {
		var ret []map[string]interface{}
		return ret
	}
	return o.CardsV2
}

// GetCardsV2Ok returns a tuple with the CardsV2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleChatQuoteResponse) GetCardsV2Ok() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.CardsV2) {
		return nil, false
	}
	return o.CardsV2, true
}

// HasCardsV2 returns a boolean if a field has been set.
func (o *GoogleChatQuoteResponse) HasCardsV2() bool {
	if o != nil && !IsNil(o.CardsV2) {
		return true
	}

	return false
}

// SetCardsV2 gets a reference to the given []map[string]interface{} and assigns it to the CardsV2 field.
func (o *GoogleChatQuoteResponse) SetCardsV2(v []map[string]interface{}) {
	o.CardsV2 = v
}

func (o GoogleChatQuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleChatQuoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	if !IsNil(o.CardsV2) {
		toSerialize["cardsV2"] = o.CardsV2
	}
	return toSerialize, nil
}

func (o *GoogleChatQuoteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleChatQuoteResponse := _GoogleChatQuoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoogleChatQuoteResponse)

	if err != nil {
		return err
	}

	*o = GoogleChatQuoteResponse(varGoogleChatQuoteResponse)

	return err
}

type NullableGoogleChatQuoteResponse struct {
	value *GoogleChatQuoteResponse
	isSet bool
}

func (v NullableGoogleChatQuoteResponse) Get() *GoogleChatQuoteResponse {
	return v.value
}

func (v *NullableGoogleChatQuoteResponse) Set(val *GoogleChatQuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleChatQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleChatQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleChatQuoteResponse(val *GoogleChatQuoteResponse) *NullableGoogleChatQuoteResponse {
	return &NullableGoogleChatQuoteResponse{value: val, isSet: true}
}

func (v NullableGoogleChatQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleChatQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


