/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CaseListItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaseListItemResponse{}

// CaseListItemResponse Lightweight case row for list views.
type CaseListItemResponse struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	AccountId string `json:"account_id"`
	CustomerId string `json:"customer_id"`
	ScopeHash string `json:"scope_hash"`
	CurrencyCode string `json:"currency_code"`
	BaseCurrencyCode string `json:"base_currency_code"`
	Status string `json:"status"`
	RiskTier string `json:"risk_tier"`
	AutonomyLevel int32 `json:"autonomy_level"`
	TotalOutstandingMicros int32 `json:"total_outstanding_micros"`
	TotalOutstandingBaseMicros int32 `json:"total_outstanding_base_micros"`
	TotalDisputedMicros *int32 `json:"total_disputed_micros,omitempty"`
	OldestDueDate *string `json:"oldest_due_date,omitempty"`
	LastContactAt *time.Time `json:"last_contact_at,omitempty"`
	LastPaymentAt *time.Time `json:"last_payment_at,omitempty"`
	NextActionAt *time.Time `json:"next_action_at,omitempty"`
	NextActionType *NextActionType `json:"next_action_type,omitempty"`
	NextPromiseDueAt *time.Time `json:"next_promise_due_at,omitempty"`
	DunningStage string `json:"dunning_stage"`
	CurrentStrategyStep *string `json:"current_strategy_step,omitempty"`
	StrategyId *string `json:"strategy_id,omitempty"`
	AssignedAgent *string `json:"assigned_agent,omitempty"`
	AssignedHuman *string `json:"assigned_human,omitempty"`
	CaseOwnerTeam *string `json:"case_owner_team,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	InvoiceCount *int32 `json:"invoice_count,omitempty"`
	Invoices []CaseInvoiceResponse `json:"invoices,omitempty"`
	Promises []PromiseResponse `json:"promises,omitempty"`
	Account *AccountSummary `json:"account,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _CaseListItemResponse CaseListItemResponse

// NewCaseListItemResponse instantiates a new CaseListItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaseListItemResponse(id string, tenantId string, accountId string, customerId string, scopeHash string, currencyCode string, baseCurrencyCode string, status string, riskTier string, autonomyLevel int32, totalOutstandingMicros int32, totalOutstandingBaseMicros int32, dunningStage string, createdAt time.Time, updatedAt time.Time) *CaseListItemResponse {
	this := CaseListItemResponse{}
	this.Id = id
	this.TenantId = tenantId
	this.AccountId = accountId
	this.CustomerId = customerId
	this.ScopeHash = scopeHash
	this.CurrencyCode = currencyCode
	this.BaseCurrencyCode = baseCurrencyCode
	this.Status = status
	this.RiskTier = riskTier
	this.AutonomyLevel = autonomyLevel
	this.TotalOutstandingMicros = totalOutstandingMicros
	this.TotalOutstandingBaseMicros = totalOutstandingBaseMicros
	var totalDisputedMicros int32 = 0
	this.TotalDisputedMicros = &totalDisputedMicros
	this.DunningStage = dunningStage
	var invoiceCount int32 = 0
	this.InvoiceCount = &invoiceCount
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCaseListItemResponseWithDefaults instantiates a new CaseListItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaseListItemResponseWithDefaults() *CaseListItemResponse {
	this := CaseListItemResponse{}
	var totalDisputedMicros int32 = 0
	this.TotalDisputedMicros = &totalDisputedMicros
	var invoiceCount int32 = 0
	this.InvoiceCount = &invoiceCount
	return &this
}

// GetId returns the Id field value
func (o *CaseListItemResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CaseListItemResponse) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *CaseListItemResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CaseListItemResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetAccountId returns the AccountId field value
func (o *CaseListItemResponse) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CaseListItemResponse) SetAccountId(v string) {
	o.AccountId = v
}

// GetCustomerId returns the CustomerId field value
func (o *CaseListItemResponse) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *CaseListItemResponse) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetScopeHash returns the ScopeHash field value
func (o *CaseListItemResponse) GetScopeHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeHash
}

// GetScopeHashOk returns a tuple with the ScopeHash field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetScopeHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeHash, true
}

// SetScopeHash sets field value
func (o *CaseListItemResponse) SetScopeHash(v string) {
	o.ScopeHash = v
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *CaseListItemResponse) GetCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *CaseListItemResponse) SetCurrencyCode(v string) {
	o.CurrencyCode = v
}

// GetBaseCurrencyCode returns the BaseCurrencyCode field value
func (o *CaseListItemResponse) GetBaseCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseCurrencyCode
}

// GetBaseCurrencyCodeOk returns a tuple with the BaseCurrencyCode field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetBaseCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseCurrencyCode, true
}

// SetBaseCurrencyCode sets field value
func (o *CaseListItemResponse) SetBaseCurrencyCode(v string) {
	o.BaseCurrencyCode = v
}

// GetStatus returns the Status field value
func (o *CaseListItemResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CaseListItemResponse) SetStatus(v string) {
	o.Status = v
}

// GetRiskTier returns the RiskTier field value
func (o *CaseListItemResponse) GetRiskTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RiskTier
}

// GetRiskTierOk returns a tuple with the RiskTier field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetRiskTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskTier, true
}

// SetRiskTier sets field value
func (o *CaseListItemResponse) SetRiskTier(v string) {
	o.RiskTier = v
}

// GetAutonomyLevel returns the AutonomyLevel field value
func (o *CaseListItemResponse) GetAutonomyLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AutonomyLevel
}

// GetAutonomyLevelOk returns a tuple with the AutonomyLevel field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetAutonomyLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutonomyLevel, true
}

// SetAutonomyLevel sets field value
func (o *CaseListItemResponse) SetAutonomyLevel(v int32) {
	o.AutonomyLevel = v
}

// GetTotalOutstandingMicros returns the TotalOutstandingMicros field value
func (o *CaseListItemResponse) GetTotalOutstandingMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalOutstandingMicros
}

// GetTotalOutstandingMicrosOk returns a tuple with the TotalOutstandingMicros field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetTotalOutstandingMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalOutstandingMicros, true
}

// SetTotalOutstandingMicros sets field value
func (o *CaseListItemResponse) SetTotalOutstandingMicros(v int32) {
	o.TotalOutstandingMicros = v
}

// GetTotalOutstandingBaseMicros returns the TotalOutstandingBaseMicros field value
func (o *CaseListItemResponse) GetTotalOutstandingBaseMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalOutstandingBaseMicros
}

// GetTotalOutstandingBaseMicrosOk returns a tuple with the TotalOutstandingBaseMicros field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetTotalOutstandingBaseMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalOutstandingBaseMicros, true
}

// SetTotalOutstandingBaseMicros sets field value
func (o *CaseListItemResponse) SetTotalOutstandingBaseMicros(v int32) {
	o.TotalOutstandingBaseMicros = v
}

// GetTotalDisputedMicros returns the TotalDisputedMicros field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetTotalDisputedMicros() int32 {
	if o == nil || IsNil(o.TotalDisputedMicros) {
		var ret int32
		return ret
	}
	return *o.TotalDisputedMicros
}

// GetTotalDisputedMicrosOk returns a tuple with the TotalDisputedMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetTotalDisputedMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalDisputedMicros) {
		return nil, false
	}
	return o.TotalDisputedMicros, true
}

// HasTotalDisputedMicros returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasTotalDisputedMicros() bool {
	if o != nil && !IsNil(o.TotalDisputedMicros) {
		return true
	}

	return false
}

// SetTotalDisputedMicros gets a reference to the given int32 and assigns it to the TotalDisputedMicros field.
func (o *CaseListItemResponse) SetTotalDisputedMicros(v int32) {
	o.TotalDisputedMicros = &v
}

// GetOldestDueDate returns the OldestDueDate field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetOldestDueDate() string {
	if o == nil || IsNil(o.OldestDueDate) {
		var ret string
		return ret
	}
	return *o.OldestDueDate
}

// GetOldestDueDateOk returns a tuple with the OldestDueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetOldestDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.OldestDueDate) {
		return nil, false
	}
	return o.OldestDueDate, true
}

// HasOldestDueDate returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasOldestDueDate() bool {
	if o != nil && !IsNil(o.OldestDueDate) {
		return true
	}

	return false
}

// SetOldestDueDate gets a reference to the given string and assigns it to the OldestDueDate field.
func (o *CaseListItemResponse) SetOldestDueDate(v string) {
	o.OldestDueDate = &v
}

// GetLastContactAt returns the LastContactAt field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetLastContactAt() time.Time {
	if o == nil || IsNil(o.LastContactAt) {
		var ret time.Time
		return ret
	}
	return *o.LastContactAt
}

// GetLastContactAtOk returns a tuple with the LastContactAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetLastContactAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastContactAt) {
		return nil, false
	}
	return o.LastContactAt, true
}

// HasLastContactAt returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasLastContactAt() bool {
	if o != nil && !IsNil(o.LastContactAt) {
		return true
	}

	return false
}

// SetLastContactAt gets a reference to the given time.Time and assigns it to the LastContactAt field.
func (o *CaseListItemResponse) SetLastContactAt(v time.Time) {
	o.LastContactAt = &v
}

// GetLastPaymentAt returns the LastPaymentAt field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetLastPaymentAt() time.Time {
	if o == nil || IsNil(o.LastPaymentAt) {
		var ret time.Time
		return ret
	}
	return *o.LastPaymentAt
}

// GetLastPaymentAtOk returns a tuple with the LastPaymentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetLastPaymentAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastPaymentAt) {
		return nil, false
	}
	return o.LastPaymentAt, true
}

// HasLastPaymentAt returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasLastPaymentAt() bool {
	if o != nil && !IsNil(o.LastPaymentAt) {
		return true
	}

	return false
}

// SetLastPaymentAt gets a reference to the given time.Time and assigns it to the LastPaymentAt field.
func (o *CaseListItemResponse) SetLastPaymentAt(v time.Time) {
	o.LastPaymentAt = &v
}

// GetNextActionAt returns the NextActionAt field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetNextActionAt() time.Time {
	if o == nil || IsNil(o.NextActionAt) {
		var ret time.Time
		return ret
	}
	return *o.NextActionAt
}

// GetNextActionAtOk returns a tuple with the NextActionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetNextActionAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextActionAt) {
		return nil, false
	}
	return o.NextActionAt, true
}

// HasNextActionAt returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasNextActionAt() bool {
	if o != nil && !IsNil(o.NextActionAt) {
		return true
	}

	return false
}

// SetNextActionAt gets a reference to the given time.Time and assigns it to the NextActionAt field.
func (o *CaseListItemResponse) SetNextActionAt(v time.Time) {
	o.NextActionAt = &v
}

// GetNextActionType returns the NextActionType field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetNextActionType() NextActionType {
	if o == nil || IsNil(o.NextActionType) {
		var ret NextActionType
		return ret
	}
	return *o.NextActionType
}

// GetNextActionTypeOk returns a tuple with the NextActionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetNextActionTypeOk() (*NextActionType, bool) {
	if o == nil || IsNil(o.NextActionType) {
		return nil, false
	}
	return o.NextActionType, true
}

// HasNextActionType returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasNextActionType() bool {
	if o != nil && !IsNil(o.NextActionType) {
		return true
	}

	return false
}

// SetNextActionType gets a reference to the given NextActionType and assigns it to the NextActionType field.
func (o *CaseListItemResponse) SetNextActionType(v NextActionType) {
	o.NextActionType = &v
}

// GetNextPromiseDueAt returns the NextPromiseDueAt field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetNextPromiseDueAt() time.Time {
	if o == nil || IsNil(o.NextPromiseDueAt) {
		var ret time.Time
		return ret
	}
	return *o.NextPromiseDueAt
}

// GetNextPromiseDueAtOk returns a tuple with the NextPromiseDueAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetNextPromiseDueAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextPromiseDueAt) {
		return nil, false
	}
	return o.NextPromiseDueAt, true
}

// HasNextPromiseDueAt returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasNextPromiseDueAt() bool {
	if o != nil && !IsNil(o.NextPromiseDueAt) {
		return true
	}

	return false
}

// SetNextPromiseDueAt gets a reference to the given time.Time and assigns it to the NextPromiseDueAt field.
func (o *CaseListItemResponse) SetNextPromiseDueAt(v time.Time) {
	o.NextPromiseDueAt = &v
}

// GetDunningStage returns the DunningStage field value
func (o *CaseListItemResponse) GetDunningStage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DunningStage
}

// GetDunningStageOk returns a tuple with the DunningStage field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetDunningStageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DunningStage, true
}

// SetDunningStage sets field value
func (o *CaseListItemResponse) SetDunningStage(v string) {
	o.DunningStage = v
}

// GetCurrentStrategyStep returns the CurrentStrategyStep field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetCurrentStrategyStep() string {
	if o == nil || IsNil(o.CurrentStrategyStep) {
		var ret string
		return ret
	}
	return *o.CurrentStrategyStep
}

// GetCurrentStrategyStepOk returns a tuple with the CurrentStrategyStep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetCurrentStrategyStepOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentStrategyStep) {
		return nil, false
	}
	return o.CurrentStrategyStep, true
}

// HasCurrentStrategyStep returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasCurrentStrategyStep() bool {
	if o != nil && !IsNil(o.CurrentStrategyStep) {
		return true
	}

	return false
}

// SetCurrentStrategyStep gets a reference to the given string and assigns it to the CurrentStrategyStep field.
func (o *CaseListItemResponse) SetCurrentStrategyStep(v string) {
	o.CurrentStrategyStep = &v
}

// GetStrategyId returns the StrategyId field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetStrategyId() string {
	if o == nil || IsNil(o.StrategyId) {
		var ret string
		return ret
	}
	return *o.StrategyId
}

// GetStrategyIdOk returns a tuple with the StrategyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetStrategyIdOk() (*string, bool) {
	if o == nil || IsNil(o.StrategyId) {
		return nil, false
	}
	return o.StrategyId, true
}

// HasStrategyId returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasStrategyId() bool {
	if o != nil && !IsNil(o.StrategyId) {
		return true
	}

	return false
}

// SetStrategyId gets a reference to the given string and assigns it to the StrategyId field.
func (o *CaseListItemResponse) SetStrategyId(v string) {
	o.StrategyId = &v
}

// GetAssignedAgent returns the AssignedAgent field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetAssignedAgent() string {
	if o == nil || IsNil(o.AssignedAgent) {
		var ret string
		return ret
	}
	return *o.AssignedAgent
}

// GetAssignedAgentOk returns a tuple with the AssignedAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetAssignedAgentOk() (*string, bool) {
	if o == nil || IsNil(o.AssignedAgent) {
		return nil, false
	}
	return o.AssignedAgent, true
}

// HasAssignedAgent returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasAssignedAgent() bool {
	if o != nil && !IsNil(o.AssignedAgent) {
		return true
	}

	return false
}

// SetAssignedAgent gets a reference to the given string and assigns it to the AssignedAgent field.
func (o *CaseListItemResponse) SetAssignedAgent(v string) {
	o.AssignedAgent = &v
}

// GetAssignedHuman returns the AssignedHuman field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetAssignedHuman() string {
	if o == nil || IsNil(o.AssignedHuman) {
		var ret string
		return ret
	}
	return *o.AssignedHuman
}

// GetAssignedHumanOk returns a tuple with the AssignedHuman field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetAssignedHumanOk() (*string, bool) {
	if o == nil || IsNil(o.AssignedHuman) {
		return nil, false
	}
	return o.AssignedHuman, true
}

// HasAssignedHuman returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasAssignedHuman() bool {
	if o != nil && !IsNil(o.AssignedHuman) {
		return true
	}

	return false
}

// SetAssignedHuman gets a reference to the given string and assigns it to the AssignedHuman field.
func (o *CaseListItemResponse) SetAssignedHuman(v string) {
	o.AssignedHuman = &v
}

// GetCaseOwnerTeam returns the CaseOwnerTeam field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetCaseOwnerTeam() string {
	if o == nil || IsNil(o.CaseOwnerTeam) {
		var ret string
		return ret
	}
	return *o.CaseOwnerTeam
}

// GetCaseOwnerTeamOk returns a tuple with the CaseOwnerTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetCaseOwnerTeamOk() (*string, bool) {
	if o == nil || IsNil(o.CaseOwnerTeam) {
		return nil, false
	}
	return o.CaseOwnerTeam, true
}

// HasCaseOwnerTeam returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasCaseOwnerTeam() bool {
	if o != nil && !IsNil(o.CaseOwnerTeam) {
		return true
	}

	return false
}

// SetCaseOwnerTeam gets a reference to the given string and assigns it to the CaseOwnerTeam field.
func (o *CaseListItemResponse) SetCaseOwnerTeam(v string) {
	o.CaseOwnerTeam = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CaseListItemResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetInvoiceCount returns the InvoiceCount field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetInvoiceCount() int32 {
	if o == nil || IsNil(o.InvoiceCount) {
		var ret int32
		return ret
	}
	return *o.InvoiceCount
}

// GetInvoiceCountOk returns a tuple with the InvoiceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetInvoiceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.InvoiceCount) {
		return nil, false
	}
	return o.InvoiceCount, true
}

// HasInvoiceCount returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasInvoiceCount() bool {
	if o != nil && !IsNil(o.InvoiceCount) {
		return true
	}

	return false
}

// SetInvoiceCount gets a reference to the given int32 and assigns it to the InvoiceCount field.
func (o *CaseListItemResponse) SetInvoiceCount(v int32) {
	o.InvoiceCount = &v
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetInvoices() []CaseInvoiceResponse {
	if o == nil || IsNil(o.Invoices) {
		var ret []CaseInvoiceResponse
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetInvoicesOk() ([]CaseInvoiceResponse, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []CaseInvoiceResponse and assigns it to the Invoices field.
func (o *CaseListItemResponse) SetInvoices(v []CaseInvoiceResponse) {
	o.Invoices = v
}

// GetPromises returns the Promises field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetPromises() []PromiseResponse {
	if o == nil || IsNil(o.Promises) {
		var ret []PromiseResponse
		return ret
	}
	return o.Promises
}

// GetPromisesOk returns a tuple with the Promises field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetPromisesOk() ([]PromiseResponse, bool) {
	if o == nil || IsNil(o.Promises) {
		return nil, false
	}
	return o.Promises, true
}

// HasPromises returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasPromises() bool {
	if o != nil && !IsNil(o.Promises) {
		return true
	}

	return false
}

// SetPromises gets a reference to the given []PromiseResponse and assigns it to the Promises field.
func (o *CaseListItemResponse) SetPromises(v []PromiseResponse) {
	o.Promises = v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *CaseListItemResponse) GetAccount() AccountSummary {
	if o == nil || IsNil(o.Account) {
		var ret AccountSummary
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetAccountOk() (*AccountSummary, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *CaseListItemResponse) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountSummary and assigns it to the Account field.
func (o *CaseListItemResponse) SetAccount(v AccountSummary) {
	o.Account = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CaseListItemResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CaseListItemResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CaseListItemResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CaseListItemResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CaseListItemResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CaseListItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaseListItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["account_id"] = o.AccountId
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["scope_hash"] = o.ScopeHash
	toSerialize["currency_code"] = o.CurrencyCode
	toSerialize["base_currency_code"] = o.BaseCurrencyCode
	toSerialize["status"] = o.Status
	toSerialize["risk_tier"] = o.RiskTier
	toSerialize["autonomy_level"] = o.AutonomyLevel
	toSerialize["total_outstanding_micros"] = o.TotalOutstandingMicros
	toSerialize["total_outstanding_base_micros"] = o.TotalOutstandingBaseMicros
	if !IsNil(o.TotalDisputedMicros) {
		toSerialize["total_disputed_micros"] = o.TotalDisputedMicros
	}
	if !IsNil(o.OldestDueDate) {
		toSerialize["oldest_due_date"] = o.OldestDueDate
	}
	if !IsNil(o.LastContactAt) {
		toSerialize["last_contact_at"] = o.LastContactAt
	}
	if !IsNil(o.LastPaymentAt) {
		toSerialize["last_payment_at"] = o.LastPaymentAt
	}
	if !IsNil(o.NextActionAt) {
		toSerialize["next_action_at"] = o.NextActionAt
	}
	if !IsNil(o.NextActionType) {
		toSerialize["next_action_type"] = o.NextActionType
	}
	if !IsNil(o.NextPromiseDueAt) {
		toSerialize["next_promise_due_at"] = o.NextPromiseDueAt
	}
	toSerialize["dunning_stage"] = o.DunningStage
	if !IsNil(o.CurrentStrategyStep) {
		toSerialize["current_strategy_step"] = o.CurrentStrategyStep
	}
	if !IsNil(o.StrategyId) {
		toSerialize["strategy_id"] = o.StrategyId
	}
	if !IsNil(o.AssignedAgent) {
		toSerialize["assigned_agent"] = o.AssignedAgent
	}
	if !IsNil(o.AssignedHuman) {
		toSerialize["assigned_human"] = o.AssignedHuman
	}
	if !IsNil(o.CaseOwnerTeam) {
		toSerialize["case_owner_team"] = o.CaseOwnerTeam
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.InvoiceCount) {
		toSerialize["invoice_count"] = o.InvoiceCount
	}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	if !IsNil(o.Promises) {
		toSerialize["promises"] = o.Promises
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *CaseListItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"account_id",
		"customer_id",
		"scope_hash",
		"currency_code",
		"base_currency_code",
		"status",
		"risk_tier",
		"autonomy_level",
		"total_outstanding_micros",
		"total_outstanding_base_micros",
		"dunning_stage",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCaseListItemResponse := _CaseListItemResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCaseListItemResponse)

	if err != nil {
		return err
	}

	*o = CaseListItemResponse(varCaseListItemResponse)

	return err
}

type NullableCaseListItemResponse struct {
	value *CaseListItemResponse
	isSet bool
}

func (v NullableCaseListItemResponse) Get() *CaseListItemResponse {
	return v.value
}

func (v *NullableCaseListItemResponse) Set(val *CaseListItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCaseListItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCaseListItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaseListItemResponse(val *CaseListItemResponse) *NullableCaseListItemResponse {
	return &NullableCaseListItemResponse{value: val, isSet: true}
}

func (v NullableCaseListItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaseListItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


