/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)

// TaxBehavior Tax behavior.  This enum is used to specify whether tax is included in the price or excluded from the price.
type TaxBehavior string

// List of TaxBehavior
const (
	TAXBEHAVIOR_INCLUSIVE TaxBehavior = "inclusive"
	TAXBEHAVIOR_EXCLUSIVE TaxBehavior = "exclusive"
)

// All allowed values of TaxBehavior enum
var AllowedTaxBehaviorEnumValues = []TaxBehavior{
	"inclusive",
	"exclusive",
}

func (v *TaxBehavior) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TaxBehavior(value)
	for _, existing := range AllowedTaxBehaviorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TaxBehavior", value)
}

// NewTaxBehaviorFromValue returns a pointer to a valid TaxBehavior
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTaxBehaviorFromValue(v string) (*TaxBehavior, error) {
	ev := TaxBehavior(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TaxBehavior: valid values are %v", v, AllowedTaxBehaviorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TaxBehavior) IsValid() bool {
	for _, existing := range AllowedTaxBehaviorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TaxBehavior value
func (v TaxBehavior) Ptr() *TaxBehavior {
	return &v
}

type NullableTaxBehavior struct {
	value *TaxBehavior
	isSet bool
}

func (v NullableTaxBehavior) Get() *TaxBehavior {
	return v.value
}

func (v *NullableTaxBehavior) Set(val *TaxBehavior) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxBehavior) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxBehavior) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxBehavior(val *TaxBehavior) *NullableTaxBehavior {
	return &NullableTaxBehavior{value: val, isSet: true}
}

func (v NullableTaxBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxBehavior) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

