/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncConfigRequest{}

// SyncConfigRequest struct for SyncConfigRequest
type SyncConfigRequest struct {
	CloudProvider string `json:"cloud_provider"`
	Schedule *string `json:"schedule,omitempty" validate:"regexp=^([*0-9,-\\/]+\\\\s+){4}[*0-9,-\\/]+$"`
}

type _SyncConfigRequest SyncConfigRequest

// NewSyncConfigRequest instantiates a new SyncConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncConfigRequest(cloudProvider string) *SyncConfigRequest {
	this := SyncConfigRequest{}
	this.CloudProvider = cloudProvider
	var schedule string = "0 6 * * *"
	this.Schedule = &schedule
	return &this
}

// NewSyncConfigRequestWithDefaults instantiates a new SyncConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncConfigRequestWithDefaults() *SyncConfigRequest {
	this := SyncConfigRequest{}
	var schedule string = "0 6 * * *"
	this.Schedule = &schedule
	return &this
}

// GetCloudProvider returns the CloudProvider field value
func (o *SyncConfigRequest) GetCloudProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value
// and a boolean to check if the value has been set.
func (o *SyncConfigRequest) GetCloudProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProvider, true
}

// SetCloudProvider sets field value
func (o *SyncConfigRequest) SetCloudProvider(v string) {
	o.CloudProvider = v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *SyncConfigRequest) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncConfigRequest) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *SyncConfigRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *SyncConfigRequest) SetSchedule(v string) {
	o.Schedule = &v
}

func (o SyncConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_provider"] = o.CloudProvider
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	return toSerialize, nil
}

func (o *SyncConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloud_provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncConfigRequest := _SyncConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncConfigRequest)

	if err != nil {
		return err
	}

	*o = SyncConfigRequest(varSyncConfigRequest)

	return err
}

type NullableSyncConfigRequest struct {
	value *SyncConfigRequest
	isSet bool
}

func (v NullableSyncConfigRequest) Get() *SyncConfigRequest {
	return v.value
}

func (v *NullableSyncConfigRequest) Set(val *SyncConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncConfigRequest(val *SyncConfigRequest) *NullableSyncConfigRequest {
	return &NullableSyncConfigRequest{value: val, isSet: true}
}

func (v NullableSyncConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


