/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DisputeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeListResponse{}

// DisputeListResponse struct for DisputeListResponse
type DisputeListResponse struct {
	Items []DisputeResponse `json:"items"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
}

type _DisputeListResponse DisputeListResponse

// NewDisputeListResponse instantiates a new DisputeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisputeListResponse(items []DisputeResponse, total int32, page int32, pageSize int32) *DisputeListResponse {
	this := DisputeListResponse{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	return &this
}

// NewDisputeListResponseWithDefaults instantiates a new DisputeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisputeListResponseWithDefaults() *DisputeListResponse {
	this := DisputeListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *DisputeListResponse) GetItems() []DisputeResponse {
	if o == nil {
		var ret []DisputeResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *DisputeListResponse) GetItemsOk() ([]DisputeResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *DisputeListResponse) SetItems(v []DisputeResponse) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *DisputeListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DisputeListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DisputeListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *DisputeListResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *DisputeListResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *DisputeListResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *DisputeListResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *DisputeListResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *DisputeListResponse) SetPageSize(v int32) {
	o.PageSize = v
}

func (o DisputeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisputeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	return toSerialize, nil
}

func (o *DisputeListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"page_size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisputeListResponse := _DisputeListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisputeListResponse)

	if err != nil {
		return err
	}

	*o = DisputeListResponse(varDisputeListResponse)

	return err
}

type NullableDisputeListResponse struct {
	value *DisputeListResponse
	isSet bool
}

func (v NullableDisputeListResponse) Get() *DisputeListResponse {
	return v.value
}

func (v *NullableDisputeListResponse) Set(val *DisputeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeListResponse(val *DisputeListResponse) *NullableDisputeListResponse {
	return &NullableDisputeListResponse{value: val, isSet: true}
}

func (v NullableDisputeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


