/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EscalationActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscalationActionResponse{}

// EscalationActionResponse POST /v1/arc/escalations/{escalation_id}/actions response.  Mirrors the ``escalation_actions.dispatch_action`` shape so the UI can render success / failure inline on the card without a 500.
type EscalationActionResponse struct {
	Ok bool `json:"ok"`
	Result map[string]interface{} `json:"result,omitempty"`
	Error *string `json:"error,omitempty"`
}

type _EscalationActionResponse EscalationActionResponse

// NewEscalationActionResponse instantiates a new EscalationActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscalationActionResponse(ok bool) *EscalationActionResponse {
	this := EscalationActionResponse{}
	this.Ok = ok
	return &this
}

// NewEscalationActionResponseWithDefaults instantiates a new EscalationActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscalationActionResponseWithDefaults() *EscalationActionResponse {
	this := EscalationActionResponse{}
	return &this
}

// GetOk returns the Ok field value
func (o *EscalationActionResponse) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *EscalationActionResponse) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *EscalationActionResponse) SetOk(v bool) {
	o.Ok = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *EscalationActionResponse) GetResult() map[string]interface{} {
	if o == nil || IsNil(o.Result) {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscalationActionResponse) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *EscalationActionResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *EscalationActionResponse) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *EscalationActionResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscalationActionResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *EscalationActionResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *EscalationActionResponse) SetError(v string) {
	o.Error = &v
}

func (o EscalationActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscalationActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ok"] = o.Ok
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *EscalationActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ok",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEscalationActionResponse := _EscalationActionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEscalationActionResponse)

	if err != nil {
		return err
	}

	*o = EscalationActionResponse(varEscalationActionResponse)

	return err
}

type NullableEscalationActionResponse struct {
	value *EscalationActionResponse
	isSet bool
}

func (v NullableEscalationActionResponse) Get() *EscalationActionResponse {
	return v.value
}

func (v *NullableEscalationActionResponse) Set(val *EscalationActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEscalationActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEscalationActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscalationActionResponse(val *EscalationActionResponse) *NullableEscalationActionResponse {
	return &NullableEscalationActionResponse{value: val, isSet: true}
}

func (v NullableEscalationActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscalationActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


