/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWalletRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWalletRequest{}

// CreateWalletRequest Request to create a wallet.
type CreateWalletRequest struct {
	// Tenant identifier
	TenantId string `json:"tenant_id"`
	// Credit pool identifier
	PoolId string `json:"pool_id"`
	// Owner type (ORG, TEAM, USER, etc.)
	OwnerType WalletOwnerType `json:"owner_type"`
	// Owner identifier
	OwnerId string `json:"owner_id"`
	// Parent wallet ID (for hierarchy)
	ParentWalletId *string `json:"parent_wallet_id,omitempty"`
	// Hierarchy depth (0-3)
	Depth *int32 `json:"depth,omitempty"`
	// Wallet policy
	Policy *WalletPolicy `json:"policy,omitempty"`
	// Local hard cap (micros)
	LocalHardCapMicros *int32 `json:"local_hard_cap_micros,omitempty"`
	// Local soft threshold (micros)
	LocalSoftThresholdMicros *int32 `json:"local_soft_threshold_micros,omitempty"`
}

type _CreateWalletRequest CreateWalletRequest

// NewCreateWalletRequest instantiates a new CreateWalletRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWalletRequest(tenantId string, poolId string, ownerType WalletOwnerType, ownerId string) *CreateWalletRequest {
	this := CreateWalletRequest{}
	this.TenantId = tenantId
	this.PoolId = poolId
	this.OwnerType = ownerType
	this.OwnerId = ownerId
	var depth int32 = 0
	this.Depth = &depth
	return &this
}

// NewCreateWalletRequestWithDefaults instantiates a new CreateWalletRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWalletRequestWithDefaults() *CreateWalletRequest {
	this := CreateWalletRequest{}
	var depth int32 = 0
	this.Depth = &depth
	return &this
}

// GetTenantId returns the TenantId field value
func (o *CreateWalletRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CreateWalletRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetPoolId returns the PoolId field value
func (o *CreateWalletRequest) GetPoolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolId
}

// GetPoolIdOk returns a tuple with the PoolId field value
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetPoolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolId, true
}

// SetPoolId sets field value
func (o *CreateWalletRequest) SetPoolId(v string) {
	o.PoolId = v
}

// GetOwnerType returns the OwnerType field value
func (o *CreateWalletRequest) GetOwnerType() WalletOwnerType {
	if o == nil {
		var ret WalletOwnerType
		return ret
	}

	return o.OwnerType
}

// GetOwnerTypeOk returns a tuple with the OwnerType field value
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetOwnerTypeOk() (*WalletOwnerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerType, true
}

// SetOwnerType sets field value
func (o *CreateWalletRequest) SetOwnerType(v WalletOwnerType) {
	o.OwnerType = v
}

// GetOwnerId returns the OwnerId field value
func (o *CreateWalletRequest) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *CreateWalletRequest) SetOwnerId(v string) {
	o.OwnerId = v
}

// GetParentWalletId returns the ParentWalletId field value if set, zero value otherwise.
func (o *CreateWalletRequest) GetParentWalletId() string {
	if o == nil || IsNil(o.ParentWalletId) {
		var ret string
		return ret
	}
	return *o.ParentWalletId
}

// GetParentWalletIdOk returns a tuple with the ParentWalletId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetParentWalletIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentWalletId) {
		return nil, false
	}
	return o.ParentWalletId, true
}

// HasParentWalletId returns a boolean if a field has been set.
func (o *CreateWalletRequest) HasParentWalletId() bool {
	if o != nil && !IsNil(o.ParentWalletId) {
		return true
	}

	return false
}

// SetParentWalletId gets a reference to the given string and assigns it to the ParentWalletId field.
func (o *CreateWalletRequest) SetParentWalletId(v string) {
	o.ParentWalletId = &v
}

// GetDepth returns the Depth field value if set, zero value otherwise.
func (o *CreateWalletRequest) GetDepth() int32 {
	if o == nil || IsNil(o.Depth) {
		var ret int32
		return ret
	}
	return *o.Depth
}

// GetDepthOk returns a tuple with the Depth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.Depth) {
		return nil, false
	}
	return o.Depth, true
}

// HasDepth returns a boolean if a field has been set.
func (o *CreateWalletRequest) HasDepth() bool {
	if o != nil && !IsNil(o.Depth) {
		return true
	}

	return false
}

// SetDepth gets a reference to the given int32 and assigns it to the Depth field.
func (o *CreateWalletRequest) SetDepth(v int32) {
	o.Depth = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *CreateWalletRequest) GetPolicy() WalletPolicy {
	if o == nil || IsNil(o.Policy) {
		var ret WalletPolicy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetPolicyOk() (*WalletPolicy, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *CreateWalletRequest) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given WalletPolicy and assigns it to the Policy field.
func (o *CreateWalletRequest) SetPolicy(v WalletPolicy) {
	o.Policy = &v
}

// GetLocalHardCapMicros returns the LocalHardCapMicros field value if set, zero value otherwise.
func (o *CreateWalletRequest) GetLocalHardCapMicros() int32 {
	if o == nil || IsNil(o.LocalHardCapMicros) {
		var ret int32
		return ret
	}
	return *o.LocalHardCapMicros
}

// GetLocalHardCapMicrosOk returns a tuple with the LocalHardCapMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetLocalHardCapMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.LocalHardCapMicros) {
		return nil, false
	}
	return o.LocalHardCapMicros, true
}

// HasLocalHardCapMicros returns a boolean if a field has been set.
func (o *CreateWalletRequest) HasLocalHardCapMicros() bool {
	if o != nil && !IsNil(o.LocalHardCapMicros) {
		return true
	}

	return false
}

// SetLocalHardCapMicros gets a reference to the given int32 and assigns it to the LocalHardCapMicros field.
func (o *CreateWalletRequest) SetLocalHardCapMicros(v int32) {
	o.LocalHardCapMicros = &v
}

// GetLocalSoftThresholdMicros returns the LocalSoftThresholdMicros field value if set, zero value otherwise.
func (o *CreateWalletRequest) GetLocalSoftThresholdMicros() int32 {
	if o == nil || IsNil(o.LocalSoftThresholdMicros) {
		var ret int32
		return ret
	}
	return *o.LocalSoftThresholdMicros
}

// GetLocalSoftThresholdMicrosOk returns a tuple with the LocalSoftThresholdMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletRequest) GetLocalSoftThresholdMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.LocalSoftThresholdMicros) {
		return nil, false
	}
	return o.LocalSoftThresholdMicros, true
}

// HasLocalSoftThresholdMicros returns a boolean if a field has been set.
func (o *CreateWalletRequest) HasLocalSoftThresholdMicros() bool {
	if o != nil && !IsNil(o.LocalSoftThresholdMicros) {
		return true
	}

	return false
}

// SetLocalSoftThresholdMicros gets a reference to the given int32 and assigns it to the LocalSoftThresholdMicros field.
func (o *CreateWalletRequest) SetLocalSoftThresholdMicros(v int32) {
	o.LocalSoftThresholdMicros = &v
}

func (o CreateWalletRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWalletRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["pool_id"] = o.PoolId
	toSerialize["owner_type"] = o.OwnerType
	toSerialize["owner_id"] = o.OwnerId
	if !IsNil(o.ParentWalletId) {
		toSerialize["parent_wallet_id"] = o.ParentWalletId
	}
	if !IsNil(o.Depth) {
		toSerialize["depth"] = o.Depth
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.LocalHardCapMicros) {
		toSerialize["local_hard_cap_micros"] = o.LocalHardCapMicros
	}
	if !IsNil(o.LocalSoftThresholdMicros) {
		toSerialize["local_soft_threshold_micros"] = o.LocalSoftThresholdMicros
	}
	return toSerialize, nil
}

func (o *CreateWalletRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"pool_id",
		"owner_type",
		"owner_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWalletRequest := _CreateWalletRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWalletRequest)

	if err != nil {
		return err
	}

	*o = CreateWalletRequest(varCreateWalletRequest)

	return err
}

type NullableCreateWalletRequest struct {
	value *CreateWalletRequest
	isSet bool
}

func (v NullableCreateWalletRequest) Get() *CreateWalletRequest {
	return v.value
}

func (v *NullableCreateWalletRequest) Set(val *CreateWalletRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWalletRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWalletRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWalletRequest(val *CreateWalletRequest) *NullableCreateWalletRequest {
	return &NullableCreateWalletRequest{value: val, isSet: true}
}

func (v NullableCreateWalletRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWalletRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


