/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EscalationActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EscalationActionRequest{}

// EscalationActionRequest POST /v1/arc/escalations/{escalation_id}/actions (Spec B Task 9 / I3).  Operator-clickable card actions dispatched from the EscalationCard. ``action_type`` must be one of the values in :class:`app.models.enums.EscalationActionType`; ``payload`` is the per-action argument bag (validated by the dispatcher).  SECURITY: ``tenant_id`` MUST come from the auth context (``get_tenant_id`` dep) — never from the request body.
type EscalationActionRequest struct {
	ActionType string `json:"action_type"`
	Payload map[string]interface{} `json:"payload,omitempty"`
}

type _EscalationActionRequest EscalationActionRequest

// NewEscalationActionRequest instantiates a new EscalationActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEscalationActionRequest(actionType string) *EscalationActionRequest {
	this := EscalationActionRequest{}
	this.ActionType = actionType
	return &this
}

// NewEscalationActionRequestWithDefaults instantiates a new EscalationActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEscalationActionRequestWithDefaults() *EscalationActionRequest {
	this := EscalationActionRequest{}
	return &this
}

// GetActionType returns the ActionType field value
func (o *EscalationActionRequest) GetActionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionType
}

// GetActionTypeOk returns a tuple with the ActionType field value
// and a boolean to check if the value has been set.
func (o *EscalationActionRequest) GetActionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionType, true
}

// SetActionType sets field value
func (o *EscalationActionRequest) SetActionType(v string) {
	o.ActionType = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *EscalationActionRequest) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EscalationActionRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *EscalationActionRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *EscalationActionRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o EscalationActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EscalationActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action_type"] = o.ActionType
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

func (o *EscalationActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEscalationActionRequest := _EscalationActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEscalationActionRequest)

	if err != nil {
		return err
	}

	*o = EscalationActionRequest(varEscalationActionRequest)

	return err
}

type NullableEscalationActionRequest struct {
	value *EscalationActionRequest
	isSet bool
}

func (v NullableEscalationActionRequest) Get() *EscalationActionRequest {
	return v.value
}

func (v *NullableEscalationActionRequest) Set(val *EscalationActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEscalationActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEscalationActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEscalationActionRequest(val *EscalationActionRequest) *NullableEscalationActionRequest {
	return &NullableEscalationActionRequest{value: val, isSet: true}
}

func (v NullableEscalationActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEscalationActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


