/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InvoicePendingLineCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicePendingLineCreateResponse{}

// InvoicePendingLineCreateResponse InvoicePendingLineCreateResponse represents the response from the create pending line endpoint.
type InvoicePendingLineCreateResponse struct {
	// The lines that were created.
	Lines []InvoiceLine `json:"lines"`
	// The invoice containing the created lines.
	Invoice Invoice `json:"invoice"`
	// Whether the invoice was newly created.
	IsInvoiceNew bool `json:"isInvoiceNew"`
}

type _InvoicePendingLineCreateResponse InvoicePendingLineCreateResponse

// NewInvoicePendingLineCreateResponse instantiates a new InvoicePendingLineCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicePendingLineCreateResponse(lines []InvoiceLine, invoice Invoice, isInvoiceNew bool) *InvoicePendingLineCreateResponse {
	this := InvoicePendingLineCreateResponse{}
	this.Lines = lines
	this.Invoice = invoice
	this.IsInvoiceNew = isInvoiceNew
	return &this
}

// NewInvoicePendingLineCreateResponseWithDefaults instantiates a new InvoicePendingLineCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicePendingLineCreateResponseWithDefaults() *InvoicePendingLineCreateResponse {
	this := InvoicePendingLineCreateResponse{}
	return &this
}

// GetLines returns the Lines field value
func (o *InvoicePendingLineCreateResponse) GetLines() []InvoiceLine {
	if o == nil {
		var ret []InvoiceLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *InvoicePendingLineCreateResponse) GetLinesOk() ([]InvoiceLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *InvoicePendingLineCreateResponse) SetLines(v []InvoiceLine) {
	o.Lines = v
}

// GetInvoice returns the Invoice field value
func (o *InvoicePendingLineCreateResponse) GetInvoice() Invoice {
	if o == nil {
		var ret Invoice
		return ret
	}

	return o.Invoice
}

// GetInvoiceOk returns a tuple with the Invoice field value
// and a boolean to check if the value has been set.
func (o *InvoicePendingLineCreateResponse) GetInvoiceOk() (*Invoice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invoice, true
}

// SetInvoice sets field value
func (o *InvoicePendingLineCreateResponse) SetInvoice(v Invoice) {
	o.Invoice = v
}

// GetIsInvoiceNew returns the IsInvoiceNew field value
func (o *InvoicePendingLineCreateResponse) GetIsInvoiceNew() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsInvoiceNew
}

// GetIsInvoiceNewOk returns a tuple with the IsInvoiceNew field value
// and a boolean to check if the value has been set.
func (o *InvoicePendingLineCreateResponse) GetIsInvoiceNewOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsInvoiceNew, true
}

// SetIsInvoiceNew sets field value
func (o *InvoicePendingLineCreateResponse) SetIsInvoiceNew(v bool) {
	o.IsInvoiceNew = v
}

func (o InvoicePendingLineCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicePendingLineCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lines"] = o.Lines
	toSerialize["invoice"] = o.Invoice
	toSerialize["isInvoiceNew"] = o.IsInvoiceNew
	return toSerialize, nil
}

func (o *InvoicePendingLineCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lines",
		"invoice",
		"isInvoiceNew",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvoicePendingLineCreateResponse := _InvoicePendingLineCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvoicePendingLineCreateResponse)

	if err != nil {
		return err
	}

	*o = InvoicePendingLineCreateResponse(varInvoicePendingLineCreateResponse)

	return err
}

type NullableInvoicePendingLineCreateResponse struct {
	value *InvoicePendingLineCreateResponse
	isSet bool
}

func (v NullableInvoicePendingLineCreateResponse) Get() *InvoicePendingLineCreateResponse {
	return v.value
}

func (v *NullableInvoicePendingLineCreateResponse) Set(val *InvoicePendingLineCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicePendingLineCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicePendingLineCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicePendingLineCreateResponse(val *InvoicePendingLineCreateResponse) *NullableInvoicePendingLineCreateResponse {
	return &NullableInvoicePendingLineCreateResponse{value: val, isSet: true}
}

func (v NullableInvoicePendingLineCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicePendingLineCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


