/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportPromiseItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportPromiseItem{}

// ImportPromiseItem One promise-to-pay row for bulk import.  ``external_ptp_id`` is the upstream identifier (e.g. Growfin PTP number) and the upsert key.  ``case_id`` must point at a non-terminal case.
type ImportPromiseItem struct {
	ExternalPtpId string `json:"external_ptp_id"`
	CaseId string `json:"case_id"`
	ContactId *string `json:"contact_id,omitempty"`
	InvoiceId *string `json:"invoice_id,omitempty"`
	PromisedAmountMicros int32 `json:"promised_amount_micros"`
	FulfilledAmountMicros *int32 `json:"fulfilled_amount_micros,omitempty"`
	CurrencyCode *string `json:"currency_code,omitempty"`
	PromisedDate string `json:"promised_date"`
	Status *string `json:"status,omitempty"`
	CapturedFromChannel *string `json:"captured_from_channel,omitempty"`
	CapturedBy *string `json:"captured_by,omitempty"`
	Confidence *float32 `json:"confidence,omitempty"`
	PtpNo *string `json:"ptp_no,omitempty"`
	BalanceAmountMicros *int32 `json:"balance_amount_micros,omitempty"`
	AmountBaseCurrencyMicros *int32 `json:"amount_base_currency_micros,omitempty"`
	BalanceAmountBaseCurrencyMicros *int32 `json:"balance_amount_base_currency_micros,omitempty"`
	SlippageCount *int32 `json:"slippage_count,omitempty"`
	SourceApp *string `json:"source_app,omitempty"`
	PtpType *string `json:"ptp_type,omitempty"`
}

type _ImportPromiseItem ImportPromiseItem

// NewImportPromiseItem instantiates a new ImportPromiseItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportPromiseItem(externalPtpId string, caseId string, promisedAmountMicros int32, promisedDate string) *ImportPromiseItem {
	this := ImportPromiseItem{}
	this.ExternalPtpId = externalPtpId
	this.CaseId = caseId
	this.PromisedAmountMicros = promisedAmountMicros
	var fulfilledAmountMicros int32 = 0
	this.FulfilledAmountMicros = &fulfilledAmountMicros
	var currencyCode string = "USD"
	this.CurrencyCode = &currencyCode
	this.PromisedDate = promisedDate
	var status string = "open"
	this.Status = &status
	var capturedFromChannel string = "email"
	this.CapturedFromChannel = &capturedFromChannel
	var capturedBy string = "human"
	this.CapturedBy = &capturedBy
	var slippageCount int32 = 0
	this.SlippageCount = &slippageCount
	return &this
}

// NewImportPromiseItemWithDefaults instantiates a new ImportPromiseItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportPromiseItemWithDefaults() *ImportPromiseItem {
	this := ImportPromiseItem{}
	var fulfilledAmountMicros int32 = 0
	this.FulfilledAmountMicros = &fulfilledAmountMicros
	var currencyCode string = "USD"
	this.CurrencyCode = &currencyCode
	var status string = "open"
	this.Status = &status
	var capturedFromChannel string = "email"
	this.CapturedFromChannel = &capturedFromChannel
	var capturedBy string = "human"
	this.CapturedBy = &capturedBy
	var slippageCount int32 = 0
	this.SlippageCount = &slippageCount
	return &this
}

// GetExternalPtpId returns the ExternalPtpId field value
func (o *ImportPromiseItem) GetExternalPtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalPtpId
}

// GetExternalPtpIdOk returns a tuple with the ExternalPtpId field value
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetExternalPtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalPtpId, true
}

// SetExternalPtpId sets field value
func (o *ImportPromiseItem) SetExternalPtpId(v string) {
	o.ExternalPtpId = v
}

// GetCaseId returns the CaseId field value
func (o *ImportPromiseItem) GetCaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CaseId
}

// GetCaseIdOk returns a tuple with the CaseId field value
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetCaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaseId, true
}

// SetCaseId sets field value
func (o *ImportPromiseItem) SetCaseId(v string) {
	o.CaseId = v
}

// GetContactId returns the ContactId field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetContactId() string {
	if o == nil || IsNil(o.ContactId) {
		var ret string
		return ret
	}
	return *o.ContactId
}

// GetContactIdOk returns a tuple with the ContactId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetContactIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContactId) {
		return nil, false
	}
	return o.ContactId, true
}

// HasContactId returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasContactId() bool {
	if o != nil && !IsNil(o.ContactId) {
		return true
	}

	return false
}

// SetContactId gets a reference to the given string and assigns it to the ContactId field.
func (o *ImportPromiseItem) SetContactId(v string) {
	o.ContactId = &v
}

// GetInvoiceId returns the InvoiceId field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetInvoiceId() string {
	if o == nil || IsNil(o.InvoiceId) {
		var ret string
		return ret
	}
	return *o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetInvoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceId) {
		return nil, false
	}
	return o.InvoiceId, true
}

// HasInvoiceId returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasInvoiceId() bool {
	if o != nil && !IsNil(o.InvoiceId) {
		return true
	}

	return false
}

// SetInvoiceId gets a reference to the given string and assigns it to the InvoiceId field.
func (o *ImportPromiseItem) SetInvoiceId(v string) {
	o.InvoiceId = &v
}

// GetPromisedAmountMicros returns the PromisedAmountMicros field value
func (o *ImportPromiseItem) GetPromisedAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PromisedAmountMicros
}

// GetPromisedAmountMicrosOk returns a tuple with the PromisedAmountMicros field value
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetPromisedAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromisedAmountMicros, true
}

// SetPromisedAmountMicros sets field value
func (o *ImportPromiseItem) SetPromisedAmountMicros(v int32) {
	o.PromisedAmountMicros = v
}

// GetFulfilledAmountMicros returns the FulfilledAmountMicros field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetFulfilledAmountMicros() int32 {
	if o == nil || IsNil(o.FulfilledAmountMicros) {
		var ret int32
		return ret
	}
	return *o.FulfilledAmountMicros
}

// GetFulfilledAmountMicrosOk returns a tuple with the FulfilledAmountMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetFulfilledAmountMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.FulfilledAmountMicros) {
		return nil, false
	}
	return o.FulfilledAmountMicros, true
}

// HasFulfilledAmountMicros returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasFulfilledAmountMicros() bool {
	if o != nil && !IsNil(o.FulfilledAmountMicros) {
		return true
	}

	return false
}

// SetFulfilledAmountMicros gets a reference to the given int32 and assigns it to the FulfilledAmountMicros field.
func (o *ImportPromiseItem) SetFulfilledAmountMicros(v int32) {
	o.FulfilledAmountMicros = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *ImportPromiseItem) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetPromisedDate returns the PromisedDate field value
func (o *ImportPromiseItem) GetPromisedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PromisedDate
}

// GetPromisedDateOk returns a tuple with the PromisedDate field value
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetPromisedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromisedDate, true
}

// SetPromisedDate sets field value
func (o *ImportPromiseItem) SetPromisedDate(v string) {
	o.PromisedDate = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ImportPromiseItem) SetStatus(v string) {
	o.Status = &v
}

// GetCapturedFromChannel returns the CapturedFromChannel field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetCapturedFromChannel() string {
	if o == nil || IsNil(o.CapturedFromChannel) {
		var ret string
		return ret
	}
	return *o.CapturedFromChannel
}

// GetCapturedFromChannelOk returns a tuple with the CapturedFromChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetCapturedFromChannelOk() (*string, bool) {
	if o == nil || IsNil(o.CapturedFromChannel) {
		return nil, false
	}
	return o.CapturedFromChannel, true
}

// HasCapturedFromChannel returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasCapturedFromChannel() bool {
	if o != nil && !IsNil(o.CapturedFromChannel) {
		return true
	}

	return false
}

// SetCapturedFromChannel gets a reference to the given string and assigns it to the CapturedFromChannel field.
func (o *ImportPromiseItem) SetCapturedFromChannel(v string) {
	o.CapturedFromChannel = &v
}

// GetCapturedBy returns the CapturedBy field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetCapturedBy() string {
	if o == nil || IsNil(o.CapturedBy) {
		var ret string
		return ret
	}
	return *o.CapturedBy
}

// GetCapturedByOk returns a tuple with the CapturedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetCapturedByOk() (*string, bool) {
	if o == nil || IsNil(o.CapturedBy) {
		return nil, false
	}
	return o.CapturedBy, true
}

// HasCapturedBy returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasCapturedBy() bool {
	if o != nil && !IsNil(o.CapturedBy) {
		return true
	}

	return false
}

// SetCapturedBy gets a reference to the given string and assigns it to the CapturedBy field.
func (o *ImportPromiseItem) SetCapturedBy(v string) {
	o.CapturedBy = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *ImportPromiseItem) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetPtpNo returns the PtpNo field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetPtpNo() string {
	if o == nil || IsNil(o.PtpNo) {
		var ret string
		return ret
	}
	return *o.PtpNo
}

// GetPtpNoOk returns a tuple with the PtpNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetPtpNoOk() (*string, bool) {
	if o == nil || IsNil(o.PtpNo) {
		return nil, false
	}
	return o.PtpNo, true
}

// HasPtpNo returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasPtpNo() bool {
	if o != nil && !IsNil(o.PtpNo) {
		return true
	}

	return false
}

// SetPtpNo gets a reference to the given string and assigns it to the PtpNo field.
func (o *ImportPromiseItem) SetPtpNo(v string) {
	o.PtpNo = &v
}

// GetBalanceAmountMicros returns the BalanceAmountMicros field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetBalanceAmountMicros() int32 {
	if o == nil || IsNil(o.BalanceAmountMicros) {
		var ret int32
		return ret
	}
	return *o.BalanceAmountMicros
}

// GetBalanceAmountMicrosOk returns a tuple with the BalanceAmountMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetBalanceAmountMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.BalanceAmountMicros) {
		return nil, false
	}
	return o.BalanceAmountMicros, true
}

// HasBalanceAmountMicros returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasBalanceAmountMicros() bool {
	if o != nil && !IsNil(o.BalanceAmountMicros) {
		return true
	}

	return false
}

// SetBalanceAmountMicros gets a reference to the given int32 and assigns it to the BalanceAmountMicros field.
func (o *ImportPromiseItem) SetBalanceAmountMicros(v int32) {
	o.BalanceAmountMicros = &v
}

// GetAmountBaseCurrencyMicros returns the AmountBaseCurrencyMicros field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetAmountBaseCurrencyMicros() int32 {
	if o == nil || IsNil(o.AmountBaseCurrencyMicros) {
		var ret int32
		return ret
	}
	return *o.AmountBaseCurrencyMicros
}

// GetAmountBaseCurrencyMicrosOk returns a tuple with the AmountBaseCurrencyMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetAmountBaseCurrencyMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountBaseCurrencyMicros) {
		return nil, false
	}
	return o.AmountBaseCurrencyMicros, true
}

// HasAmountBaseCurrencyMicros returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasAmountBaseCurrencyMicros() bool {
	if o != nil && !IsNil(o.AmountBaseCurrencyMicros) {
		return true
	}

	return false
}

// SetAmountBaseCurrencyMicros gets a reference to the given int32 and assigns it to the AmountBaseCurrencyMicros field.
func (o *ImportPromiseItem) SetAmountBaseCurrencyMicros(v int32) {
	o.AmountBaseCurrencyMicros = &v
}

// GetBalanceAmountBaseCurrencyMicros returns the BalanceAmountBaseCurrencyMicros field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetBalanceAmountBaseCurrencyMicros() int32 {
	if o == nil || IsNil(o.BalanceAmountBaseCurrencyMicros) {
		var ret int32
		return ret
	}
	return *o.BalanceAmountBaseCurrencyMicros
}

// GetBalanceAmountBaseCurrencyMicrosOk returns a tuple with the BalanceAmountBaseCurrencyMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetBalanceAmountBaseCurrencyMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.BalanceAmountBaseCurrencyMicros) {
		return nil, false
	}
	return o.BalanceAmountBaseCurrencyMicros, true
}

// HasBalanceAmountBaseCurrencyMicros returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasBalanceAmountBaseCurrencyMicros() bool {
	if o != nil && !IsNil(o.BalanceAmountBaseCurrencyMicros) {
		return true
	}

	return false
}

// SetBalanceAmountBaseCurrencyMicros gets a reference to the given int32 and assigns it to the BalanceAmountBaseCurrencyMicros field.
func (o *ImportPromiseItem) SetBalanceAmountBaseCurrencyMicros(v int32) {
	o.BalanceAmountBaseCurrencyMicros = &v
}

// GetSlippageCount returns the SlippageCount field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetSlippageCount() int32 {
	if o == nil || IsNil(o.SlippageCount) {
		var ret int32
		return ret
	}
	return *o.SlippageCount
}

// GetSlippageCountOk returns a tuple with the SlippageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetSlippageCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SlippageCount) {
		return nil, false
	}
	return o.SlippageCount, true
}

// HasSlippageCount returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasSlippageCount() bool {
	if o != nil && !IsNil(o.SlippageCount) {
		return true
	}

	return false
}

// SetSlippageCount gets a reference to the given int32 and assigns it to the SlippageCount field.
func (o *ImportPromiseItem) SetSlippageCount(v int32) {
	o.SlippageCount = &v
}

// GetSourceApp returns the SourceApp field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetSourceApp() string {
	if o == nil || IsNil(o.SourceApp) {
		var ret string
		return ret
	}
	return *o.SourceApp
}

// GetSourceAppOk returns a tuple with the SourceApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetSourceAppOk() (*string, bool) {
	if o == nil || IsNil(o.SourceApp) {
		return nil, false
	}
	return o.SourceApp, true
}

// HasSourceApp returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasSourceApp() bool {
	if o != nil && !IsNil(o.SourceApp) {
		return true
	}

	return false
}

// SetSourceApp gets a reference to the given string and assigns it to the SourceApp field.
func (o *ImportPromiseItem) SetSourceApp(v string) {
	o.SourceApp = &v
}

// GetPtpType returns the PtpType field value if set, zero value otherwise.
func (o *ImportPromiseItem) GetPtpType() string {
	if o == nil || IsNil(o.PtpType) {
		var ret string
		return ret
	}
	return *o.PtpType
}

// GetPtpTypeOk returns a tuple with the PtpType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportPromiseItem) GetPtpTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PtpType) {
		return nil, false
	}
	return o.PtpType, true
}

// HasPtpType returns a boolean if a field has been set.
func (o *ImportPromiseItem) HasPtpType() bool {
	if o != nil && !IsNil(o.PtpType) {
		return true
	}

	return false
}

// SetPtpType gets a reference to the given string and assigns it to the PtpType field.
func (o *ImportPromiseItem) SetPtpType(v string) {
	o.PtpType = &v
}

func (o ImportPromiseItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportPromiseItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_ptp_id"] = o.ExternalPtpId
	toSerialize["case_id"] = o.CaseId
	if !IsNil(o.ContactId) {
		toSerialize["contact_id"] = o.ContactId
	}
	if !IsNil(o.InvoiceId) {
		toSerialize["invoice_id"] = o.InvoiceId
	}
	toSerialize["promised_amount_micros"] = o.PromisedAmountMicros
	if !IsNil(o.FulfilledAmountMicros) {
		toSerialize["fulfilled_amount_micros"] = o.FulfilledAmountMicros
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currency_code"] = o.CurrencyCode
	}
	toSerialize["promised_date"] = o.PromisedDate
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CapturedFromChannel) {
		toSerialize["captured_from_channel"] = o.CapturedFromChannel
	}
	if !IsNil(o.CapturedBy) {
		toSerialize["captured_by"] = o.CapturedBy
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.PtpNo) {
		toSerialize["ptp_no"] = o.PtpNo
	}
	if !IsNil(o.BalanceAmountMicros) {
		toSerialize["balance_amount_micros"] = o.BalanceAmountMicros
	}
	if !IsNil(o.AmountBaseCurrencyMicros) {
		toSerialize["amount_base_currency_micros"] = o.AmountBaseCurrencyMicros
	}
	if !IsNil(o.BalanceAmountBaseCurrencyMicros) {
		toSerialize["balance_amount_base_currency_micros"] = o.BalanceAmountBaseCurrencyMicros
	}
	if !IsNil(o.SlippageCount) {
		toSerialize["slippage_count"] = o.SlippageCount
	}
	if !IsNil(o.SourceApp) {
		toSerialize["source_app"] = o.SourceApp
	}
	if !IsNil(o.PtpType) {
		toSerialize["ptp_type"] = o.PtpType
	}
	return toSerialize, nil
}

func (o *ImportPromiseItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_ptp_id",
		"case_id",
		"promised_amount_micros",
		"promised_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportPromiseItem := _ImportPromiseItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportPromiseItem)

	if err != nil {
		return err
	}

	*o = ImportPromiseItem(varImportPromiseItem)

	return err
}

type NullableImportPromiseItem struct {
	value *ImportPromiseItem
	isSet bool
}

func (v NullableImportPromiseItem) Get() *ImportPromiseItem {
	return v.value
}

func (v *NullableImportPromiseItem) Set(val *ImportPromiseItem) {
	v.value = val
	v.isSet = true
}

func (v NullableImportPromiseItem) IsSet() bool {
	return v.isSet
}

func (v *NullableImportPromiseItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportPromiseItem(val *ImportPromiseItem) *NullableImportPromiseItem {
	return &NullableImportPromiseItem{value: val, isSet: true}
}

func (v NullableImportPromiseItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportPromiseItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


