/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BomComponentIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BomComponentIn{}

// BomComponentIn struct for BomComponentIn
type BomComponentIn struct {
	// 'llm_call', 'embedding', etc.
	ComponentType *string `json:"component_type,omitempty"`
	Provider string `json:"provider"`
	Model string `json:"model"`
	MetricType string `json:"metric_type"`
	// Expected units per billing event
	ExpectedQuantity float32 `json:"expected_quantity"`
	// Expected cost_event spans per billing event
	ExpectedSpanCount *int32 `json:"expected_span_count,omitempty"`
	// Override from rate_catalog if provided
	UnitCost *float32 `json:"unit_cost,omitempty"`
	Currency *string `json:"currency,omitempty"`
	SortOrder *int32 `json:"sort_order,omitempty"`
	Notes *string `json:"notes,omitempty"`
}

type _BomComponentIn BomComponentIn

// NewBomComponentIn instantiates a new BomComponentIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBomComponentIn(provider string, model string, metricType string, expectedQuantity float32) *BomComponentIn {
	this := BomComponentIn{}
	var componentType string = "llm_call"
	this.ComponentType = &componentType
	this.Provider = provider
	this.Model = model
	this.MetricType = metricType
	this.ExpectedQuantity = expectedQuantity
	var expectedSpanCount int32 = 1
	this.ExpectedSpanCount = &expectedSpanCount
	var currency string = "USD"
	this.Currency = &currency
	var sortOrder int32 = 0
	this.SortOrder = &sortOrder
	return &this
}

// NewBomComponentInWithDefaults instantiates a new BomComponentIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBomComponentInWithDefaults() *BomComponentIn {
	this := BomComponentIn{}
	var componentType string = "llm_call"
	this.ComponentType = &componentType
	var expectedSpanCount int32 = 1
	this.ExpectedSpanCount = &expectedSpanCount
	var currency string = "USD"
	this.Currency = &currency
	var sortOrder int32 = 0
	this.SortOrder = &sortOrder
	return &this
}

// GetComponentType returns the ComponentType field value if set, zero value otherwise.
func (o *BomComponentIn) GetComponentType() string {
	if o == nil || IsNil(o.ComponentType) {
		var ret string
		return ret
	}
	return *o.ComponentType
}

// GetComponentTypeOk returns a tuple with the ComponentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetComponentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentType) {
		return nil, false
	}
	return o.ComponentType, true
}

// HasComponentType returns a boolean if a field has been set.
func (o *BomComponentIn) HasComponentType() bool {
	if o != nil && !IsNil(o.ComponentType) {
		return true
	}

	return false
}

// SetComponentType gets a reference to the given string and assigns it to the ComponentType field.
func (o *BomComponentIn) SetComponentType(v string) {
	o.ComponentType = &v
}

// GetProvider returns the Provider field value
func (o *BomComponentIn) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *BomComponentIn) SetProvider(v string) {
	o.Provider = v
}

// GetModel returns the Model field value
func (o *BomComponentIn) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *BomComponentIn) SetModel(v string) {
	o.Model = v
}

// GetMetricType returns the MetricType field value
func (o *BomComponentIn) GetMetricType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetricType
}

// GetMetricTypeOk returns a tuple with the MetricType field value
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetMetricTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetricType, true
}

// SetMetricType sets field value
func (o *BomComponentIn) SetMetricType(v string) {
	o.MetricType = v
}

// GetExpectedQuantity returns the ExpectedQuantity field value
func (o *BomComponentIn) GetExpectedQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExpectedQuantity
}

// GetExpectedQuantityOk returns a tuple with the ExpectedQuantity field value
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetExpectedQuantityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedQuantity, true
}

// SetExpectedQuantity sets field value
func (o *BomComponentIn) SetExpectedQuantity(v float32) {
	o.ExpectedQuantity = v
}

// GetExpectedSpanCount returns the ExpectedSpanCount field value if set, zero value otherwise.
func (o *BomComponentIn) GetExpectedSpanCount() int32 {
	if o == nil || IsNil(o.ExpectedSpanCount) {
		var ret int32
		return ret
	}
	return *o.ExpectedSpanCount
}

// GetExpectedSpanCountOk returns a tuple with the ExpectedSpanCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetExpectedSpanCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpectedSpanCount) {
		return nil, false
	}
	return o.ExpectedSpanCount, true
}

// HasExpectedSpanCount returns a boolean if a field has been set.
func (o *BomComponentIn) HasExpectedSpanCount() bool {
	if o != nil && !IsNil(o.ExpectedSpanCount) {
		return true
	}

	return false
}

// SetExpectedSpanCount gets a reference to the given int32 and assigns it to the ExpectedSpanCount field.
func (o *BomComponentIn) SetExpectedSpanCount(v int32) {
	o.ExpectedSpanCount = &v
}

// GetUnitCost returns the UnitCost field value if set, zero value otherwise.
func (o *BomComponentIn) GetUnitCost() float32 {
	if o == nil || IsNil(o.UnitCost) {
		var ret float32
		return ret
	}
	return *o.UnitCost
}

// GetUnitCostOk returns a tuple with the UnitCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetUnitCostOk() (*float32, bool) {
	if o == nil || IsNil(o.UnitCost) {
		return nil, false
	}
	return o.UnitCost, true
}

// HasUnitCost returns a boolean if a field has been set.
func (o *BomComponentIn) HasUnitCost() bool {
	if o != nil && !IsNil(o.UnitCost) {
		return true
	}

	return false
}

// SetUnitCost gets a reference to the given float32 and assigns it to the UnitCost field.
func (o *BomComponentIn) SetUnitCost(v float32) {
	o.UnitCost = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *BomComponentIn) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *BomComponentIn) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *BomComponentIn) SetCurrency(v string) {
	o.Currency = &v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *BomComponentIn) GetSortOrder() int32 {
	if o == nil || IsNil(o.SortOrder) {
		var ret int32
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetSortOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *BomComponentIn) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given int32 and assigns it to the SortOrder field.
func (o *BomComponentIn) SetSortOrder(v int32) {
	o.SortOrder = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *BomComponentIn) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BomComponentIn) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *BomComponentIn) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *BomComponentIn) SetNotes(v string) {
	o.Notes = &v
}

func (o BomComponentIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BomComponentIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ComponentType) {
		toSerialize["component_type"] = o.ComponentType
	}
	toSerialize["provider"] = o.Provider
	toSerialize["model"] = o.Model
	toSerialize["metric_type"] = o.MetricType
	toSerialize["expected_quantity"] = o.ExpectedQuantity
	if !IsNil(o.ExpectedSpanCount) {
		toSerialize["expected_span_count"] = o.ExpectedSpanCount
	}
	if !IsNil(o.UnitCost) {
		toSerialize["unit_cost"] = o.UnitCost
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sort_order"] = o.SortOrder
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

func (o *BomComponentIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"model",
		"metric_type",
		"expected_quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBomComponentIn := _BomComponentIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBomComponentIn)

	if err != nil {
		return err
	}

	*o = BomComponentIn(varBomComponentIn)

	return err
}

type NullableBomComponentIn struct {
	value *BomComponentIn
	isSet bool
}

func (v NullableBomComponentIn) Get() *BomComponentIn {
	return v.value
}

func (v *NullableBomComponentIn) Set(val *BomComponentIn) {
	v.value = val
	v.isSet = true
}

func (v NullableBomComponentIn) IsSet() bool {
	return v.isSet
}

func (v *NullableBomComponentIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBomComponentIn(val *BomComponentIn) *NullableBomComponentIn {
	return &NullableBomComponentIn{value: val, isSet: true}
}

func (v NullableBomComponentIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBomComponentIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


