/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchIngestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchIngestRequest{}

// BatchIngestRequest struct for BatchIngestRequest
type BatchIngestRequest struct {
	Events []CostEventIngest `json:"events"`
}

type _BatchIngestRequest BatchIngestRequest

// NewBatchIngestRequest instantiates a new BatchIngestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchIngestRequest(events []CostEventIngest) *BatchIngestRequest {
	this := BatchIngestRequest{}
	this.Events = events
	return &this
}

// NewBatchIngestRequestWithDefaults instantiates a new BatchIngestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchIngestRequestWithDefaults() *BatchIngestRequest {
	this := BatchIngestRequest{}
	return &this
}

// GetEvents returns the Events field value
func (o *BatchIngestRequest) GetEvents() []CostEventIngest {
	if o == nil {
		var ret []CostEventIngest
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *BatchIngestRequest) GetEventsOk() ([]CostEventIngest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *BatchIngestRequest) SetEvents(v []CostEventIngest) {
	o.Events = v
}

func (o BatchIngestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchIngestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *BatchIngestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchIngestRequest := _BatchIngestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchIngestRequest)

	if err != nil {
		return err
	}

	*o = BatchIngestRequest(varBatchIngestRequest)

	return err
}

type NullableBatchIngestRequest struct {
	value *BatchIngestRequest
	isSet bool
}

func (v NullableBatchIngestRequest) Get() *BatchIngestRequest {
	return v.value
}

func (v *NullableBatchIngestRequest) Set(val *BatchIngestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchIngestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchIngestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchIngestRequest(val *BatchIngestRequest) *NullableBatchIngestRequest {
	return &NullableBatchIngestRequest{value: val, isSet: true}
}

func (v NullableBatchIngestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchIngestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


