/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the PaymentReversalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentReversalRequest{}

// PaymentReversalRequest struct for PaymentReversalRequest
type PaymentReversalRequest struct {
	// chargeback, nsf, ach_return, refund, correction
	ReversalType *string `json:"reversal_type,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewPaymentReversalRequest instantiates a new PaymentReversalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentReversalRequest() *PaymentReversalRequest {
	this := PaymentReversalRequest{}
	var reversalType string = "correction"
	this.ReversalType = &reversalType
	return &this
}

// NewPaymentReversalRequestWithDefaults instantiates a new PaymentReversalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentReversalRequestWithDefaults() *PaymentReversalRequest {
	this := PaymentReversalRequest{}
	var reversalType string = "correction"
	this.ReversalType = &reversalType
	return &this
}

// GetReversalType returns the ReversalType field value if set, zero value otherwise.
func (o *PaymentReversalRequest) GetReversalType() string {
	if o == nil || IsNil(o.ReversalType) {
		var ret string
		return ret
	}
	return *o.ReversalType
}

// GetReversalTypeOk returns a tuple with the ReversalType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentReversalRequest) GetReversalTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReversalType) {
		return nil, false
	}
	return o.ReversalType, true
}

// HasReversalType returns a boolean if a field has been set.
func (o *PaymentReversalRequest) HasReversalType() bool {
	if o != nil && !IsNil(o.ReversalType) {
		return true
	}

	return false
}

// SetReversalType gets a reference to the given string and assigns it to the ReversalType field.
func (o *PaymentReversalRequest) SetReversalType(v string) {
	o.ReversalType = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *PaymentReversalRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentReversalRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *PaymentReversalRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *PaymentReversalRequest) SetReason(v string) {
	o.Reason = &v
}

func (o PaymentReversalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentReversalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReversalType) {
		toSerialize["reversal_type"] = o.ReversalType
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullablePaymentReversalRequest struct {
	value *PaymentReversalRequest
	isSet bool
}

func (v NullablePaymentReversalRequest) Get() *PaymentReversalRequest {
	return v.value
}

func (v *NullablePaymentReversalRequest) Set(val *PaymentReversalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentReversalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentReversalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentReversalRequest(val *PaymentReversalRequest) *NullablePaymentReversalRequest {
	return &NullablePaymentReversalRequest{value: val, isSet: true}
}

func (v NullablePaymentReversalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentReversalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


