/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeterMappingItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeterMappingItem{}

// MeterMappingItem struct for MeterMappingItem
type MeterMappingItem struct {
	MeterSlug string `json:"meter_slug"`
	FeatureKey string `json:"feature_key"`
	EffectiveFrom string `json:"effective_from"`
	EffectiveTo string `json:"effective_to"`
	IsActive bool `json:"is_active"`
}

type _MeterMappingItem MeterMappingItem

// NewMeterMappingItem instantiates a new MeterMappingItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeterMappingItem(meterSlug string, featureKey string, effectiveFrom string, effectiveTo string, isActive bool) *MeterMappingItem {
	this := MeterMappingItem{}
	this.MeterSlug = meterSlug
	this.FeatureKey = featureKey
	this.EffectiveFrom = effectiveFrom
	this.EffectiveTo = effectiveTo
	this.IsActive = isActive
	return &this
}

// NewMeterMappingItemWithDefaults instantiates a new MeterMappingItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterMappingItemWithDefaults() *MeterMappingItem {
	this := MeterMappingItem{}
	return &this
}

// GetMeterSlug returns the MeterSlug field value
func (o *MeterMappingItem) GetMeterSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeterSlug
}

// GetMeterSlugOk returns a tuple with the MeterSlug field value
// and a boolean to check if the value has been set.
func (o *MeterMappingItem) GetMeterSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeterSlug, true
}

// SetMeterSlug sets field value
func (o *MeterMappingItem) SetMeterSlug(v string) {
	o.MeterSlug = v
}

// GetFeatureKey returns the FeatureKey field value
func (o *MeterMappingItem) GetFeatureKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeatureKey
}

// GetFeatureKeyOk returns a tuple with the FeatureKey field value
// and a boolean to check if the value has been set.
func (o *MeterMappingItem) GetFeatureKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeatureKey, true
}

// SetFeatureKey sets field value
func (o *MeterMappingItem) SetFeatureKey(v string) {
	o.FeatureKey = v
}

// GetEffectiveFrom returns the EffectiveFrom field value
func (o *MeterMappingItem) GetEffectiveFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value
// and a boolean to check if the value has been set.
func (o *MeterMappingItem) GetEffectiveFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveFrom, true
}

// SetEffectiveFrom sets field value
func (o *MeterMappingItem) SetEffectiveFrom(v string) {
	o.EffectiveFrom = v
}

// GetEffectiveTo returns the EffectiveTo field value
func (o *MeterMappingItem) GetEffectiveTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveTo
}

// GetEffectiveToOk returns a tuple with the EffectiveTo field value
// and a boolean to check if the value has been set.
func (o *MeterMappingItem) GetEffectiveToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveTo, true
}

// SetEffectiveTo sets field value
func (o *MeterMappingItem) SetEffectiveTo(v string) {
	o.EffectiveTo = v
}

// GetIsActive returns the IsActive field value
func (o *MeterMappingItem) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *MeterMappingItem) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *MeterMappingItem) SetIsActive(v bool) {
	o.IsActive = v
}

func (o MeterMappingItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeterMappingItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meter_slug"] = o.MeterSlug
	toSerialize["feature_key"] = o.FeatureKey
	toSerialize["effective_from"] = o.EffectiveFrom
	toSerialize["effective_to"] = o.EffectiveTo
	toSerialize["is_active"] = o.IsActive
	return toSerialize, nil
}

func (o *MeterMappingItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meter_slug",
		"feature_key",
		"effective_from",
		"effective_to",
		"is_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeterMappingItem := _MeterMappingItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeterMappingItem)

	if err != nil {
		return err
	}

	*o = MeterMappingItem(varMeterMappingItem)

	return err
}

type NullableMeterMappingItem struct {
	value *MeterMappingItem
	isSet bool
}

func (v NullableMeterMappingItem) Get() *MeterMappingItem {
	return v.value
}

func (v *NullableMeterMappingItem) Set(val *MeterMappingItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMeterMappingItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMeterMappingItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeterMappingItem(val *MeterMappingItem) *NullableMeterMappingItem {
	return &NullableMeterMappingItem{value: val, isSet: true}
}

func (v NullableMeterMappingItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeterMappingItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


