/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.1.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)

// AddonStatus The status of the add-on defined by the effectiveFrom and effectiveTo properties.
type AddonStatus string

// List of AddonStatus
const (
	ADDONSTATUS_DRAFT AddonStatus = "draft"
	ADDONSTATUS_ACTIVE AddonStatus = "active"
	ADDONSTATUS_ARCHIVED AddonStatus = "archived"
)

// All allowed values of AddonStatus enum
var AllowedAddonStatusEnumValues = []AddonStatus{
	"draft",
	"active",
	"archived",
}

func (v *AddonStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AddonStatus(value)
	for _, existing := range AllowedAddonStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AddonStatus", value)
}

// NewAddonStatusFromValue returns a pointer to a valid AddonStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAddonStatusFromValue(v string) (*AddonStatus, error) {
	ev := AddonStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AddonStatus: valid values are %v", v, AllowedAddonStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AddonStatus) IsValid() bool {
	for _, existing := range AllowedAddonStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AddonStatus value
func (v AddonStatus) Ptr() *AddonStatus {
	return &v
}

type NullableAddonStatus struct {
	value *AddonStatus
	isSet bool
}

func (v NullableAddonStatus) Get() *AddonStatus {
	return v.value
}

func (v *NullableAddonStatus) Set(val *AddonStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAddonStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAddonStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddonStatus(val *AddonStatus) *NullableAddonStatus {
	return &NullableAddonStatus{value: val, isSet: true}
}

func (v NullableAddonStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddonStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

