/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.2.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// CustomerAppData - CustomerAppData Stores the app specific data for the customer. One of: stripe, sandbox, custom_invoicing
type CustomerAppData struct {
	CustomInvoicingCustomerAppData *CustomInvoicingCustomerAppData
	SandboxCustomerAppData *SandboxCustomerAppData
	StripeCustomerAppData *StripeCustomerAppData
}

// CustomInvoicingCustomerAppDataAsCustomerAppData is a convenience function that returns CustomInvoicingCustomerAppData wrapped in CustomerAppData
func CustomInvoicingCustomerAppDataAsCustomerAppData(v *CustomInvoicingCustomerAppData) CustomerAppData {
	return CustomerAppData{
		CustomInvoicingCustomerAppData: v,
	}
}

// SandboxCustomerAppDataAsCustomerAppData is a convenience function that returns SandboxCustomerAppData wrapped in CustomerAppData
func SandboxCustomerAppDataAsCustomerAppData(v *SandboxCustomerAppData) CustomerAppData {
	return CustomerAppData{
		SandboxCustomerAppData: v,
	}
}

// StripeCustomerAppDataAsCustomerAppData is a convenience function that returns StripeCustomerAppData wrapped in CustomerAppData
func StripeCustomerAppDataAsCustomerAppData(v *StripeCustomerAppData) CustomerAppData {
	return CustomerAppData{
		StripeCustomerAppData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CustomerAppData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CustomInvoicingCustomerAppData
	err = newStrictDecoder(data).Decode(&dst.CustomInvoicingCustomerAppData)
	if err == nil {
		jsonCustomInvoicingCustomerAppData, _ := json.Marshal(dst.CustomInvoicingCustomerAppData)
		if string(jsonCustomInvoicingCustomerAppData) == "{}" { // empty struct
			dst.CustomInvoicingCustomerAppData = nil
		} else {
			if err = validator.Validate(dst.CustomInvoicingCustomerAppData); err != nil {
				dst.CustomInvoicingCustomerAppData = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomInvoicingCustomerAppData = nil
	}

	// try to unmarshal data into SandboxCustomerAppData
	err = newStrictDecoder(data).Decode(&dst.SandboxCustomerAppData)
	if err == nil {
		jsonSandboxCustomerAppData, _ := json.Marshal(dst.SandboxCustomerAppData)
		if string(jsonSandboxCustomerAppData) == "{}" { // empty struct
			dst.SandboxCustomerAppData = nil
		} else {
			if err = validator.Validate(dst.SandboxCustomerAppData); err != nil {
				dst.SandboxCustomerAppData = nil
			} else {
				match++
			}
		}
	} else {
		dst.SandboxCustomerAppData = nil
	}

	// try to unmarshal data into StripeCustomerAppData
	err = newStrictDecoder(data).Decode(&dst.StripeCustomerAppData)
	if err == nil {
		jsonStripeCustomerAppData, _ := json.Marshal(dst.StripeCustomerAppData)
		if string(jsonStripeCustomerAppData) == "{}" { // empty struct
			dst.StripeCustomerAppData = nil
		} else {
			if err = validator.Validate(dst.StripeCustomerAppData); err != nil {
				dst.StripeCustomerAppData = nil
			} else {
				match++
			}
		}
	} else {
		dst.StripeCustomerAppData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CustomInvoicingCustomerAppData = nil
		dst.SandboxCustomerAppData = nil
		dst.StripeCustomerAppData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CustomerAppData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CustomerAppData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CustomerAppData) MarshalJSON() ([]byte, error) {
	if src.CustomInvoicingCustomerAppData != nil {
		return json.Marshal(&src.CustomInvoicingCustomerAppData)
	}

	if src.SandboxCustomerAppData != nil {
		return json.Marshal(&src.SandboxCustomerAppData)
	}

	if src.StripeCustomerAppData != nil {
		return json.Marshal(&src.StripeCustomerAppData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CustomerAppData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CustomInvoicingCustomerAppData != nil {
		return obj.CustomInvoicingCustomerAppData
	}

	if obj.SandboxCustomerAppData != nil {
		return obj.SandboxCustomerAppData
	}

	if obj.StripeCustomerAppData != nil {
		return obj.StripeCustomerAppData
	}

	// all schemas are nil
	return nil
}

type NullableCustomerAppData struct {
	value *CustomerAppData
	isSet bool
}

func (v NullableCustomerAppData) Get() *CustomerAppData {
	return v.value
}

func (v *NullableCustomerAppData) Set(val *CustomerAppData) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerAppData) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerAppData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerAppData(val *CustomerAppData) *NullableCustomerAppData {
	return &NullableCustomerAppData{value: val, isSet: true}
}

func (v NullableCustomerAppData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerAppData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


