/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefundCreditRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundCreditRequest{}

// RefundCreditRequest struct for RefundCreditRequest
type RefundCreditRequest struct {
	AmountMicros int32 `json:"amount_micros"`
	RefundReference *string `json:"refund_reference,omitempty"`
}

type _RefundCreditRequest RefundCreditRequest

// NewRefundCreditRequest instantiates a new RefundCreditRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundCreditRequest(amountMicros int32) *RefundCreditRequest {
	this := RefundCreditRequest{}
	this.AmountMicros = amountMicros
	return &this
}

// NewRefundCreditRequestWithDefaults instantiates a new RefundCreditRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundCreditRequestWithDefaults() *RefundCreditRequest {
	this := RefundCreditRequest{}
	return &this
}

// GetAmountMicros returns the AmountMicros field value
func (o *RefundCreditRequest) GetAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmountMicros
}

// GetAmountMicrosOk returns a tuple with the AmountMicros field value
// and a boolean to check if the value has been set.
func (o *RefundCreditRequest) GetAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMicros, true
}

// SetAmountMicros sets field value
func (o *RefundCreditRequest) SetAmountMicros(v int32) {
	o.AmountMicros = v
}

// GetRefundReference returns the RefundReference field value if set, zero value otherwise.
func (o *RefundCreditRequest) GetRefundReference() string {
	if o == nil || IsNil(o.RefundReference) {
		var ret string
		return ret
	}
	return *o.RefundReference
}

// GetRefundReferenceOk returns a tuple with the RefundReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundCreditRequest) GetRefundReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.RefundReference) {
		return nil, false
	}
	return o.RefundReference, true
}

// HasRefundReference returns a boolean if a field has been set.
func (o *RefundCreditRequest) HasRefundReference() bool {
	if o != nil && !IsNil(o.RefundReference) {
		return true
	}

	return false
}

// SetRefundReference gets a reference to the given string and assigns it to the RefundReference field.
func (o *RefundCreditRequest) SetRefundReference(v string) {
	o.RefundReference = &v
}

func (o RefundCreditRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundCreditRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount_micros"] = o.AmountMicros
	if !IsNil(o.RefundReference) {
		toSerialize["refund_reference"] = o.RefundReference
	}
	return toSerialize, nil
}

func (o *RefundCreditRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount_micros",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefundCreditRequest := _RefundCreditRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefundCreditRequest)

	if err != nil {
		return err
	}

	*o = RefundCreditRequest(varRefundCreditRequest)

	return err
}

type NullableRefundCreditRequest struct {
	value *RefundCreditRequest
	isSet bool
}

func (v NullableRefundCreditRequest) Get() *RefundCreditRequest {
	return v.value
}

func (v *NullableRefundCreditRequest) Set(val *RefundCreditRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundCreditRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundCreditRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundCreditRequest(val *RefundCreditRequest) *NullableRefundCreditRequest {
	return &NullableRefundCreditRequest{value: val, isSet: true}
}

func (v NullableRefundCreditRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundCreditRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


