/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the NetSuiteManagedPortalBackfillRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetSuiteManagedPortalBackfillRequest{}

// NetSuiteManagedPortalBackfillRequest struct for NetSuiteManagedPortalBackfillRequest
type NetSuiteManagedPortalBackfillRequest struct {
	DryRun *bool `json:"dry_run,omitempty"`
	IncludeFalse *bool `json:"include_false,omitempty"`
}

// NewNetSuiteManagedPortalBackfillRequest instantiates a new NetSuiteManagedPortalBackfillRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetSuiteManagedPortalBackfillRequest() *NetSuiteManagedPortalBackfillRequest {
	this := NetSuiteManagedPortalBackfillRequest{}
	var dryRun bool = true
	this.DryRun = &dryRun
	var includeFalse bool = false
	this.IncludeFalse = &includeFalse
	return &this
}

// NewNetSuiteManagedPortalBackfillRequestWithDefaults instantiates a new NetSuiteManagedPortalBackfillRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetSuiteManagedPortalBackfillRequestWithDefaults() *NetSuiteManagedPortalBackfillRequest {
	this := NetSuiteManagedPortalBackfillRequest{}
	var dryRun bool = true
	this.DryRun = &dryRun
	var includeFalse bool = false
	this.IncludeFalse = &includeFalse
	return &this
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *NetSuiteManagedPortalBackfillRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetSuiteManagedPortalBackfillRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *NetSuiteManagedPortalBackfillRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *NetSuiteManagedPortalBackfillRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetIncludeFalse returns the IncludeFalse field value if set, zero value otherwise.
func (o *NetSuiteManagedPortalBackfillRequest) GetIncludeFalse() bool {
	if o == nil || IsNil(o.IncludeFalse) {
		var ret bool
		return ret
	}
	return *o.IncludeFalse
}

// GetIncludeFalseOk returns a tuple with the IncludeFalse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetSuiteManagedPortalBackfillRequest) GetIncludeFalseOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeFalse) {
		return nil, false
	}
	return o.IncludeFalse, true
}

// HasIncludeFalse returns a boolean if a field has been set.
func (o *NetSuiteManagedPortalBackfillRequest) HasIncludeFalse() bool {
	if o != nil && !IsNil(o.IncludeFalse) {
		return true
	}

	return false
}

// SetIncludeFalse gets a reference to the given bool and assigns it to the IncludeFalse field.
func (o *NetSuiteManagedPortalBackfillRequest) SetIncludeFalse(v bool) {
	o.IncludeFalse = &v
}

func (o NetSuiteManagedPortalBackfillRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetSuiteManagedPortalBackfillRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}
	if !IsNil(o.IncludeFalse) {
		toSerialize["include_false"] = o.IncludeFalse
	}
	return toSerialize, nil
}

type NullableNetSuiteManagedPortalBackfillRequest struct {
	value *NetSuiteManagedPortalBackfillRequest
	isSet bool
}

func (v NullableNetSuiteManagedPortalBackfillRequest) Get() *NetSuiteManagedPortalBackfillRequest {
	return v.value
}

func (v *NullableNetSuiteManagedPortalBackfillRequest) Set(val *NetSuiteManagedPortalBackfillRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetSuiteManagedPortalBackfillRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetSuiteManagedPortalBackfillRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetSuiteManagedPortalBackfillRequest(val *NetSuiteManagedPortalBackfillRequest) *NullableNetSuiteManagedPortalBackfillRequest {
	return &NullableNetSuiteManagedPortalBackfillRequest{value: val, isSet: true}
}

func (v NullableNetSuiteManagedPortalBackfillRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetSuiteManagedPortalBackfillRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


