/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MarketplaceListing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceListing{}

// MarketplaceListing A marketplace listing. Represent an available app in the app marketplace that can be installed to the organization.  Marketplace apps only exist in config so they don't extend the Resource model.
type MarketplaceListing struct {
	// The app's type
	Type AppType `json:"type"`
	// The app's name.
	Name string `json:"name"`
	// The app's description.
	Description string `json:"description"`
	// The app's capabilities.
	Capabilities []AppCapability `json:"capabilities"`
	// Install methods.  List of methods to install the app.
	InstallMethods []InstallMethod `json:"installMethods"`
}

type _MarketplaceListing MarketplaceListing

// NewMarketplaceListing instantiates a new MarketplaceListing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceListing(type_ AppType, name string, description string, capabilities []AppCapability, installMethods []InstallMethod) *MarketplaceListing {
	this := MarketplaceListing{}
	this.Type = type_
	this.Name = name
	this.Description = description
	this.Capabilities = capabilities
	this.InstallMethods = installMethods
	return &this
}

// NewMarketplaceListingWithDefaults instantiates a new MarketplaceListing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceListingWithDefaults() *MarketplaceListing {
	this := MarketplaceListing{}
	return &this
}

// GetType returns the Type field value
func (o *MarketplaceListing) GetType() AppType {
	if o == nil {
		var ret AppType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MarketplaceListing) GetTypeOk() (*AppType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MarketplaceListing) SetType(v AppType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *MarketplaceListing) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MarketplaceListing) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MarketplaceListing) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *MarketplaceListing) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MarketplaceListing) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MarketplaceListing) SetDescription(v string) {
	o.Description = v
}

// GetCapabilities returns the Capabilities field value
func (o *MarketplaceListing) GetCapabilities() []AppCapability {
	if o == nil {
		var ret []AppCapability
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *MarketplaceListing) GetCapabilitiesOk() ([]AppCapability, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capabilities, true
}

// SetCapabilities sets field value
func (o *MarketplaceListing) SetCapabilities(v []AppCapability) {
	o.Capabilities = v
}

// GetInstallMethods returns the InstallMethods field value
func (o *MarketplaceListing) GetInstallMethods() []InstallMethod {
	if o == nil {
		var ret []InstallMethod
		return ret
	}

	return o.InstallMethods
}

// GetInstallMethodsOk returns a tuple with the InstallMethods field value
// and a boolean to check if the value has been set.
func (o *MarketplaceListing) GetInstallMethodsOk() ([]InstallMethod, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstallMethods, true
}

// SetInstallMethods sets field value
func (o *MarketplaceListing) SetInstallMethods(v []InstallMethod) {
	o.InstallMethods = v
}

func (o MarketplaceListing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceListing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["capabilities"] = o.Capabilities
	toSerialize["installMethods"] = o.InstallMethods
	return toSerialize, nil
}

func (o *MarketplaceListing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"description",
		"capabilities",
		"installMethods",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMarketplaceListing := _MarketplaceListing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMarketplaceListing)

	if err != nil {
		return err
	}

	*o = MarketplaceListing(varMarketplaceListing)

	return err
}

type NullableMarketplaceListing struct {
	value *MarketplaceListing
	isSet bool
}

func (v NullableMarketplaceListing) Get() *MarketplaceListing {
	return v.value
}

func (v *NullableMarketplaceListing) Set(val *MarketplaceListing) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceListing) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceListing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceListing(val *MarketplaceListing) *NullableMarketplaceListing {
	return &NullableMarketplaceListing{value: val, isSet: true}
}

func (v NullableMarketplaceListing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceListing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


