/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)

// EntitlementType Type of the entitlement.
type EntitlementType string

// List of EntitlementType
const (
	ENTITLEMENTTYPE_METERED EntitlementType = "metered"
	ENTITLEMENTTYPE_BOOLEAN EntitlementType = "boolean"
	ENTITLEMENTTYPE_STATIC EntitlementType = "static"
)

// All allowed values of EntitlementType enum
var AllowedEntitlementTypeEnumValues = []EntitlementType{
	"metered",
	"boolean",
	"static",
}

func (v *EntitlementType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EntitlementType(value)
	for _, existing := range AllowedEntitlementTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EntitlementType", value)
}

// NewEntitlementTypeFromValue returns a pointer to a valid EntitlementType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEntitlementTypeFromValue(v string) (*EntitlementType, error) {
	ev := EntitlementType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EntitlementType: valid values are %v", v, AllowedEntitlementTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EntitlementType) IsValid() bool {
	for _, existing := range AllowedEntitlementTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EntitlementType value
func (v EntitlementType) Ptr() *EntitlementType {
	return &v
}

type NullableEntitlementType struct {
	value *EntitlementType
	isSet bool
}

func (v NullableEntitlementType) Get() *EntitlementType {
	return v.value
}

func (v *NullableEntitlementType) Set(val *EntitlementType) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementType) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementType(val *EntitlementType) *NullableEntitlementType {
	return &NullableEntitlementType{value: val, isSet: true}
}

func (v NullableEntitlementType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

