/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.2.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PlanSubscriptionCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanSubscriptionCreate{}

// PlanSubscriptionCreate Create subscription based on plan.
type PlanSubscriptionCreate struct {
	// What alignment settings the subscription should have.
	// Deprecated
	Alignment *Alignment `json:"alignment,omitempty"`
	// Arbitrary metadata associated with the subscription.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Commercial terms for this subscription (replaces prior overrides when set on change).
	CommercialOverrides *CommercialOverrides `json:"commercialOverrides,omitempty"`
	// The plan reference to change to.
	Plan PlanReferenceInput `json:"plan"`
	// The key of the phase to start the subscription in. If not provided, the subscription will start in the first phase of the plan.
	StartingPhase *string `json:"startingPhase,omitempty"`
	// The name of the Subscription. If not provided the plan name is used.
	Name *string `json:"name,omitempty"`
	// Description for the Subscription.
	Description *string `json:"description,omitempty"`
	// Timing configuration for the change, when the change should take effect. The default is immediate.
	Timing *SubscriptionTiming `json:"timing,omitempty"`
	// The ID of the customer. Provide either the key or ID. Has presedence over the key.
	CustomerId *string `json:"customerId,omitempty" validate:"regexp=^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$"`
	// The key of the customer. Provide either the key or ID.
	CustomerKey *string `json:"customerKey,omitempty"`
	// The billing anchor of the subscription. The provided date will be normalized according to the billing cadence to the nearest recurrence before start time. If not provided, the subscription start time will be used.
	BillingAnchor *time.Time `json:"billingAnchor,omitempty"`
}

type _PlanSubscriptionCreate PlanSubscriptionCreate

// NewPlanSubscriptionCreate instantiates a new PlanSubscriptionCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanSubscriptionCreate(plan PlanReferenceInput) *PlanSubscriptionCreate {
	this := PlanSubscriptionCreate{}
	this.Plan = plan
	return &this
}

// NewPlanSubscriptionCreateWithDefaults instantiates a new PlanSubscriptionCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanSubscriptionCreateWithDefaults() *PlanSubscriptionCreate {
	this := PlanSubscriptionCreate{}
	return &this
}

// GetAlignment returns the Alignment field value if set, zero value otherwise.
// Deprecated
func (o *PlanSubscriptionCreate) GetAlignment() Alignment {
	if o == nil || IsNil(o.Alignment) {
		var ret Alignment
		return ret
	}
	return *o.Alignment
}

// GetAlignmentOk returns a tuple with the Alignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *PlanSubscriptionCreate) GetAlignmentOk() (*Alignment, bool) {
	if o == nil || IsNil(o.Alignment) {
		return nil, false
	}
	return o.Alignment, true
}

// HasAlignment returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasAlignment() bool {
	if o != nil && !IsNil(o.Alignment) {
		return true
	}

	return false
}

// SetAlignment gets a reference to the given Alignment and assigns it to the Alignment field.
// Deprecated
func (o *PlanSubscriptionCreate) SetAlignment(v Alignment) {
	o.Alignment = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *PlanSubscriptionCreate) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetCommercialOverrides returns the CommercialOverrides field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetCommercialOverrides() CommercialOverrides {
	if o == nil || IsNil(o.CommercialOverrides) {
		var ret CommercialOverrides
		return ret
	}
	return *o.CommercialOverrides
}

// GetCommercialOverridesOk returns a tuple with the CommercialOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetCommercialOverridesOk() (*CommercialOverrides, bool) {
	if o == nil || IsNil(o.CommercialOverrides) {
		return nil, false
	}
	return o.CommercialOverrides, true
}

// HasCommercialOverrides returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasCommercialOverrides() bool {
	if o != nil && !IsNil(o.CommercialOverrides) {
		return true
	}

	return false
}

// SetCommercialOverrides gets a reference to the given CommercialOverrides and assigns it to the CommercialOverrides field.
func (o *PlanSubscriptionCreate) SetCommercialOverrides(v CommercialOverrides) {
	o.CommercialOverrides = &v
}

// GetPlan returns the Plan field value
func (o *PlanSubscriptionCreate) GetPlan() PlanReferenceInput {
	if o == nil {
		var ret PlanReferenceInput
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetPlanOk() (*PlanReferenceInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *PlanSubscriptionCreate) SetPlan(v PlanReferenceInput) {
	o.Plan = v
}

// GetStartingPhase returns the StartingPhase field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetStartingPhase() string {
	if o == nil || IsNil(o.StartingPhase) {
		var ret string
		return ret
	}
	return *o.StartingPhase
}

// GetStartingPhaseOk returns a tuple with the StartingPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetStartingPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.StartingPhase) {
		return nil, false
	}
	return o.StartingPhase, true
}

// HasStartingPhase returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasStartingPhase() bool {
	if o != nil && !IsNil(o.StartingPhase) {
		return true
	}

	return false
}

// SetStartingPhase gets a reference to the given string and assigns it to the StartingPhase field.
func (o *PlanSubscriptionCreate) SetStartingPhase(v string) {
	o.StartingPhase = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PlanSubscriptionCreate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlanSubscriptionCreate) SetDescription(v string) {
	o.Description = &v
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetTiming() SubscriptionTiming {
	if o == nil || IsNil(o.Timing) {
		var ret SubscriptionTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetTimingOk() (*SubscriptionTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given SubscriptionTiming and assigns it to the Timing field.
func (o *PlanSubscriptionCreate) SetTiming(v SubscriptionTiming) {
	o.Timing = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *PlanSubscriptionCreate) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetCustomerKey returns the CustomerKey field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetCustomerKey() string {
	if o == nil || IsNil(o.CustomerKey) {
		var ret string
		return ret
	}
	return *o.CustomerKey
}

// GetCustomerKeyOk returns a tuple with the CustomerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetCustomerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerKey) {
		return nil, false
	}
	return o.CustomerKey, true
}

// HasCustomerKey returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasCustomerKey() bool {
	if o != nil && !IsNil(o.CustomerKey) {
		return true
	}

	return false
}

// SetCustomerKey gets a reference to the given string and assigns it to the CustomerKey field.
func (o *PlanSubscriptionCreate) SetCustomerKey(v string) {
	o.CustomerKey = &v
}

// GetBillingAnchor returns the BillingAnchor field value if set, zero value otherwise.
func (o *PlanSubscriptionCreate) GetBillingAnchor() time.Time {
	if o == nil || IsNil(o.BillingAnchor) {
		var ret time.Time
		return ret
	}
	return *o.BillingAnchor
}

// GetBillingAnchorOk returns a tuple with the BillingAnchor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSubscriptionCreate) GetBillingAnchorOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BillingAnchor) {
		return nil, false
	}
	return o.BillingAnchor, true
}

// HasBillingAnchor returns a boolean if a field has been set.
func (o *PlanSubscriptionCreate) HasBillingAnchor() bool {
	if o != nil && !IsNil(o.BillingAnchor) {
		return true
	}

	return false
}

// SetBillingAnchor gets a reference to the given time.Time and assigns it to the BillingAnchor field.
func (o *PlanSubscriptionCreate) SetBillingAnchor(v time.Time) {
	o.BillingAnchor = &v
}

func (o PlanSubscriptionCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanSubscriptionCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alignment) {
		toSerialize["alignment"] = o.Alignment
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.CommercialOverrides) {
		toSerialize["commercialOverrides"] = o.CommercialOverrides
	}
	toSerialize["plan"] = o.Plan
	if !IsNil(o.StartingPhase) {
		toSerialize["startingPhase"] = o.StartingPhase
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.CustomerKey) {
		toSerialize["customerKey"] = o.CustomerKey
	}
	if !IsNil(o.BillingAnchor) {
		toSerialize["billingAnchor"] = o.BillingAnchor
	}
	return toSerialize, nil
}

func (o *PlanSubscriptionCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanSubscriptionCreate := _PlanSubscriptionCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlanSubscriptionCreate)

	if err != nil {
		return err
	}

	*o = PlanSubscriptionCreate(varPlanSubscriptionCreate)

	return err
}

type NullablePlanSubscriptionCreate struct {
	value *PlanSubscriptionCreate
	isSet bool
}

func (v NullablePlanSubscriptionCreate) Get() *PlanSubscriptionCreate {
	return v.value
}

func (v *NullablePlanSubscriptionCreate) Set(val *PlanSubscriptionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanSubscriptionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanSubscriptionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanSubscriptionCreate(val *PlanSubscriptionCreate) *NullablePlanSubscriptionCreate {
	return &NullablePlanSubscriptionCreate{value: val, isSet: true}
}

func (v NullablePlanSubscriptionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanSubscriptionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


