/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the ContactUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactUpdate{}

// ContactUpdate PATCH /contacts/{id} — partial update.
type ContactUpdate struct {
	FullName *string `json:"full_name,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Role *string `json:"role,omitempty"`
	IsPrimaryAp *bool `json:"is_primary_ap,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// NewContactUpdate instantiates a new ContactUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactUpdate() *ContactUpdate {
	this := ContactUpdate{}
	return &this
}

// NewContactUpdateWithDefaults instantiates a new ContactUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactUpdateWithDefaults() *ContactUpdate {
	this := ContactUpdate{}
	return &this
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *ContactUpdate) GetFullName() string {
	if o == nil || IsNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullName) {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *ContactUpdate) HasFullName() bool {
	if o != nil && !IsNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *ContactUpdate) SetFullName(v string) {
	o.FullName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ContactUpdate) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ContactUpdate) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ContactUpdate) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *ContactUpdate) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *ContactUpdate) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *ContactUpdate) SetPhone(v string) {
	o.Phone = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ContactUpdate) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ContactUpdate) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ContactUpdate) SetRole(v string) {
	o.Role = &v
}

// GetIsPrimaryAp returns the IsPrimaryAp field value if set, zero value otherwise.
func (o *ContactUpdate) GetIsPrimaryAp() bool {
	if o == nil || IsNil(o.IsPrimaryAp) {
		var ret bool
		return ret
	}
	return *o.IsPrimaryAp
}

// GetIsPrimaryApOk returns a tuple with the IsPrimaryAp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetIsPrimaryApOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrimaryAp) {
		return nil, false
	}
	return o.IsPrimaryAp, true
}

// HasIsPrimaryAp returns a boolean if a field has been set.
func (o *ContactUpdate) HasIsPrimaryAp() bool {
	if o != nil && !IsNil(o.IsPrimaryAp) {
		return true
	}

	return false
}

// SetIsPrimaryAp gets a reference to the given bool and assigns it to the IsPrimaryAp field.
func (o *ContactUpdate) SetIsPrimaryAp(v bool) {
	o.IsPrimaryAp = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ContactUpdate) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ContactUpdate) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ContactUpdate) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *ContactUpdate) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *ContactUpdate) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *ContactUpdate) SetLocale(v string) {
	o.Locale = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *ContactUpdate) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactUpdate) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *ContactUpdate) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *ContactUpdate) SetTimezone(v string) {
	o.Timezone = &v
}

func (o ContactUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.IsPrimaryAp) {
		toSerialize["is_primary_ap"] = o.IsPrimaryAp
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	return toSerialize, nil
}

type NullableContactUpdate struct {
	value *ContactUpdate
	isSet bool
}

func (v NullableContactUpdate) Get() *ContactUpdate {
	return v.value
}

func (v *NullableContactUpdate) Set(val *ContactUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableContactUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableContactUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactUpdate(val *ContactUpdate) *NullableContactUpdate {
	return &NullableContactUpdate{value: val, isSet: true}
}

func (v NullableContactUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


