/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.3.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublishTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishTemplateRequest{}

// PublishTemplateRequest struct for PublishTemplateRequest
type PublishTemplateRequest struct {
	VersionId string `json:"version_id"`
	ConfirmationAck bool `json:"confirmation_ack"`
	ChangeReason string `json:"change_reason"`
	PromptSummary *string `json:"prompt_summary,omitempty"`
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
}

type _PublishTemplateRequest PublishTemplateRequest

// NewPublishTemplateRequest instantiates a new PublishTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishTemplateRequest(versionId string, confirmationAck bool, changeReason string) *PublishTemplateRequest {
	this := PublishTemplateRequest{}
	this.VersionId = versionId
	this.ConfirmationAck = confirmationAck
	this.ChangeReason = changeReason
	return &this
}

// NewPublishTemplateRequestWithDefaults instantiates a new PublishTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishTemplateRequestWithDefaults() *PublishTemplateRequest {
	this := PublishTemplateRequest{}
	return &this
}

// GetVersionId returns the VersionId field value
func (o *PublishTemplateRequest) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *PublishTemplateRequest) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *PublishTemplateRequest) SetVersionId(v string) {
	o.VersionId = v
}

// GetConfirmationAck returns the ConfirmationAck field value
func (o *PublishTemplateRequest) GetConfirmationAck() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConfirmationAck
}

// GetConfirmationAckOk returns a tuple with the ConfirmationAck field value
// and a boolean to check if the value has been set.
func (o *PublishTemplateRequest) GetConfirmationAckOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfirmationAck, true
}

// SetConfirmationAck sets field value
func (o *PublishTemplateRequest) SetConfirmationAck(v bool) {
	o.ConfirmationAck = v
}

// GetChangeReason returns the ChangeReason field value
func (o *PublishTemplateRequest) GetChangeReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeReason
}

// GetChangeReasonOk returns a tuple with the ChangeReason field value
// and a boolean to check if the value has been set.
func (o *PublishTemplateRequest) GetChangeReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeReason, true
}

// SetChangeReason sets field value
func (o *PublishTemplateRequest) SetChangeReason(v string) {
	o.ChangeReason = v
}

// GetPromptSummary returns the PromptSummary field value if set, zero value otherwise.
func (o *PublishTemplateRequest) GetPromptSummary() string {
	if o == nil || IsNil(o.PromptSummary) {
		var ret string
		return ret
	}
	return *o.PromptSummary
}

// GetPromptSummaryOk returns a tuple with the PromptSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishTemplateRequest) GetPromptSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.PromptSummary) {
		return nil, false
	}
	return o.PromptSummary, true
}

// HasPromptSummary returns a boolean if a field has been set.
func (o *PublishTemplateRequest) HasPromptSummary() bool {
	if o != nil && !IsNil(o.PromptSummary) {
		return true
	}

	return false
}

// SetPromptSummary gets a reference to the given string and assigns it to the PromptSummary field.
func (o *PublishTemplateRequest) SetPromptSummary(v string) {
	o.PromptSummary = &v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *PublishTemplateRequest) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishTemplateRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *PublishTemplateRequest) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *PublishTemplateRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

func (o PublishTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version_id"] = o.VersionId
	toSerialize["confirmation_ack"] = o.ConfirmationAck
	toSerialize["change_reason"] = o.ChangeReason
	if !IsNil(o.PromptSummary) {
		toSerialize["prompt_summary"] = o.PromptSummary
	}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}
	return toSerialize, nil
}

func (o *PublishTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version_id",
		"confirmation_ack",
		"change_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishTemplateRequest := _PublishTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublishTemplateRequest)

	if err != nil {
		return err
	}

	*o = PublishTemplateRequest(varPublishTemplateRequest)

	return err
}

type NullablePublishTemplateRequest struct {
	value *PublishTemplateRequest
	isSet bool
}

func (v NullablePublishTemplateRequest) Get() *PublishTemplateRequest {
	return v.value
}

func (v *NullablePublishTemplateRequest) Set(val *PublishTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishTemplateRequest(val *PublishTemplateRequest) *NullablePublishTemplateRequest {
	return &NullablePublishTemplateRequest{value: val, isSet: true}
}

func (v NullablePublishTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


