/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit{}

// CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit Custom text that should be displayed after the payment confirmation button.
type CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit struct {
	Message *string `json:"message,omitempty"`
}

// NewCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit instantiates a new CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit() *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit {
	this := CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit{}
	return &this
}

// NewCheckoutSessionCustomTextAfterSubmitParamsAfterSubmitWithDefaults instantiates a new CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutSessionCustomTextAfterSubmitParamsAfterSubmitWithDefaults() *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit {
	this := CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) SetMessage(v string) {
	o.Message = &v
}

func (o CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit struct {
	value *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit
	isSet bool
}

func (v NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) Get() *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit {
	return v.value
}

func (v *NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) Set(val *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit(val *CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) *NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit {
	return &NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit{value: val, isSet: true}
}

func (v NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutSessionCustomTextAfterSubmitParamsAfterSubmit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


