/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotificationRuleBalanceThresholdValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationRuleBalanceThresholdValue{}

// NotificationRuleBalanceThresholdValue Threshold value with multiple supported types.
type NotificationRuleBalanceThresholdValue struct {
	// Value of the threshold.
	Value float64 `json:"value"`
	// Type of the threshold.
	Type NotificationRuleBalanceThresholdValueType `json:"type"`
}

type _NotificationRuleBalanceThresholdValue NotificationRuleBalanceThresholdValue

// NewNotificationRuleBalanceThresholdValue instantiates a new NotificationRuleBalanceThresholdValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationRuleBalanceThresholdValue(value float64, type_ NotificationRuleBalanceThresholdValueType) *NotificationRuleBalanceThresholdValue {
	this := NotificationRuleBalanceThresholdValue{}
	this.Value = value
	this.Type = type_
	return &this
}

// NewNotificationRuleBalanceThresholdValueWithDefaults instantiates a new NotificationRuleBalanceThresholdValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationRuleBalanceThresholdValueWithDefaults() *NotificationRuleBalanceThresholdValue {
	this := NotificationRuleBalanceThresholdValue{}
	return &this
}

// GetValue returns the Value field value
func (o *NotificationRuleBalanceThresholdValue) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NotificationRuleBalanceThresholdValue) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NotificationRuleBalanceThresholdValue) SetValue(v float64) {
	o.Value = v
}

// GetType returns the Type field value
func (o *NotificationRuleBalanceThresholdValue) GetType() NotificationRuleBalanceThresholdValueType {
	if o == nil {
		var ret NotificationRuleBalanceThresholdValueType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NotificationRuleBalanceThresholdValue) GetTypeOk() (*NotificationRuleBalanceThresholdValueType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NotificationRuleBalanceThresholdValue) SetType(v NotificationRuleBalanceThresholdValueType) {
	o.Type = v
}

func (o NotificationRuleBalanceThresholdValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationRuleBalanceThresholdValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *NotificationRuleBalanceThresholdValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationRuleBalanceThresholdValue := _NotificationRuleBalanceThresholdValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotificationRuleBalanceThresholdValue)

	if err != nil {
		return err
	}

	*o = NotificationRuleBalanceThresholdValue(varNotificationRuleBalanceThresholdValue)

	return err
}

type NullableNotificationRuleBalanceThresholdValue struct {
	value *NotificationRuleBalanceThresholdValue
	isSet bool
}

func (v NullableNotificationRuleBalanceThresholdValue) Get() *NotificationRuleBalanceThresholdValue {
	return v.value
}

func (v *NullableNotificationRuleBalanceThresholdValue) Set(val *NotificationRuleBalanceThresholdValue) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationRuleBalanceThresholdValue) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationRuleBalanceThresholdValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationRuleBalanceThresholdValue(val *NotificationRuleBalanceThresholdValue) *NullableNotificationRuleBalanceThresholdValue {
	return &NullableNotificationRuleBalanceThresholdValue{value: val, isSet: true}
}

func (v NullableNotificationRuleBalanceThresholdValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationRuleBalanceThresholdValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


