/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GrantPlanChangeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantPlanChangeRequest{}

// GrantPlanChangeRequest struct for GrantPlanChangeRequest
type GrantPlanChangeRequest struct {
	TenantId string `json:"tenant_id"`
	SubscriptionId string `json:"subscription_id"`
	CustomerId string `json:"customer_id"`
	OldPlanId string `json:"oldPlanId"`
	OldPlanVersion int32 `json:"oldPlanVersion"`
	NewPlanId string `json:"newPlanId"`
	NewPlanVersion int32 `json:"newPlanVersion"`
	EffectiveAt time.Time `json:"effectiveAt"`
	NewCreditConfig CreditConfigPayload `json:"newCreditConfig"`
	CommercialOverrides *CommercialOverridesPayload `json:"commercial_overrides,omitempty"`
	Entitlements []EntitlementPayload `json:"entitlements"`
	SubjectKeys []string `json:"subject_keys"`
}

type _GrantPlanChangeRequest GrantPlanChangeRequest

// NewGrantPlanChangeRequest instantiates a new GrantPlanChangeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantPlanChangeRequest(tenantId string, subscriptionId string, customerId string, oldPlanId string, oldPlanVersion int32, newPlanId string, newPlanVersion int32, effectiveAt time.Time, newCreditConfig CreditConfigPayload, entitlements []EntitlementPayload, subjectKeys []string) *GrantPlanChangeRequest {
	this := GrantPlanChangeRequest{}
	this.TenantId = tenantId
	this.SubscriptionId = subscriptionId
	this.CustomerId = customerId
	this.OldPlanId = oldPlanId
	this.OldPlanVersion = oldPlanVersion
	this.NewPlanId = newPlanId
	this.NewPlanVersion = newPlanVersion
	this.EffectiveAt = effectiveAt
	this.NewCreditConfig = newCreditConfig
	this.Entitlements = entitlements
	this.SubjectKeys = subjectKeys
	return &this
}

// NewGrantPlanChangeRequestWithDefaults instantiates a new GrantPlanChangeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantPlanChangeRequestWithDefaults() *GrantPlanChangeRequest {
	this := GrantPlanChangeRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *GrantPlanChangeRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *GrantPlanChangeRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *GrantPlanChangeRequest) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *GrantPlanChangeRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetCustomerId returns the CustomerId field value
func (o *GrantPlanChangeRequest) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *GrantPlanChangeRequest) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetOldPlanId returns the OldPlanId field value
func (o *GrantPlanChangeRequest) GetOldPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OldPlanId
}

// GetOldPlanIdOk returns a tuple with the OldPlanId field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetOldPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldPlanId, true
}

// SetOldPlanId sets field value
func (o *GrantPlanChangeRequest) SetOldPlanId(v string) {
	o.OldPlanId = v
}

// GetOldPlanVersion returns the OldPlanVersion field value
func (o *GrantPlanChangeRequest) GetOldPlanVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OldPlanVersion
}

// GetOldPlanVersionOk returns a tuple with the OldPlanVersion field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetOldPlanVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldPlanVersion, true
}

// SetOldPlanVersion sets field value
func (o *GrantPlanChangeRequest) SetOldPlanVersion(v int32) {
	o.OldPlanVersion = v
}

// GetNewPlanId returns the NewPlanId field value
func (o *GrantPlanChangeRequest) GetNewPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPlanId
}

// GetNewPlanIdOk returns a tuple with the NewPlanId field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetNewPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPlanId, true
}

// SetNewPlanId sets field value
func (o *GrantPlanChangeRequest) SetNewPlanId(v string) {
	o.NewPlanId = v
}

// GetNewPlanVersion returns the NewPlanVersion field value
func (o *GrantPlanChangeRequest) GetNewPlanVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NewPlanVersion
}

// GetNewPlanVersionOk returns a tuple with the NewPlanVersion field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetNewPlanVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPlanVersion, true
}

// SetNewPlanVersion sets field value
func (o *GrantPlanChangeRequest) SetNewPlanVersion(v int32) {
	o.NewPlanVersion = v
}

// GetEffectiveAt returns the EffectiveAt field value
func (o *GrantPlanChangeRequest) GetEffectiveAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EffectiveAt
}

// GetEffectiveAtOk returns a tuple with the EffectiveAt field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetEffectiveAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveAt, true
}

// SetEffectiveAt sets field value
func (o *GrantPlanChangeRequest) SetEffectiveAt(v time.Time) {
	o.EffectiveAt = v
}

// GetNewCreditConfig returns the NewCreditConfig field value
func (o *GrantPlanChangeRequest) GetNewCreditConfig() CreditConfigPayload {
	if o == nil {
		var ret CreditConfigPayload
		return ret
	}

	return o.NewCreditConfig
}

// GetNewCreditConfigOk returns a tuple with the NewCreditConfig field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetNewCreditConfigOk() (*CreditConfigPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewCreditConfig, true
}

// SetNewCreditConfig sets field value
func (o *GrantPlanChangeRequest) SetNewCreditConfig(v CreditConfigPayload) {
	o.NewCreditConfig = v
}

// GetCommercialOverrides returns the CommercialOverrides field value if set, zero value otherwise.
func (o *GrantPlanChangeRequest) GetCommercialOverrides() CommercialOverridesPayload {
	if o == nil || IsNil(o.CommercialOverrides) {
		var ret CommercialOverridesPayload
		return ret
	}
	return *o.CommercialOverrides
}

// GetCommercialOverridesOk returns a tuple with the CommercialOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetCommercialOverridesOk() (*CommercialOverridesPayload, bool) {
	if o == nil || IsNil(o.CommercialOverrides) {
		return nil, false
	}
	return o.CommercialOverrides, true
}

// HasCommercialOverrides returns a boolean if a field has been set.
func (o *GrantPlanChangeRequest) HasCommercialOverrides() bool {
	if o != nil && !IsNil(o.CommercialOverrides) {
		return true
	}

	return false
}

// SetCommercialOverrides gets a reference to the given CommercialOverridesPayload and assigns it to the CommercialOverrides field.
func (o *GrantPlanChangeRequest) SetCommercialOverrides(v CommercialOverridesPayload) {
	o.CommercialOverrides = &v
}

// GetEntitlements returns the Entitlements field value
func (o *GrantPlanChangeRequest) GetEntitlements() []EntitlementPayload {
	if o == nil {
		var ret []EntitlementPayload
		return ret
	}

	return o.Entitlements
}

// GetEntitlementsOk returns a tuple with the Entitlements field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetEntitlementsOk() ([]EntitlementPayload, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entitlements, true
}

// SetEntitlements sets field value
func (o *GrantPlanChangeRequest) SetEntitlements(v []EntitlementPayload) {
	o.Entitlements = v
}

// GetSubjectKeys returns the SubjectKeys field value
func (o *GrantPlanChangeRequest) GetSubjectKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SubjectKeys
}

// GetSubjectKeysOk returns a tuple with the SubjectKeys field value
// and a boolean to check if the value has been set.
func (o *GrantPlanChangeRequest) GetSubjectKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubjectKeys, true
}

// SetSubjectKeys sets field value
func (o *GrantPlanChangeRequest) SetSubjectKeys(v []string) {
	o.SubjectKeys = v
}

func (o GrantPlanChangeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantPlanChangeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["subscription_id"] = o.SubscriptionId
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["oldPlanId"] = o.OldPlanId
	toSerialize["oldPlanVersion"] = o.OldPlanVersion
	toSerialize["newPlanId"] = o.NewPlanId
	toSerialize["newPlanVersion"] = o.NewPlanVersion
	toSerialize["effectiveAt"] = o.EffectiveAt
	toSerialize["newCreditConfig"] = o.NewCreditConfig
	if !IsNil(o.CommercialOverrides) {
		toSerialize["commercial_overrides"] = o.CommercialOverrides
	}
	toSerialize["entitlements"] = o.Entitlements
	toSerialize["subject_keys"] = o.SubjectKeys
	return toSerialize, nil
}

func (o *GrantPlanChangeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"subscription_id",
		"customer_id",
		"oldPlanId",
		"oldPlanVersion",
		"newPlanId",
		"newPlanVersion",
		"effectiveAt",
		"newCreditConfig",
		"entitlements",
		"subject_keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantPlanChangeRequest := _GrantPlanChangeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrantPlanChangeRequest)

	if err != nil {
		return err
	}

	*o = GrantPlanChangeRequest(varGrantPlanChangeRequest)

	return err
}

type NullableGrantPlanChangeRequest struct {
	value *GrantPlanChangeRequest
	isSet bool
}

func (v NullableGrantPlanChangeRequest) Get() *GrantPlanChangeRequest {
	return v.value
}

func (v *NullableGrantPlanChangeRequest) Set(val *GrantPlanChangeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantPlanChangeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantPlanChangeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantPlanChangeRequest(val *GrantPlanChangeRequest) *NullableGrantPlanChangeRequest {
	return &NullableGrantPlanChangeRequest{value: val, isSet: true}
}

func (v NullableGrantPlanChangeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantPlanChangeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


