/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)

// AppCapabilityType App capability type.
type AppCapabilityType string

// List of AppCapabilityType
const (
	APPCAPABILITYTYPE_REPORT_USAGE AppCapabilityType = "reportUsage"
	APPCAPABILITYTYPE_REPORT_EVENTS AppCapabilityType = "reportEvents"
	APPCAPABILITYTYPE_CALCULATE_TAX AppCapabilityType = "calculateTax"
	APPCAPABILITYTYPE_INVOICE_CUSTOMERS AppCapabilityType = "invoiceCustomers"
	APPCAPABILITYTYPE_COLLECT_PAYMENTS AppCapabilityType = "collectPayments"
)

// All allowed values of AppCapabilityType enum
var AllowedAppCapabilityTypeEnumValues = []AppCapabilityType{
	"reportUsage",
	"reportEvents",
	"calculateTax",
	"invoiceCustomers",
	"collectPayments",
}

func (v *AppCapabilityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppCapabilityType(value)
	for _, existing := range AllowedAppCapabilityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppCapabilityType", value)
}

// NewAppCapabilityTypeFromValue returns a pointer to a valid AppCapabilityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppCapabilityTypeFromValue(v string) (*AppCapabilityType, error) {
	ev := AppCapabilityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppCapabilityType: valid values are %v", v, AllowedAppCapabilityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppCapabilityType) IsValid() bool {
	for _, existing := range AllowedAppCapabilityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppCapabilityType value
func (v AppCapabilityType) Ptr() *AppCapabilityType {
	return &v
}

type NullableAppCapabilityType struct {
	value *AppCapabilityType
	isSet bool
}

func (v NullableAppCapabilityType) Get() *AppCapabilityType {
	return v.value
}

func (v *NullableAppCapabilityType) Set(val *AppCapabilityType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppCapabilityType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppCapabilityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppCapabilityType(val *AppCapabilityType) *NullableAppCapabilityType {
	return &NullableAppCapabilityType{value: val, isSet: true}
}

func (v NullableAppCapabilityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppCapabilityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

