/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DisputeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisputeResponse{}

// DisputeResponse struct for DisputeResponse
type DisputeResponse struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	CaseId string `json:"case_id"`
	InvoiceId string `json:"invoice_id"`
	DisputeType *string `json:"dispute_type,omitempty"`
	ClassificationStatus *string `json:"classification_status,omitempty"`
	Status *string `json:"status,omitempty"`
	AccountingClass *string `json:"accounting_class,omitempty"`
	AccountingReasonCode *string `json:"accounting_reason_code,omitempty"`
	DisputedAmountMicros int32 `json:"disputed_amount_micros"`
	ResolvedAmountMicros *int32 `json:"resolved_amount_micros,omitempty"`
	Description string `json:"description"`
	ResolutionNotes *string `json:"resolution_notes,omitempty"`
	ExternalDisputeId *string `json:"external_dispute_id,omitempty"`
	AssignedTo *string `json:"assigned_to,omitempty"`
	ResolutionDeadline *time.Time `json:"resolution_deadline,omitempty"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	CustomerName *string `json:"customer_name,omitempty"`
	InvoiceNumber *string `json:"invoice_number,omitempty"`
	AgingBucket *string `json:"aging_bucket,omitempty"`
	InvoiceDate *string `json:"invoice_date,omitempty"`
	InvoiceDueDate *string `json:"invoice_due_date,omitempty"`
}

type _DisputeResponse DisputeResponse

// NewDisputeResponse instantiates a new DisputeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisputeResponse(id string, tenantId string, caseId string, invoiceId string, disputedAmountMicros int32, description string) *DisputeResponse {
	this := DisputeResponse{}
	this.Id = id
	this.TenantId = tenantId
	this.CaseId = caseId
	this.InvoiceId = invoiceId
	this.DisputedAmountMicros = disputedAmountMicros
	this.Description = description
	return &this
}

// NewDisputeResponseWithDefaults instantiates a new DisputeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisputeResponseWithDefaults() *DisputeResponse {
	this := DisputeResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DisputeResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DisputeResponse) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *DisputeResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *DisputeResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetCaseId returns the CaseId field value
func (o *DisputeResponse) GetCaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CaseId
}

// GetCaseIdOk returns a tuple with the CaseId field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetCaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaseId, true
}

// SetCaseId sets field value
func (o *DisputeResponse) SetCaseId(v string) {
	o.CaseId = v
}

// GetInvoiceId returns the InvoiceId field value
func (o *DisputeResponse) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets field value
func (o *DisputeResponse) SetInvoiceId(v string) {
	o.InvoiceId = v
}

// GetDisputeType returns the DisputeType field value if set, zero value otherwise.
func (o *DisputeResponse) GetDisputeType() string {
	if o == nil || IsNil(o.DisputeType) {
		var ret string
		return ret
	}
	return *o.DisputeType
}

// GetDisputeTypeOk returns a tuple with the DisputeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetDisputeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DisputeType) {
		return nil, false
	}
	return o.DisputeType, true
}

// HasDisputeType returns a boolean if a field has been set.
func (o *DisputeResponse) HasDisputeType() bool {
	if o != nil && !IsNil(o.DisputeType) {
		return true
	}

	return false
}

// SetDisputeType gets a reference to the given string and assigns it to the DisputeType field.
func (o *DisputeResponse) SetDisputeType(v string) {
	o.DisputeType = &v
}

// GetClassificationStatus returns the ClassificationStatus field value if set, zero value otherwise.
func (o *DisputeResponse) GetClassificationStatus() string {
	if o == nil || IsNil(o.ClassificationStatus) {
		var ret string
		return ret
	}
	return *o.ClassificationStatus
}

// GetClassificationStatusOk returns a tuple with the ClassificationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetClassificationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ClassificationStatus) {
		return nil, false
	}
	return o.ClassificationStatus, true
}

// HasClassificationStatus returns a boolean if a field has been set.
func (o *DisputeResponse) HasClassificationStatus() bool {
	if o != nil && !IsNil(o.ClassificationStatus) {
		return true
	}

	return false
}

// SetClassificationStatus gets a reference to the given string and assigns it to the ClassificationStatus field.
func (o *DisputeResponse) SetClassificationStatus(v string) {
	o.ClassificationStatus = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DisputeResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DisputeResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DisputeResponse) SetStatus(v string) {
	o.Status = &v
}

// GetAccountingClass returns the AccountingClass field value if set, zero value otherwise.
func (o *DisputeResponse) GetAccountingClass() string {
	if o == nil || IsNil(o.AccountingClass) {
		var ret string
		return ret
	}
	return *o.AccountingClass
}

// GetAccountingClassOk returns a tuple with the AccountingClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetAccountingClassOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingClass) {
		return nil, false
	}
	return o.AccountingClass, true
}

// HasAccountingClass returns a boolean if a field has been set.
func (o *DisputeResponse) HasAccountingClass() bool {
	if o != nil && !IsNil(o.AccountingClass) {
		return true
	}

	return false
}

// SetAccountingClass gets a reference to the given string and assigns it to the AccountingClass field.
func (o *DisputeResponse) SetAccountingClass(v string) {
	o.AccountingClass = &v
}

// GetAccountingReasonCode returns the AccountingReasonCode field value if set, zero value otherwise.
func (o *DisputeResponse) GetAccountingReasonCode() string {
	if o == nil || IsNil(o.AccountingReasonCode) {
		var ret string
		return ret
	}
	return *o.AccountingReasonCode
}

// GetAccountingReasonCodeOk returns a tuple with the AccountingReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetAccountingReasonCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingReasonCode) {
		return nil, false
	}
	return o.AccountingReasonCode, true
}

// HasAccountingReasonCode returns a boolean if a field has been set.
func (o *DisputeResponse) HasAccountingReasonCode() bool {
	if o != nil && !IsNil(o.AccountingReasonCode) {
		return true
	}

	return false
}

// SetAccountingReasonCode gets a reference to the given string and assigns it to the AccountingReasonCode field.
func (o *DisputeResponse) SetAccountingReasonCode(v string) {
	o.AccountingReasonCode = &v
}

// GetDisputedAmountMicros returns the DisputedAmountMicros field value
func (o *DisputeResponse) GetDisputedAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DisputedAmountMicros
}

// GetDisputedAmountMicrosOk returns a tuple with the DisputedAmountMicros field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetDisputedAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisputedAmountMicros, true
}

// SetDisputedAmountMicros sets field value
func (o *DisputeResponse) SetDisputedAmountMicros(v int32) {
	o.DisputedAmountMicros = v
}

// GetResolvedAmountMicros returns the ResolvedAmountMicros field value if set, zero value otherwise.
func (o *DisputeResponse) GetResolvedAmountMicros() int32 {
	if o == nil || IsNil(o.ResolvedAmountMicros) {
		var ret int32
		return ret
	}
	return *o.ResolvedAmountMicros
}

// GetResolvedAmountMicrosOk returns a tuple with the ResolvedAmountMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetResolvedAmountMicrosOk() (*int32, bool) {
	if o == nil || IsNil(o.ResolvedAmountMicros) {
		return nil, false
	}
	return o.ResolvedAmountMicros, true
}

// HasResolvedAmountMicros returns a boolean if a field has been set.
func (o *DisputeResponse) HasResolvedAmountMicros() bool {
	if o != nil && !IsNil(o.ResolvedAmountMicros) {
		return true
	}

	return false
}

// SetResolvedAmountMicros gets a reference to the given int32 and assigns it to the ResolvedAmountMicros field.
func (o *DisputeResponse) SetResolvedAmountMicros(v int32) {
	o.ResolvedAmountMicros = &v
}

// GetDescription returns the Description field value
func (o *DisputeResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DisputeResponse) SetDescription(v string) {
	o.Description = v
}

// GetResolutionNotes returns the ResolutionNotes field value if set, zero value otherwise.
func (o *DisputeResponse) GetResolutionNotes() string {
	if o == nil || IsNil(o.ResolutionNotes) {
		var ret string
		return ret
	}
	return *o.ResolutionNotes
}

// GetResolutionNotesOk returns a tuple with the ResolutionNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetResolutionNotesOk() (*string, bool) {
	if o == nil || IsNil(o.ResolutionNotes) {
		return nil, false
	}
	return o.ResolutionNotes, true
}

// HasResolutionNotes returns a boolean if a field has been set.
func (o *DisputeResponse) HasResolutionNotes() bool {
	if o != nil && !IsNil(o.ResolutionNotes) {
		return true
	}

	return false
}

// SetResolutionNotes gets a reference to the given string and assigns it to the ResolutionNotes field.
func (o *DisputeResponse) SetResolutionNotes(v string) {
	o.ResolutionNotes = &v
}

// GetExternalDisputeId returns the ExternalDisputeId field value if set, zero value otherwise.
func (o *DisputeResponse) GetExternalDisputeId() string {
	if o == nil || IsNil(o.ExternalDisputeId) {
		var ret string
		return ret
	}
	return *o.ExternalDisputeId
}

// GetExternalDisputeIdOk returns a tuple with the ExternalDisputeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetExternalDisputeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalDisputeId) {
		return nil, false
	}
	return o.ExternalDisputeId, true
}

// HasExternalDisputeId returns a boolean if a field has been set.
func (o *DisputeResponse) HasExternalDisputeId() bool {
	if o != nil && !IsNil(o.ExternalDisputeId) {
		return true
	}

	return false
}

// SetExternalDisputeId gets a reference to the given string and assigns it to the ExternalDisputeId field.
func (o *DisputeResponse) SetExternalDisputeId(v string) {
	o.ExternalDisputeId = &v
}

// GetAssignedTo returns the AssignedTo field value if set, zero value otherwise.
func (o *DisputeResponse) GetAssignedTo() string {
	if o == nil || IsNil(o.AssignedTo) {
		var ret string
		return ret
	}
	return *o.AssignedTo
}

// GetAssignedToOk returns a tuple with the AssignedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetAssignedToOk() (*string, bool) {
	if o == nil || IsNil(o.AssignedTo) {
		return nil, false
	}
	return o.AssignedTo, true
}

// HasAssignedTo returns a boolean if a field has been set.
func (o *DisputeResponse) HasAssignedTo() bool {
	if o != nil && !IsNil(o.AssignedTo) {
		return true
	}

	return false
}

// SetAssignedTo gets a reference to the given string and assigns it to the AssignedTo field.
func (o *DisputeResponse) SetAssignedTo(v string) {
	o.AssignedTo = &v
}

// GetResolutionDeadline returns the ResolutionDeadline field value if set, zero value otherwise.
func (o *DisputeResponse) GetResolutionDeadline() time.Time {
	if o == nil || IsNil(o.ResolutionDeadline) {
		var ret time.Time
		return ret
	}
	return *o.ResolutionDeadline
}

// GetResolutionDeadlineOk returns a tuple with the ResolutionDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetResolutionDeadlineOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolutionDeadline) {
		return nil, false
	}
	return o.ResolutionDeadline, true
}

// HasResolutionDeadline returns a boolean if a field has been set.
func (o *DisputeResponse) HasResolutionDeadline() bool {
	if o != nil && !IsNil(o.ResolutionDeadline) {
		return true
	}

	return false
}

// SetResolutionDeadline gets a reference to the given time.Time and assigns it to the ResolutionDeadline field.
func (o *DisputeResponse) SetResolutionDeadline(v time.Time) {
	o.ResolutionDeadline = &v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *DisputeResponse) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *DisputeResponse) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *DisputeResponse) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DisputeResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DisputeResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DisputeResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DisputeResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DisputeResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *DisputeResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *DisputeResponse) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *DisputeResponse) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *DisputeResponse) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetInvoiceNumber returns the InvoiceNumber field value if set, zero value otherwise.
func (o *DisputeResponse) GetInvoiceNumber() string {
	if o == nil || IsNil(o.InvoiceNumber) {
		var ret string
		return ret
	}
	return *o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetInvoiceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceNumber) {
		return nil, false
	}
	return o.InvoiceNumber, true
}

// HasInvoiceNumber returns a boolean if a field has been set.
func (o *DisputeResponse) HasInvoiceNumber() bool {
	if o != nil && !IsNil(o.InvoiceNumber) {
		return true
	}

	return false
}

// SetInvoiceNumber gets a reference to the given string and assigns it to the InvoiceNumber field.
func (o *DisputeResponse) SetInvoiceNumber(v string) {
	o.InvoiceNumber = &v
}

// GetAgingBucket returns the AgingBucket field value if set, zero value otherwise.
func (o *DisputeResponse) GetAgingBucket() string {
	if o == nil || IsNil(o.AgingBucket) {
		var ret string
		return ret
	}
	return *o.AgingBucket
}

// GetAgingBucketOk returns a tuple with the AgingBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetAgingBucketOk() (*string, bool) {
	if o == nil || IsNil(o.AgingBucket) {
		return nil, false
	}
	return o.AgingBucket, true
}

// HasAgingBucket returns a boolean if a field has been set.
func (o *DisputeResponse) HasAgingBucket() bool {
	if o != nil && !IsNil(o.AgingBucket) {
		return true
	}

	return false
}

// SetAgingBucket gets a reference to the given string and assigns it to the AgingBucket field.
func (o *DisputeResponse) SetAgingBucket(v string) {
	o.AgingBucket = &v
}

// GetInvoiceDate returns the InvoiceDate field value if set, zero value otherwise.
func (o *DisputeResponse) GetInvoiceDate() string {
	if o == nil || IsNil(o.InvoiceDate) {
		var ret string
		return ret
	}
	return *o.InvoiceDate
}

// GetInvoiceDateOk returns a tuple with the InvoiceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetInvoiceDateOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceDate) {
		return nil, false
	}
	return o.InvoiceDate, true
}

// HasInvoiceDate returns a boolean if a field has been set.
func (o *DisputeResponse) HasInvoiceDate() bool {
	if o != nil && !IsNil(o.InvoiceDate) {
		return true
	}

	return false
}

// SetInvoiceDate gets a reference to the given string and assigns it to the InvoiceDate field.
func (o *DisputeResponse) SetInvoiceDate(v string) {
	o.InvoiceDate = &v
}

// GetInvoiceDueDate returns the InvoiceDueDate field value if set, zero value otherwise.
func (o *DisputeResponse) GetInvoiceDueDate() string {
	if o == nil || IsNil(o.InvoiceDueDate) {
		var ret string
		return ret
	}
	return *o.InvoiceDueDate
}

// GetInvoiceDueDateOk returns a tuple with the InvoiceDueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisputeResponse) GetInvoiceDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceDueDate) {
		return nil, false
	}
	return o.InvoiceDueDate, true
}

// HasInvoiceDueDate returns a boolean if a field has been set.
func (o *DisputeResponse) HasInvoiceDueDate() bool {
	if o != nil && !IsNil(o.InvoiceDueDate) {
		return true
	}

	return false
}

// SetInvoiceDueDate gets a reference to the given string and assigns it to the InvoiceDueDate field.
func (o *DisputeResponse) SetInvoiceDueDate(v string) {
	o.InvoiceDueDate = &v
}

func (o DisputeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisputeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["case_id"] = o.CaseId
	toSerialize["invoice_id"] = o.InvoiceId
	if !IsNil(o.DisputeType) {
		toSerialize["dispute_type"] = o.DisputeType
	}
	if !IsNil(o.ClassificationStatus) {
		toSerialize["classification_status"] = o.ClassificationStatus
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AccountingClass) {
		toSerialize["accounting_class"] = o.AccountingClass
	}
	if !IsNil(o.AccountingReasonCode) {
		toSerialize["accounting_reason_code"] = o.AccountingReasonCode
	}
	toSerialize["disputed_amount_micros"] = o.DisputedAmountMicros
	if !IsNil(o.ResolvedAmountMicros) {
		toSerialize["resolved_amount_micros"] = o.ResolvedAmountMicros
	}
	toSerialize["description"] = o.Description
	if !IsNil(o.ResolutionNotes) {
		toSerialize["resolution_notes"] = o.ResolutionNotes
	}
	if !IsNil(o.ExternalDisputeId) {
		toSerialize["external_dispute_id"] = o.ExternalDisputeId
	}
	if !IsNil(o.AssignedTo) {
		toSerialize["assigned_to"] = o.AssignedTo
	}
	if !IsNil(o.ResolutionDeadline) {
		toSerialize["resolution_deadline"] = o.ResolutionDeadline
	}
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.CustomerName) {
		toSerialize["customer_name"] = o.CustomerName
	}
	if !IsNil(o.InvoiceNumber) {
		toSerialize["invoice_number"] = o.InvoiceNumber
	}
	if !IsNil(o.AgingBucket) {
		toSerialize["aging_bucket"] = o.AgingBucket
	}
	if !IsNil(o.InvoiceDate) {
		toSerialize["invoice_date"] = o.InvoiceDate
	}
	if !IsNil(o.InvoiceDueDate) {
		toSerialize["invoice_due_date"] = o.InvoiceDueDate
	}
	return toSerialize, nil
}

func (o *DisputeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"case_id",
		"invoice_id",
		"disputed_amount_micros",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisputeResponse := _DisputeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisputeResponse)

	if err != nil {
		return err
	}

	*o = DisputeResponse(varDisputeResponse)

	return err
}

type NullableDisputeResponse struct {
	value *DisputeResponse
	isSet bool
}

func (v NullableDisputeResponse) Get() *DisputeResponse {
	return v.value
}

func (v *NullableDisputeResponse) Set(val *DisputeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDisputeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDisputeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisputeResponse(val *DisputeResponse) *NullableDisputeResponse {
	return &NullableDisputeResponse{value: val, isSet: true}
}

func (v NullableDisputeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisputeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


