/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the UpdateWalletThresholdsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWalletThresholdsRequest{}

// UpdateWalletThresholdsRequest Request to update wallet thresholds.
type UpdateWalletThresholdsRequest struct {
	LocalSoftThresholdMicros NullableInt32 `json:"local_soft_threshold_micros,omitempty"`
	LocalHardCapMicros NullableInt32 `json:"local_hard_cap_micros,omitempty"`
	AuditNote NullableString `json:"audit_note,omitempty"`
}

// NewUpdateWalletThresholdsRequest instantiates a new UpdateWalletThresholdsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWalletThresholdsRequest() *UpdateWalletThresholdsRequest {
	this := UpdateWalletThresholdsRequest{}
	return &this
}

// NewUpdateWalletThresholdsRequestWithDefaults instantiates a new UpdateWalletThresholdsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWalletThresholdsRequestWithDefaults() *UpdateWalletThresholdsRequest {
	this := UpdateWalletThresholdsRequest{}
	return &this
}

// GetLocalSoftThresholdMicros returns the LocalSoftThresholdMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateWalletThresholdsRequest) GetLocalSoftThresholdMicros() int32 {
	if o == nil || IsNil(o.LocalSoftThresholdMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.LocalSoftThresholdMicros.Get()
}

// GetLocalSoftThresholdMicrosOk returns a tuple with the LocalSoftThresholdMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateWalletThresholdsRequest) GetLocalSoftThresholdMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocalSoftThresholdMicros.Get(), o.LocalSoftThresholdMicros.IsSet()
}

// HasLocalSoftThresholdMicros returns a boolean if a field has been set.
func (o *UpdateWalletThresholdsRequest) HasLocalSoftThresholdMicros() bool {
	if o != nil && o.LocalSoftThresholdMicros.IsSet() {
		return true
	}

	return false
}

// SetLocalSoftThresholdMicros gets a reference to the given NullableInt32 and assigns it to the LocalSoftThresholdMicros field.
func (o *UpdateWalletThresholdsRequest) SetLocalSoftThresholdMicros(v int32) {
	o.LocalSoftThresholdMicros.Set(&v)
}
// SetLocalSoftThresholdMicrosNil sets the value for LocalSoftThresholdMicros to be an explicit nil
func (o *UpdateWalletThresholdsRequest) SetLocalSoftThresholdMicrosNil() {
	o.LocalSoftThresholdMicros.Set(nil)
}

// UnsetLocalSoftThresholdMicros ensures that no value is present for LocalSoftThresholdMicros, not even an explicit nil
func (o *UpdateWalletThresholdsRequest) UnsetLocalSoftThresholdMicros() {
	o.LocalSoftThresholdMicros.Unset()
}

// GetLocalHardCapMicros returns the LocalHardCapMicros field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateWalletThresholdsRequest) GetLocalHardCapMicros() int32 {
	if o == nil || IsNil(o.LocalHardCapMicros.Get()) {
		var ret int32
		return ret
	}
	return *o.LocalHardCapMicros.Get()
}

// GetLocalHardCapMicrosOk returns a tuple with the LocalHardCapMicros field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateWalletThresholdsRequest) GetLocalHardCapMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocalHardCapMicros.Get(), o.LocalHardCapMicros.IsSet()
}

// HasLocalHardCapMicros returns a boolean if a field has been set.
func (o *UpdateWalletThresholdsRequest) HasLocalHardCapMicros() bool {
	if o != nil && o.LocalHardCapMicros.IsSet() {
		return true
	}

	return false
}

// SetLocalHardCapMicros gets a reference to the given NullableInt32 and assigns it to the LocalHardCapMicros field.
func (o *UpdateWalletThresholdsRequest) SetLocalHardCapMicros(v int32) {
	o.LocalHardCapMicros.Set(&v)
}
// SetLocalHardCapMicrosNil sets the value for LocalHardCapMicros to be an explicit nil
func (o *UpdateWalletThresholdsRequest) SetLocalHardCapMicrosNil() {
	o.LocalHardCapMicros.Set(nil)
}

// UnsetLocalHardCapMicros ensures that no value is present for LocalHardCapMicros, not even an explicit nil
func (o *UpdateWalletThresholdsRequest) UnsetLocalHardCapMicros() {
	o.LocalHardCapMicros.Unset()
}

// GetAuditNote returns the AuditNote field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateWalletThresholdsRequest) GetAuditNote() string {
	if o == nil || IsNil(o.AuditNote.Get()) {
		var ret string
		return ret
	}
	return *o.AuditNote.Get()
}

// GetAuditNoteOk returns a tuple with the AuditNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateWalletThresholdsRequest) GetAuditNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditNote.Get(), o.AuditNote.IsSet()
}

// HasAuditNote returns a boolean if a field has been set.
func (o *UpdateWalletThresholdsRequest) HasAuditNote() bool {
	if o != nil && o.AuditNote.IsSet() {
		return true
	}

	return false
}

// SetAuditNote gets a reference to the given NullableString and assigns it to the AuditNote field.
func (o *UpdateWalletThresholdsRequest) SetAuditNote(v string) {
	o.AuditNote.Set(&v)
}
// SetAuditNoteNil sets the value for AuditNote to be an explicit nil
func (o *UpdateWalletThresholdsRequest) SetAuditNoteNil() {
	o.AuditNote.Set(nil)
}

// UnsetAuditNote ensures that no value is present for AuditNote, not even an explicit nil
func (o *UpdateWalletThresholdsRequest) UnsetAuditNote() {
	o.AuditNote.Unset()
}

func (o UpdateWalletThresholdsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWalletThresholdsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.LocalSoftThresholdMicros.IsSet() {
		toSerialize["local_soft_threshold_micros"] = o.LocalSoftThresholdMicros.Get()
	}
	if o.LocalHardCapMicros.IsSet() {
		toSerialize["local_hard_cap_micros"] = o.LocalHardCapMicros.Get()
	}
	if o.AuditNote.IsSet() {
		toSerialize["audit_note"] = o.AuditNote.Get()
	}
	return toSerialize, nil
}

type NullableUpdateWalletThresholdsRequest struct {
	value *UpdateWalletThresholdsRequest
	isSet bool
}

func (v NullableUpdateWalletThresholdsRequest) Get() *UpdateWalletThresholdsRequest {
	return v.value
}

func (v *NullableUpdateWalletThresholdsRequest) Set(val *UpdateWalletThresholdsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWalletThresholdsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWalletThresholdsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWalletThresholdsRequest(val *UpdateWalletThresholdsRequest) *NullableUpdateWalletThresholdsRequest {
	return &NullableUpdateWalletThresholdsRequest{value: val, isSet: true}
}

func (v NullableUpdateWalletThresholdsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWalletThresholdsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


