/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.3.0-rc2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DraftLockResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DraftLockResponse{}

// DraftLockResponse struct for DraftLockResponse
type DraftLockResponse struct {
	VersionId string `json:"version_id"`
	LockId string `json:"lock_id"`
	LockToken string `json:"lock_token"`
	LockOwnerActorId string `json:"lock_owner_actor_id"`
	LockOwnerDisplay *string `json:"lock_owner_display,omitempty"`
	LockExpiresAt string `json:"lock_expires_at"`
}

type _DraftLockResponse DraftLockResponse

// NewDraftLockResponse instantiates a new DraftLockResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDraftLockResponse(versionId string, lockId string, lockToken string, lockOwnerActorId string, lockExpiresAt string) *DraftLockResponse {
	this := DraftLockResponse{}
	this.VersionId = versionId
	this.LockId = lockId
	this.LockToken = lockToken
	this.LockOwnerActorId = lockOwnerActorId
	this.LockExpiresAt = lockExpiresAt
	return &this
}

// NewDraftLockResponseWithDefaults instantiates a new DraftLockResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDraftLockResponseWithDefaults() *DraftLockResponse {
	this := DraftLockResponse{}
	return &this
}

// GetVersionId returns the VersionId field value
func (o *DraftLockResponse) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *DraftLockResponse) SetVersionId(v string) {
	o.VersionId = v
}

// GetLockId returns the LockId field value
func (o *DraftLockResponse) GetLockId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LockId
}

// GetLockIdOk returns a tuple with the LockId field value
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetLockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockId, true
}

// SetLockId sets field value
func (o *DraftLockResponse) SetLockId(v string) {
	o.LockId = v
}

// GetLockToken returns the LockToken field value
func (o *DraftLockResponse) GetLockToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LockToken
}

// GetLockTokenOk returns a tuple with the LockToken field value
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetLockTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockToken, true
}

// SetLockToken sets field value
func (o *DraftLockResponse) SetLockToken(v string) {
	o.LockToken = v
}

// GetLockOwnerActorId returns the LockOwnerActorId field value
func (o *DraftLockResponse) GetLockOwnerActorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LockOwnerActorId
}

// GetLockOwnerActorIdOk returns a tuple with the LockOwnerActorId field value
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetLockOwnerActorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockOwnerActorId, true
}

// SetLockOwnerActorId sets field value
func (o *DraftLockResponse) SetLockOwnerActorId(v string) {
	o.LockOwnerActorId = v
}

// GetLockOwnerDisplay returns the LockOwnerDisplay field value if set, zero value otherwise.
func (o *DraftLockResponse) GetLockOwnerDisplay() string {
	if o == nil || IsNil(o.LockOwnerDisplay) {
		var ret string
		return ret
	}
	return *o.LockOwnerDisplay
}

// GetLockOwnerDisplayOk returns a tuple with the LockOwnerDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetLockOwnerDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.LockOwnerDisplay) {
		return nil, false
	}
	return o.LockOwnerDisplay, true
}

// HasLockOwnerDisplay returns a boolean if a field has been set.
func (o *DraftLockResponse) HasLockOwnerDisplay() bool {
	if o != nil && !IsNil(o.LockOwnerDisplay) {
		return true
	}

	return false
}

// SetLockOwnerDisplay gets a reference to the given string and assigns it to the LockOwnerDisplay field.
func (o *DraftLockResponse) SetLockOwnerDisplay(v string) {
	o.LockOwnerDisplay = &v
}

// GetLockExpiresAt returns the LockExpiresAt field value
func (o *DraftLockResponse) GetLockExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LockExpiresAt
}

// GetLockExpiresAtOk returns a tuple with the LockExpiresAt field value
// and a boolean to check if the value has been set.
func (o *DraftLockResponse) GetLockExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockExpiresAt, true
}

// SetLockExpiresAt sets field value
func (o *DraftLockResponse) SetLockExpiresAt(v string) {
	o.LockExpiresAt = v
}

func (o DraftLockResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DraftLockResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version_id"] = o.VersionId
	toSerialize["lock_id"] = o.LockId
	toSerialize["lock_token"] = o.LockToken
	toSerialize["lock_owner_actor_id"] = o.LockOwnerActorId
	if !IsNil(o.LockOwnerDisplay) {
		toSerialize["lock_owner_display"] = o.LockOwnerDisplay
	}
	toSerialize["lock_expires_at"] = o.LockExpiresAt
	return toSerialize, nil
}

func (o *DraftLockResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version_id",
		"lock_id",
		"lock_token",
		"lock_owner_actor_id",
		"lock_expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDraftLockResponse := _DraftLockResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDraftLockResponse)

	if err != nil {
		return err
	}

	*o = DraftLockResponse(varDraftLockResponse)

	return err
}

type NullableDraftLockResponse struct {
	value *DraftLockResponse
	isSet bool
}

func (v NullableDraftLockResponse) Get() *DraftLockResponse {
	return v.value
}

func (v *NullableDraftLockResponse) Set(val *DraftLockResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDraftLockResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDraftLockResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDraftLockResponse(val *DraftLockResponse) *NullableDraftLockResponse {
	return &NullableDraftLockResponse{value: val, isSet: true}
}

func (v NullableDraftLockResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDraftLockResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


