/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EvidenceReviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvidenceReviewRequest{}

// EvidenceReviewRequest struct for EvidenceReviewRequest
type EvidenceReviewRequest struct {
	// upheld, denied, or partial
	ResolutionStatus string `json:"resolution_status"`
	ResolvedAmountMicros int32 `json:"resolved_amount_micros"`
}

type _EvidenceReviewRequest EvidenceReviewRequest

// NewEvidenceReviewRequest instantiates a new EvidenceReviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvidenceReviewRequest(resolutionStatus string, resolvedAmountMicros int32) *EvidenceReviewRequest {
	this := EvidenceReviewRequest{}
	this.ResolutionStatus = resolutionStatus
	this.ResolvedAmountMicros = resolvedAmountMicros
	return &this
}

// NewEvidenceReviewRequestWithDefaults instantiates a new EvidenceReviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvidenceReviewRequestWithDefaults() *EvidenceReviewRequest {
	this := EvidenceReviewRequest{}
	return &this
}

// GetResolutionStatus returns the ResolutionStatus field value
func (o *EvidenceReviewRequest) GetResolutionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolutionStatus
}

// GetResolutionStatusOk returns a tuple with the ResolutionStatus field value
// and a boolean to check if the value has been set.
func (o *EvidenceReviewRequest) GetResolutionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolutionStatus, true
}

// SetResolutionStatus sets field value
func (o *EvidenceReviewRequest) SetResolutionStatus(v string) {
	o.ResolutionStatus = v
}

// GetResolvedAmountMicros returns the ResolvedAmountMicros field value
func (o *EvidenceReviewRequest) GetResolvedAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ResolvedAmountMicros
}

// GetResolvedAmountMicrosOk returns a tuple with the ResolvedAmountMicros field value
// and a boolean to check if the value has been set.
func (o *EvidenceReviewRequest) GetResolvedAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolvedAmountMicros, true
}

// SetResolvedAmountMicros sets field value
func (o *EvidenceReviewRequest) SetResolvedAmountMicros(v int32) {
	o.ResolvedAmountMicros = v
}

func (o EvidenceReviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvidenceReviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resolution_status"] = o.ResolutionStatus
	toSerialize["resolved_amount_micros"] = o.ResolvedAmountMicros
	return toSerialize, nil
}

func (o *EvidenceReviewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resolution_status",
		"resolved_amount_micros",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvidenceReviewRequest := _EvidenceReviewRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvidenceReviewRequest)

	if err != nil {
		return err
	}

	*o = EvidenceReviewRequest(varEvidenceReviewRequest)

	return err
}

type NullableEvidenceReviewRequest struct {
	value *EvidenceReviewRequest
	isSet bool
}

func (v NullableEvidenceReviewRequest) Get() *EvidenceReviewRequest {
	return v.value
}

func (v *NullableEvidenceReviewRequest) Set(val *EvidenceReviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEvidenceReviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEvidenceReviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvidenceReviewRequest(val *EvidenceReviewRequest) *NullableEvidenceReviewRequest {
	return &NullableEvidenceReviewRequest{value: val, isSet: true}
}

func (v NullableEvidenceReviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvidenceReviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


