/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResolveUnappliedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveUnappliedRequest{}

// ResolveUnappliedRequest struct for ResolveUnappliedRequest
type ResolveUnappliedRequest struct {
	// One of: applied_as_credit, refunded, abandoned_property, operational_void, de_minimis_writeoff, reversal_return
	Disposition string `json:"disposition"`
}

type _ResolveUnappliedRequest ResolveUnappliedRequest

// NewResolveUnappliedRequest instantiates a new ResolveUnappliedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveUnappliedRequest(disposition string) *ResolveUnappliedRequest {
	this := ResolveUnappliedRequest{}
	this.Disposition = disposition
	return &this
}

// NewResolveUnappliedRequestWithDefaults instantiates a new ResolveUnappliedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveUnappliedRequestWithDefaults() *ResolveUnappliedRequest {
	this := ResolveUnappliedRequest{}
	return &this
}

// GetDisposition returns the Disposition field value
func (o *ResolveUnappliedRequest) GetDisposition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Disposition
}

// GetDispositionOk returns a tuple with the Disposition field value
// and a boolean to check if the value has been set.
func (o *ResolveUnappliedRequest) GetDispositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disposition, true
}

// SetDisposition sets field value
func (o *ResolveUnappliedRequest) SetDisposition(v string) {
	o.Disposition = v
}

func (o ResolveUnappliedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveUnappliedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["disposition"] = o.Disposition
	return toSerialize, nil
}

func (o *ResolveUnappliedRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disposition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveUnappliedRequest := _ResolveUnappliedRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResolveUnappliedRequest)

	if err != nil {
		return err
	}

	*o = ResolveUnappliedRequest(varResolveUnappliedRequest)

	return err
}

type NullableResolveUnappliedRequest struct {
	value *ResolveUnappliedRequest
	isSet bool
}

func (v NullableResolveUnappliedRequest) Get() *ResolveUnappliedRequest {
	return v.value
}

func (v *NullableResolveUnappliedRequest) Set(val *ResolveUnappliedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveUnappliedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveUnappliedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveUnappliedRequest(val *ResolveUnappliedRequest) *NullableResolveUnappliedRequest {
	return &NullableResolveUnappliedRequest{value: val, isSet: true}
}

func (v NullableResolveUnappliedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveUnappliedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


