/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)

// NotificationRuleBalanceThresholdValueType Type of the rule in the balance threshold specification: * `balance_value`: threshold defined by the remaining balance value based on usage and the total of grants in the current usage period * `usage_percentage`: threshold defined by the usage percentage compared to the total of grants in the current usage period * `usage_value`: threshold defined by the usage value in the current usage period * `NUMBER` (**deprecated**): see `usage_value` * `PERCENT` (**deprecated**): see `usage_percentage`
type NotificationRuleBalanceThresholdValueType string

// List of NotificationRuleBalanceThresholdValueType
const (
	NOTIFICATIONRULEBALANCETHRESHOLDVALUETYPE_Percent NotificationRuleBalanceThresholdValueType = "PERCENT"
	NOTIFICATIONRULEBALANCETHRESHOLDVALUETYPE_Number NotificationRuleBalanceThresholdValueType = "NUMBER"
	NOTIFICATIONRULEBALANCETHRESHOLDVALUETYPE_BalanceValue NotificationRuleBalanceThresholdValueType = "balance_value"
	NOTIFICATIONRULEBALANCETHRESHOLDVALUETYPE_UsagePercentage NotificationRuleBalanceThresholdValueType = "usage_percentage"
	NOTIFICATIONRULEBALANCETHRESHOLDVALUETYPE_UsageValue NotificationRuleBalanceThresholdValueType = "usage_value"
)

// All allowed values of NotificationRuleBalanceThresholdValueType enum
var AllowedNotificationRuleBalanceThresholdValueTypeEnumValues = []NotificationRuleBalanceThresholdValueType{
	"PERCENT",
	"NUMBER",
	"balance_value",
	"usage_percentage",
	"usage_value",
}

func (v *NotificationRuleBalanceThresholdValueType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationRuleBalanceThresholdValueType(value)
	for _, existing := range AllowedNotificationRuleBalanceThresholdValueTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationRuleBalanceThresholdValueType", value)
}

// NewNotificationRuleBalanceThresholdValueTypeFromValue returns a pointer to a valid NotificationRuleBalanceThresholdValueType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationRuleBalanceThresholdValueTypeFromValue(v string) (*NotificationRuleBalanceThresholdValueType, error) {
	ev := NotificationRuleBalanceThresholdValueType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationRuleBalanceThresholdValueType: valid values are %v", v, AllowedNotificationRuleBalanceThresholdValueTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationRuleBalanceThresholdValueType) IsValid() bool {
	for _, existing := range AllowedNotificationRuleBalanceThresholdValueTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NotificationRuleBalanceThresholdValueType value
func (v NotificationRuleBalanceThresholdValueType) Ptr() *NotificationRuleBalanceThresholdValueType {
	return &v
}

type NullableNotificationRuleBalanceThresholdValueType struct {
	value *NotificationRuleBalanceThresholdValueType
	isSet bool
}

func (v NullableNotificationRuleBalanceThresholdValueType) Get() *NotificationRuleBalanceThresholdValueType {
	return v.value
}

func (v *NullableNotificationRuleBalanceThresholdValueType) Set(val *NotificationRuleBalanceThresholdValueType) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationRuleBalanceThresholdValueType) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationRuleBalanceThresholdValueType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationRuleBalanceThresholdValueType(val *NotificationRuleBalanceThresholdValueType) *NullableNotificationRuleBalanceThresholdValueType {
	return &NullableNotificationRuleBalanceThresholdValueType{value: val, isSet: true}
}

func (v NullableNotificationRuleBalanceThresholdValueType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationRuleBalanceThresholdValueType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

