/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetSuiteManagedPortalMappingDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetSuiteManagedPortalMappingDeleteRequest{}

// NetSuiteManagedPortalMappingDeleteRequest struct for NetSuiteManagedPortalMappingDeleteRequest
type NetSuiteManagedPortalMappingDeleteRequest struct {
	ChangeReason string `json:"change_reason"`
	PreviewOnly *bool `json:"preview_only,omitempty"`
	PreviewAuditId *string `json:"preview_audit_id,omitempty"`
}

type _NetSuiteManagedPortalMappingDeleteRequest NetSuiteManagedPortalMappingDeleteRequest

// NewNetSuiteManagedPortalMappingDeleteRequest instantiates a new NetSuiteManagedPortalMappingDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetSuiteManagedPortalMappingDeleteRequest(changeReason string) *NetSuiteManagedPortalMappingDeleteRequest {
	this := NetSuiteManagedPortalMappingDeleteRequest{}
	this.ChangeReason = changeReason
	var previewOnly bool = false
	this.PreviewOnly = &previewOnly
	return &this
}

// NewNetSuiteManagedPortalMappingDeleteRequestWithDefaults instantiates a new NetSuiteManagedPortalMappingDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetSuiteManagedPortalMappingDeleteRequestWithDefaults() *NetSuiteManagedPortalMappingDeleteRequest {
	this := NetSuiteManagedPortalMappingDeleteRequest{}
	var previewOnly bool = false
	this.PreviewOnly = &previewOnly
	return &this
}

// GetChangeReason returns the ChangeReason field value
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetChangeReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeReason
}

// GetChangeReasonOk returns a tuple with the ChangeReason field value
// and a boolean to check if the value has been set.
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetChangeReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeReason, true
}

// SetChangeReason sets field value
func (o *NetSuiteManagedPortalMappingDeleteRequest) SetChangeReason(v string) {
	o.ChangeReason = v
}

// GetPreviewOnly returns the PreviewOnly field value if set, zero value otherwise.
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetPreviewOnly() bool {
	if o == nil || IsNil(o.PreviewOnly) {
		var ret bool
		return ret
	}
	return *o.PreviewOnly
}

// GetPreviewOnlyOk returns a tuple with the PreviewOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetPreviewOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.PreviewOnly) {
		return nil, false
	}
	return o.PreviewOnly, true
}

// HasPreviewOnly returns a boolean if a field has been set.
func (o *NetSuiteManagedPortalMappingDeleteRequest) HasPreviewOnly() bool {
	if o != nil && !IsNil(o.PreviewOnly) {
		return true
	}

	return false
}

// SetPreviewOnly gets a reference to the given bool and assigns it to the PreviewOnly field.
func (o *NetSuiteManagedPortalMappingDeleteRequest) SetPreviewOnly(v bool) {
	o.PreviewOnly = &v
}

// GetPreviewAuditId returns the PreviewAuditId field value if set, zero value otherwise.
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetPreviewAuditId() string {
	if o == nil || IsNil(o.PreviewAuditId) {
		var ret string
		return ret
	}
	return *o.PreviewAuditId
}

// GetPreviewAuditIdOk returns a tuple with the PreviewAuditId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetSuiteManagedPortalMappingDeleteRequest) GetPreviewAuditIdOk() (*string, bool) {
	if o == nil || IsNil(o.PreviewAuditId) {
		return nil, false
	}
	return o.PreviewAuditId, true
}

// HasPreviewAuditId returns a boolean if a field has been set.
func (o *NetSuiteManagedPortalMappingDeleteRequest) HasPreviewAuditId() bool {
	if o != nil && !IsNil(o.PreviewAuditId) {
		return true
	}

	return false
}

// SetPreviewAuditId gets a reference to the given string and assigns it to the PreviewAuditId field.
func (o *NetSuiteManagedPortalMappingDeleteRequest) SetPreviewAuditId(v string) {
	o.PreviewAuditId = &v
}

func (o NetSuiteManagedPortalMappingDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetSuiteManagedPortalMappingDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["change_reason"] = o.ChangeReason
	if !IsNil(o.PreviewOnly) {
		toSerialize["preview_only"] = o.PreviewOnly
	}
	if !IsNil(o.PreviewAuditId) {
		toSerialize["preview_audit_id"] = o.PreviewAuditId
	}
	return toSerialize, nil
}

func (o *NetSuiteManagedPortalMappingDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"change_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetSuiteManagedPortalMappingDeleteRequest := _NetSuiteManagedPortalMappingDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetSuiteManagedPortalMappingDeleteRequest)

	if err != nil {
		return err
	}

	*o = NetSuiteManagedPortalMappingDeleteRequest(varNetSuiteManagedPortalMappingDeleteRequest)

	return err
}

type NullableNetSuiteManagedPortalMappingDeleteRequest struct {
	value *NetSuiteManagedPortalMappingDeleteRequest
	isSet bool
}

func (v NullableNetSuiteManagedPortalMappingDeleteRequest) Get() *NetSuiteManagedPortalMappingDeleteRequest {
	return v.value
}

func (v *NullableNetSuiteManagedPortalMappingDeleteRequest) Set(val *NetSuiteManagedPortalMappingDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetSuiteManagedPortalMappingDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetSuiteManagedPortalMappingDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetSuiteManagedPortalMappingDeleteRequest(val *NetSuiteManagedPortalMappingDeleteRequest) *NullableNetSuiteManagedPortalMappingDeleteRequest {
	return &NullableNetSuiteManagedPortalMappingDeleteRequest{value: val, isSet: true}
}

func (v NullableNetSuiteManagedPortalMappingDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetSuiteManagedPortalMappingDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


