/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreditConfigPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditConfigPayload{}

// CreditConfigPayload struct for CreditConfigPayload
type CreditConfigPayload struct {
	Enabled bool `json:"enabled"`
	GlobalPoolEnabled bool `json:"globalPoolEnabled"`
	FeaturePoolsEnabled bool `json:"featurePoolsEnabled"`
	InitialAmount Initialamount `json:"initialAmount"`
	RecurringAmount Recurringamount `json:"recurringAmount"`
	Cadence string `json:"cadence"`
	ExpiresInDays int32 `json:"expiresInDays"`
	RolloverEnabled bool `json:"rolloverEnabled"`
	RolloverPercent NullableRolloverpercent `json:"rolloverPercent,omitempty"`
	RolloverCapAmount NullableRollovercapamount `json:"rolloverCapAmount,omitempty"`
	RolloverExpiresAfterDays *int32 `json:"rolloverExpiresAfterDays,omitempty"`
	RolloverPriorityDelta *int32 `json:"rolloverPriorityDelta,omitempty"`
	FeaturePools []FeaturePoolPayload `json:"featurePools,omitempty"`
}

type _CreditConfigPayload CreditConfigPayload

// NewCreditConfigPayload instantiates a new CreditConfigPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditConfigPayload(enabled bool, globalPoolEnabled bool, featurePoolsEnabled bool, initialAmount Initialamount, recurringAmount Recurringamount, cadence string, expiresInDays int32, rolloverEnabled bool) *CreditConfigPayload {
	this := CreditConfigPayload{}
	this.Enabled = enabled
	this.GlobalPoolEnabled = globalPoolEnabled
	this.FeaturePoolsEnabled = featurePoolsEnabled
	this.InitialAmount = initialAmount
	this.RecurringAmount = recurringAmount
	this.Cadence = cadence
	this.ExpiresInDays = expiresInDays
	this.RolloverEnabled = rolloverEnabled
	return &this
}

// NewCreditConfigPayloadWithDefaults instantiates a new CreditConfigPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditConfigPayloadWithDefaults() *CreditConfigPayload {
	this := CreditConfigPayload{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CreditConfigPayload) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreditConfigPayload) SetEnabled(v bool) {
	o.Enabled = v
}

// GetGlobalPoolEnabled returns the GlobalPoolEnabled field value
func (o *CreditConfigPayload) GetGlobalPoolEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.GlobalPoolEnabled
}

// GetGlobalPoolEnabledOk returns a tuple with the GlobalPoolEnabled field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetGlobalPoolEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalPoolEnabled, true
}

// SetGlobalPoolEnabled sets field value
func (o *CreditConfigPayload) SetGlobalPoolEnabled(v bool) {
	o.GlobalPoolEnabled = v
}

// GetFeaturePoolsEnabled returns the FeaturePoolsEnabled field value
func (o *CreditConfigPayload) GetFeaturePoolsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FeaturePoolsEnabled
}

// GetFeaturePoolsEnabledOk returns a tuple with the FeaturePoolsEnabled field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetFeaturePoolsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeaturePoolsEnabled, true
}

// SetFeaturePoolsEnabled sets field value
func (o *CreditConfigPayload) SetFeaturePoolsEnabled(v bool) {
	o.FeaturePoolsEnabled = v
}

// GetInitialAmount returns the InitialAmount field value
func (o *CreditConfigPayload) GetInitialAmount() Initialamount {
	if o == nil {
		var ret Initialamount
		return ret
	}

	return o.InitialAmount
}

// GetInitialAmountOk returns a tuple with the InitialAmount field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetInitialAmountOk() (*Initialamount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitialAmount, true
}

// SetInitialAmount sets field value
func (o *CreditConfigPayload) SetInitialAmount(v Initialamount) {
	o.InitialAmount = v
}

// GetRecurringAmount returns the RecurringAmount field value
func (o *CreditConfigPayload) GetRecurringAmount() Recurringamount {
	if o == nil {
		var ret Recurringamount
		return ret
	}

	return o.RecurringAmount
}

// GetRecurringAmountOk returns a tuple with the RecurringAmount field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetRecurringAmountOk() (*Recurringamount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecurringAmount, true
}

// SetRecurringAmount sets field value
func (o *CreditConfigPayload) SetRecurringAmount(v Recurringamount) {
	o.RecurringAmount = v
}

// GetCadence returns the Cadence field value
func (o *CreditConfigPayload) GetCadence() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetCadenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cadence, true
}

// SetCadence sets field value
func (o *CreditConfigPayload) SetCadence(v string) {
	o.Cadence = v
}

// GetExpiresInDays returns the ExpiresInDays field value
func (o *CreditConfigPayload) GetExpiresInDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresInDays
}

// GetExpiresInDaysOk returns a tuple with the ExpiresInDays field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetExpiresInDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresInDays, true
}

// SetExpiresInDays sets field value
func (o *CreditConfigPayload) SetExpiresInDays(v int32) {
	o.ExpiresInDays = v
}

// GetRolloverEnabled returns the RolloverEnabled field value
func (o *CreditConfigPayload) GetRolloverEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RolloverEnabled
}

// GetRolloverEnabledOk returns a tuple with the RolloverEnabled field value
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetRolloverEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolloverEnabled, true
}

// SetRolloverEnabled sets field value
func (o *CreditConfigPayload) SetRolloverEnabled(v bool) {
	o.RolloverEnabled = v
}

// GetRolloverPercent returns the RolloverPercent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditConfigPayload) GetRolloverPercent() Rolloverpercent {
	if o == nil || IsNil(o.RolloverPercent.Get()) {
		var ret Rolloverpercent
		return ret
	}
	return *o.RolloverPercent.Get()
}

// GetRolloverPercentOk returns a tuple with the RolloverPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditConfigPayload) GetRolloverPercentOk() (*Rolloverpercent, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloverPercent.Get(), o.RolloverPercent.IsSet()
}

// HasRolloverPercent returns a boolean if a field has been set.
func (o *CreditConfigPayload) HasRolloverPercent() bool {
	if o != nil && o.RolloverPercent.IsSet() {
		return true
	}

	return false
}

// SetRolloverPercent gets a reference to the given NullableRolloverpercent and assigns it to the RolloverPercent field.
func (o *CreditConfigPayload) SetRolloverPercent(v Rolloverpercent) {
	o.RolloverPercent.Set(&v)
}
// SetRolloverPercentNil sets the value for RolloverPercent to be an explicit nil
func (o *CreditConfigPayload) SetRolloverPercentNil() {
	o.RolloverPercent.Set(nil)
}

// UnsetRolloverPercent ensures that no value is present for RolloverPercent, not even an explicit nil
func (o *CreditConfigPayload) UnsetRolloverPercent() {
	o.RolloverPercent.Unset()
}

// GetRolloverCapAmount returns the RolloverCapAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditConfigPayload) GetRolloverCapAmount() Rollovercapamount {
	if o == nil || IsNil(o.RolloverCapAmount.Get()) {
		var ret Rollovercapamount
		return ret
	}
	return *o.RolloverCapAmount.Get()
}

// GetRolloverCapAmountOk returns a tuple with the RolloverCapAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditConfigPayload) GetRolloverCapAmountOk() (*Rollovercapamount, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloverCapAmount.Get(), o.RolloverCapAmount.IsSet()
}

// HasRolloverCapAmount returns a boolean if a field has been set.
func (o *CreditConfigPayload) HasRolloverCapAmount() bool {
	if o != nil && o.RolloverCapAmount.IsSet() {
		return true
	}

	return false
}

// SetRolloverCapAmount gets a reference to the given NullableRollovercapamount and assigns it to the RolloverCapAmount field.
func (o *CreditConfigPayload) SetRolloverCapAmount(v Rollovercapamount) {
	o.RolloverCapAmount.Set(&v)
}
// SetRolloverCapAmountNil sets the value for RolloverCapAmount to be an explicit nil
func (o *CreditConfigPayload) SetRolloverCapAmountNil() {
	o.RolloverCapAmount.Set(nil)
}

// UnsetRolloverCapAmount ensures that no value is present for RolloverCapAmount, not even an explicit nil
func (o *CreditConfigPayload) UnsetRolloverCapAmount() {
	o.RolloverCapAmount.Unset()
}

// GetRolloverExpiresAfterDays returns the RolloverExpiresAfterDays field value if set, zero value otherwise.
func (o *CreditConfigPayload) GetRolloverExpiresAfterDays() int32 {
	if o == nil || IsNil(o.RolloverExpiresAfterDays) {
		var ret int32
		return ret
	}
	return *o.RolloverExpiresAfterDays
}

// GetRolloverExpiresAfterDaysOk returns a tuple with the RolloverExpiresAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetRolloverExpiresAfterDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.RolloverExpiresAfterDays) {
		return nil, false
	}
	return o.RolloverExpiresAfterDays, true
}

// HasRolloverExpiresAfterDays returns a boolean if a field has been set.
func (o *CreditConfigPayload) HasRolloverExpiresAfterDays() bool {
	if o != nil && !IsNil(o.RolloverExpiresAfterDays) {
		return true
	}

	return false
}

// SetRolloverExpiresAfterDays gets a reference to the given int32 and assigns it to the RolloverExpiresAfterDays field.
func (o *CreditConfigPayload) SetRolloverExpiresAfterDays(v int32) {
	o.RolloverExpiresAfterDays = &v
}

// GetRolloverPriorityDelta returns the RolloverPriorityDelta field value if set, zero value otherwise.
func (o *CreditConfigPayload) GetRolloverPriorityDelta() int32 {
	if o == nil || IsNil(o.RolloverPriorityDelta) {
		var ret int32
		return ret
	}
	return *o.RolloverPriorityDelta
}

// GetRolloverPriorityDeltaOk returns a tuple with the RolloverPriorityDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetRolloverPriorityDeltaOk() (*int32, bool) {
	if o == nil || IsNil(o.RolloverPriorityDelta) {
		return nil, false
	}
	return o.RolloverPriorityDelta, true
}

// HasRolloverPriorityDelta returns a boolean if a field has been set.
func (o *CreditConfigPayload) HasRolloverPriorityDelta() bool {
	if o != nil && !IsNil(o.RolloverPriorityDelta) {
		return true
	}

	return false
}

// SetRolloverPriorityDelta gets a reference to the given int32 and assigns it to the RolloverPriorityDelta field.
func (o *CreditConfigPayload) SetRolloverPriorityDelta(v int32) {
	o.RolloverPriorityDelta = &v
}

// GetFeaturePools returns the FeaturePools field value if set, zero value otherwise.
func (o *CreditConfigPayload) GetFeaturePools() []FeaturePoolPayload {
	if o == nil || IsNil(o.FeaturePools) {
		var ret []FeaturePoolPayload
		return ret
	}
	return o.FeaturePools
}

// GetFeaturePoolsOk returns a tuple with the FeaturePools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditConfigPayload) GetFeaturePoolsOk() ([]FeaturePoolPayload, bool) {
	if o == nil || IsNil(o.FeaturePools) {
		return nil, false
	}
	return o.FeaturePools, true
}

// HasFeaturePools returns a boolean if a field has been set.
func (o *CreditConfigPayload) HasFeaturePools() bool {
	if o != nil && !IsNil(o.FeaturePools) {
		return true
	}

	return false
}

// SetFeaturePools gets a reference to the given []FeaturePoolPayload and assigns it to the FeaturePools field.
func (o *CreditConfigPayload) SetFeaturePools(v []FeaturePoolPayload) {
	o.FeaturePools = v
}

func (o CreditConfigPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditConfigPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["globalPoolEnabled"] = o.GlobalPoolEnabled
	toSerialize["featurePoolsEnabled"] = o.FeaturePoolsEnabled
	toSerialize["initialAmount"] = o.InitialAmount
	toSerialize["recurringAmount"] = o.RecurringAmount
	toSerialize["cadence"] = o.Cadence
	toSerialize["expiresInDays"] = o.ExpiresInDays
	toSerialize["rolloverEnabled"] = o.RolloverEnabled
	if o.RolloverPercent.IsSet() {
		toSerialize["rolloverPercent"] = o.RolloverPercent.Get()
	}
	if o.RolloverCapAmount.IsSet() {
		toSerialize["rolloverCapAmount"] = o.RolloverCapAmount.Get()
	}
	if !IsNil(o.RolloverExpiresAfterDays) {
		toSerialize["rolloverExpiresAfterDays"] = o.RolloverExpiresAfterDays
	}
	if !IsNil(o.RolloverPriorityDelta) {
		toSerialize["rolloverPriorityDelta"] = o.RolloverPriorityDelta
	}
	if !IsNil(o.FeaturePools) {
		toSerialize["featurePools"] = o.FeaturePools
	}
	return toSerialize, nil
}

func (o *CreditConfigPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"globalPoolEnabled",
		"featurePoolsEnabled",
		"initialAmount",
		"recurringAmount",
		"cadence",
		"expiresInDays",
		"rolloverEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditConfigPayload := _CreditConfigPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreditConfigPayload)

	if err != nil {
		return err
	}

	*o = CreditConfigPayload(varCreditConfigPayload)

	return err
}

type NullableCreditConfigPayload struct {
	value *CreditConfigPayload
	isSet bool
}

func (v NullableCreditConfigPayload) Get() *CreditConfigPayload {
	return v.value
}

func (v *NullableCreditConfigPayload) Set(val *CreditConfigPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditConfigPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditConfigPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditConfigPayload(val *CreditConfigPayload) *NullableCreditConfigPayload {
	return &NullableCreditConfigPayload{value: val, isSet: true}
}

func (v NullableCreditConfigPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditConfigPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


