/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
)

// checks if the CustomInvoicingFinalizedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomInvoicingFinalizedRequest{}

// CustomInvoicingFinalizedRequest Information to finalize the invoice.  If invoicing.invoiceNumber is not set, then a new invoice number will be generated (INV- prefix).
type CustomInvoicingFinalizedRequest struct {
	// The result of the synchronization.
	Invoicing *CustomInvoicingFinalizedInvoicingRequest `json:"invoicing,omitempty"`
	// The result of the payment synchronization.
	Payment *CustomInvoicingFinalizedPaymentRequest `json:"payment,omitempty"`
}

// NewCustomInvoicingFinalizedRequest instantiates a new CustomInvoicingFinalizedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomInvoicingFinalizedRequest() *CustomInvoicingFinalizedRequest {
	this := CustomInvoicingFinalizedRequest{}
	return &this
}

// NewCustomInvoicingFinalizedRequestWithDefaults instantiates a new CustomInvoicingFinalizedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomInvoicingFinalizedRequestWithDefaults() *CustomInvoicingFinalizedRequest {
	this := CustomInvoicingFinalizedRequest{}
	return &this
}

// GetInvoicing returns the Invoicing field value if set, zero value otherwise.
func (o *CustomInvoicingFinalizedRequest) GetInvoicing() CustomInvoicingFinalizedInvoicingRequest {
	if o == nil || IsNil(o.Invoicing) {
		var ret CustomInvoicingFinalizedInvoicingRequest
		return ret
	}
	return *o.Invoicing
}

// GetInvoicingOk returns a tuple with the Invoicing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomInvoicingFinalizedRequest) GetInvoicingOk() (*CustomInvoicingFinalizedInvoicingRequest, bool) {
	if o == nil || IsNil(o.Invoicing) {
		return nil, false
	}
	return o.Invoicing, true
}

// HasInvoicing returns a boolean if a field has been set.
func (o *CustomInvoicingFinalizedRequest) HasInvoicing() bool {
	if o != nil && !IsNil(o.Invoicing) {
		return true
	}

	return false
}

// SetInvoicing gets a reference to the given CustomInvoicingFinalizedInvoicingRequest and assigns it to the Invoicing field.
func (o *CustomInvoicingFinalizedRequest) SetInvoicing(v CustomInvoicingFinalizedInvoicingRequest) {
	o.Invoicing = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *CustomInvoicingFinalizedRequest) GetPayment() CustomInvoicingFinalizedPaymentRequest {
	if o == nil || IsNil(o.Payment) {
		var ret CustomInvoicingFinalizedPaymentRequest
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomInvoicingFinalizedRequest) GetPaymentOk() (*CustomInvoicingFinalizedPaymentRequest, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *CustomInvoicingFinalizedRequest) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given CustomInvoicingFinalizedPaymentRequest and assigns it to the Payment field.
func (o *CustomInvoicingFinalizedRequest) SetPayment(v CustomInvoicingFinalizedPaymentRequest) {
	o.Payment = &v
}

func (o CustomInvoicingFinalizedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomInvoicingFinalizedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invoicing) {
		toSerialize["invoicing"] = o.Invoicing
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	return toSerialize, nil
}

type NullableCustomInvoicingFinalizedRequest struct {
	value *CustomInvoicingFinalizedRequest
	isSet bool
}

func (v NullableCustomInvoicingFinalizedRequest) Get() *CustomInvoicingFinalizedRequest {
	return v.value
}

func (v *NullableCustomInvoicingFinalizedRequest) Set(val *CustomInvoicingFinalizedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomInvoicingFinalizedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomInvoicingFinalizedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomInvoicingFinalizedRequest(val *CustomInvoicingFinalizedRequest) *NullableCustomInvoicingFinalizedRequest {
	return &NullableCustomInvoicingFinalizedRequest{value: val, isSet: true}
}

func (v NullableCustomInvoicingFinalizedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomInvoicingFinalizedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


