/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.2.0-rc1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"fmt"
)


// CreateStripeCheckoutSessionRequestCustomer Provide a customer ID or key to use an existing OpenMeter customer. or provide a customer object to create a new customer.
type CreateStripeCheckoutSessionRequestCustomer struct {
	CustomerCreate *CustomerCreate
	CustomerId *CustomerId
	CustomerKey *CustomerKey
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreateStripeCheckoutSessionRequestCustomer) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into CustomerCreate
	err = json.Unmarshal(data, &dst.CustomerCreate);
	if err == nil {
		jsonCustomerCreate, _ := json.Marshal(dst.CustomerCreate)
		if string(jsonCustomerCreate) == "{}" { // empty struct
			dst.CustomerCreate = nil
		} else {
			return nil // data stored in dst.CustomerCreate, return on the first match
		}
	} else {
		dst.CustomerCreate = nil
	}

	// try to unmarshal JSON data into CustomerId
	err = json.Unmarshal(data, &dst.CustomerId);
	if err == nil {
		jsonCustomerId, _ := json.Marshal(dst.CustomerId)
		if string(jsonCustomerId) == "{}" { // empty struct
			dst.CustomerId = nil
		} else {
			return nil // data stored in dst.CustomerId, return on the first match
		}
	} else {
		dst.CustomerId = nil
	}

	// try to unmarshal JSON data into CustomerKey
	err = json.Unmarshal(data, &dst.CustomerKey);
	if err == nil {
		jsonCustomerKey, _ := json.Marshal(dst.CustomerKey)
		if string(jsonCustomerKey) == "{}" { // empty struct
			dst.CustomerKey = nil
		} else {
			return nil // data stored in dst.CustomerKey, return on the first match
		}
	} else {
		dst.CustomerKey = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreateStripeCheckoutSessionRequestCustomer)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *CreateStripeCheckoutSessionRequestCustomer) MarshalJSON() ([]byte, error) {
	if src.CustomerCreate != nil {
		return json.Marshal(&src.CustomerCreate)
	}

	if src.CustomerId != nil {
		return json.Marshal(&src.CustomerId)
	}

	if src.CustomerKey != nil {
		return json.Marshal(&src.CustomerKey)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCreateStripeCheckoutSessionRequestCustomer struct {
	value *CreateStripeCheckoutSessionRequestCustomer
	isSet bool
}

func (v NullableCreateStripeCheckoutSessionRequestCustomer) Get() *CreateStripeCheckoutSessionRequestCustomer {
	return v.value
}

func (v *NullableCreateStripeCheckoutSessionRequestCustomer) Set(val *CreateStripeCheckoutSessionRequestCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStripeCheckoutSessionRequestCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStripeCheckoutSessionRequestCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStripeCheckoutSessionRequestCustomer(val *CreateStripeCheckoutSessionRequestCustomer) *NullableCreateStripeCheckoutSessionRequestCustomer {
	return &NullableCreateStripeCheckoutSessionRequestCustomer{value: val, isSet: true}
}

func (v NullableCreateStripeCheckoutSessionRequestCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStripeCheckoutSessionRequestCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


