/*
Moolabs API

Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.

API version: 0.0.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MeterCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeterCreate{}

// MeterCreate A meter create model.
type MeterCreate struct {
	// Optional description of the resource. Maximum 1024 characters.
	Description *string `json:"description,omitempty"`
	// Additional metadata for the resource.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Human-readable name for the resource. Between 1 and 256 characters. Defaults to the slug if not specified.
	Name *string `json:"name,omitempty"`
	// A unique, human-readable identifier for the meter. Must consist only alphanumeric and underscore characters.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(?:_[a-z0-9]+)*$"`
	// The aggregation type to use for the meter.
	Aggregation MeterAggregation `json:"aggregation"`
	// The event type to aggregate.
	EventType string `json:"eventType"`
	// The date since the meter should include events. Useful to skip old events. If not specified, all historical events are included.
	EventFrom *time.Time `json:"eventFrom,omitempty"`
	// JSONPath expression to extract the value from the ingested event's data property.  The ingested value for SUM, AVG, MIN, and MAX aggregations is a number or a string that can be parsed to a number.  For UNIQUE_COUNT aggregation, the ingested value must be a string. For COUNT aggregation the valueProperty is ignored.
	ValueProperty *string `json:"valueProperty,omitempty"`
	// Named JSONPath expressions to extract the group by values from the event data.  Keys must be unique and consist only alphanumeric and underscore characters.
	GroupBy map[string]string `json:"groupBy,omitempty"`
}

type _MeterCreate MeterCreate

// NewMeterCreate instantiates a new MeterCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeterCreate(slug string, aggregation MeterAggregation, eventType string) *MeterCreate {
	this := MeterCreate{}
	this.Slug = slug
	this.Aggregation = aggregation
	this.EventType = eventType
	return &this
}

// NewMeterCreateWithDefaults instantiates a new MeterCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterCreateWithDefaults() *MeterCreate {
	this := MeterCreate{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MeterCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MeterCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MeterCreate) SetDescription(v string) {
	o.Description = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *MeterCreate) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *MeterCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *MeterCreate) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MeterCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MeterCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MeterCreate) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value
func (o *MeterCreate) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *MeterCreate) SetSlug(v string) {
	o.Slug = v
}

// GetAggregation returns the Aggregation field value
func (o *MeterCreate) GetAggregation() MeterAggregation {
	if o == nil {
		var ret MeterAggregation
		return ret
	}

	return o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetAggregationOk() (*MeterAggregation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregation, true
}

// SetAggregation sets field value
func (o *MeterCreate) SetAggregation(v MeterAggregation) {
	o.Aggregation = v
}

// GetEventType returns the EventType field value
func (o *MeterCreate) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *MeterCreate) SetEventType(v string) {
	o.EventType = v
}

// GetEventFrom returns the EventFrom field value if set, zero value otherwise.
func (o *MeterCreate) GetEventFrom() time.Time {
	if o == nil || IsNil(o.EventFrom) {
		var ret time.Time
		return ret
	}
	return *o.EventFrom
}

// GetEventFromOk returns a tuple with the EventFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetEventFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EventFrom) {
		return nil, false
	}
	return o.EventFrom, true
}

// HasEventFrom returns a boolean if a field has been set.
func (o *MeterCreate) HasEventFrom() bool {
	if o != nil && !IsNil(o.EventFrom) {
		return true
	}

	return false
}

// SetEventFrom gets a reference to the given time.Time and assigns it to the EventFrom field.
func (o *MeterCreate) SetEventFrom(v time.Time) {
	o.EventFrom = &v
}

// GetValueProperty returns the ValueProperty field value if set, zero value otherwise.
func (o *MeterCreate) GetValueProperty() string {
	if o == nil || IsNil(o.ValueProperty) {
		var ret string
		return ret
	}
	return *o.ValueProperty
}

// GetValuePropertyOk returns a tuple with the ValueProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetValuePropertyOk() (*string, bool) {
	if o == nil || IsNil(o.ValueProperty) {
		return nil, false
	}
	return o.ValueProperty, true
}

// HasValueProperty returns a boolean if a field has been set.
func (o *MeterCreate) HasValueProperty() bool {
	if o != nil && !IsNil(o.ValueProperty) {
		return true
	}

	return false
}

// SetValueProperty gets a reference to the given string and assigns it to the ValueProperty field.
func (o *MeterCreate) SetValueProperty(v string) {
	o.ValueProperty = &v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *MeterCreate) GetGroupBy() map[string]string {
	if o == nil || IsNil(o.GroupBy) {
		var ret map[string]string
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterCreate) GetGroupByOk() (map[string]string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return map[string]string{}, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *MeterCreate) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given map[string]string and assigns it to the GroupBy field.
func (o *MeterCreate) SetGroupBy(v map[string]string) {
	o.GroupBy = v
}

func (o MeterCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeterCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["slug"] = o.Slug
	toSerialize["aggregation"] = o.Aggregation
	toSerialize["eventType"] = o.EventType
	if !IsNil(o.EventFrom) {
		toSerialize["eventFrom"] = o.EventFrom
	}
	if !IsNil(o.ValueProperty) {
		toSerialize["valueProperty"] = o.ValueProperty
	}
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	return toSerialize, nil
}

func (o *MeterCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"aggregation",
		"eventType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeterCreate := _MeterCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeterCreate)

	if err != nil {
		return err
	}

	*o = MeterCreate(varMeterCreate)

	return err
}

type NullableMeterCreate struct {
	value *MeterCreate
	isSet bool
}

func (v NullableMeterCreate) Get() *MeterCreate {
	return v.value
}

func (v *NullableMeterCreate) Set(val *MeterCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableMeterCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableMeterCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeterCreate(val *MeterCreate) *NullableMeterCreate {
	return &NullableMeterCreate{value: val, isSet: true}
}

func (v NullableMeterCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeterCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


