/*
Moolabs API

Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.

API version: 0.2.0-rc3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moolabs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GrantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantResponse{}

// GrantResponse Grant response.
type GrantResponse struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	PoolId string `json:"pool_id"`
	WalletId string `json:"wallet_id"`
	AmountMicros int32 `json:"amount_micros"`
	RemainingMicros int32 `json:"remaining_micros"`
	Priority int32 `json:"priority"`
	ValidFrom time.Time `json:"valid_from"`
	ExpiresAt time.Time `json:"expires_at"`
	SourceType string `json:"source_type"`
	SourceId string `json:"source_id"`
	SubscriptionId string `json:"subscription_id"`
	ScopeType ScopeType `json:"scope_type"`
	RolloverMode RolloverMode `json:"rollover_mode"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _GrantResponse GrantResponse

// NewGrantResponse instantiates a new GrantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantResponse(id string, tenantId string, poolId string, walletId string, amountMicros int32, remainingMicros int32, priority int32, validFrom time.Time, expiresAt time.Time, sourceType string, sourceId string, subscriptionId string, scopeType ScopeType, rolloverMode RolloverMode, createdAt time.Time, updatedAt time.Time) *GrantResponse {
	this := GrantResponse{}
	this.Id = id
	this.TenantId = tenantId
	this.PoolId = poolId
	this.WalletId = walletId
	this.AmountMicros = amountMicros
	this.RemainingMicros = remainingMicros
	this.Priority = priority
	this.ValidFrom = validFrom
	this.ExpiresAt = expiresAt
	this.SourceType = sourceType
	this.SourceId = sourceId
	this.SubscriptionId = subscriptionId
	this.ScopeType = scopeType
	this.RolloverMode = rolloverMode
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGrantResponseWithDefaults instantiates a new GrantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantResponseWithDefaults() *GrantResponse {
	this := GrantResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GrantResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GrantResponse) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *GrantResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *GrantResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetPoolId returns the PoolId field value
func (o *GrantResponse) GetPoolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolId
}

// GetPoolIdOk returns a tuple with the PoolId field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetPoolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolId, true
}

// SetPoolId sets field value
func (o *GrantResponse) SetPoolId(v string) {
	o.PoolId = v
}

// GetWalletId returns the WalletId field value
func (o *GrantResponse) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *GrantResponse) SetWalletId(v string) {
	o.WalletId = v
}

// GetAmountMicros returns the AmountMicros field value
func (o *GrantResponse) GetAmountMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmountMicros
}

// GetAmountMicrosOk returns a tuple with the AmountMicros field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetAmountMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountMicros, true
}

// SetAmountMicros sets field value
func (o *GrantResponse) SetAmountMicros(v int32) {
	o.AmountMicros = v
}

// GetRemainingMicros returns the RemainingMicros field value
func (o *GrantResponse) GetRemainingMicros() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RemainingMicros
}

// GetRemainingMicrosOk returns a tuple with the RemainingMicros field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetRemainingMicrosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemainingMicros, true
}

// SetRemainingMicros sets field value
func (o *GrantResponse) SetRemainingMicros(v int32) {
	o.RemainingMicros = v
}

// GetPriority returns the Priority field value
func (o *GrantResponse) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *GrantResponse) SetPriority(v int32) {
	o.Priority = v
}

// GetValidFrom returns the ValidFrom field value
func (o *GrantResponse) GetValidFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetValidFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *GrantResponse) SetValidFrom(v time.Time) {
	o.ValidFrom = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *GrantResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *GrantResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetSourceType returns the SourceType field value
func (o *GrantResponse) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *GrantResponse) SetSourceType(v string) {
	o.SourceType = v
}

// GetSourceId returns the SourceId field value
func (o *GrantResponse) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *GrantResponse) SetSourceId(v string) {
	o.SourceId = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *GrantResponse) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *GrantResponse) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetScopeType returns the ScopeType field value
func (o *GrantResponse) GetScopeType() ScopeType {
	if o == nil {
		var ret ScopeType
		return ret
	}

	return o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetScopeTypeOk() (*ScopeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeType, true
}

// SetScopeType sets field value
func (o *GrantResponse) SetScopeType(v ScopeType) {
	o.ScopeType = v
}

// GetRolloverMode returns the RolloverMode field value
func (o *GrantResponse) GetRolloverMode() RolloverMode {
	if o == nil {
		var ret RolloverMode
		return ret
	}

	return o.RolloverMode
}

// GetRolloverModeOk returns a tuple with the RolloverMode field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetRolloverModeOk() (*RolloverMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolloverMode, true
}

// SetRolloverMode sets field value
func (o *GrantResponse) SetRolloverMode(v RolloverMode) {
	o.RolloverMode = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GrantResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GrantResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GrantResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GrantResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GrantResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GrantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["pool_id"] = o.PoolId
	toSerialize["wallet_id"] = o.WalletId
	toSerialize["amount_micros"] = o.AmountMicros
	toSerialize["remaining_micros"] = o.RemainingMicros
	toSerialize["priority"] = o.Priority
	toSerialize["valid_from"] = o.ValidFrom
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["source_type"] = o.SourceType
	toSerialize["source_id"] = o.SourceId
	toSerialize["subscription_id"] = o.SubscriptionId
	toSerialize["scope_type"] = o.ScopeType
	toSerialize["rollover_mode"] = o.RolloverMode
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GrantResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"pool_id",
		"wallet_id",
		"amount_micros",
		"remaining_micros",
		"priority",
		"valid_from",
		"expires_at",
		"source_type",
		"source_id",
		"subscription_id",
		"scope_type",
		"rollover_mode",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantResponse := _GrantResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrantResponse)

	if err != nil {
		return err
	}

	*o = GrantResponse(varGrantResponse)

	return err
}

type NullableGrantResponse struct {
	value *GrantResponse
	isSet bool
}

func (v NullableGrantResponse) Get() *GrantResponse {
	return v.value
}

func (v *NullableGrantResponse) Set(val *GrantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantResponse(val *GrantResponse) *NullableGrantResponse {
	return &NullableGrantResponse{value: val, isSet: true}
}

func (v NullableGrantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


